- package-lock.json
- package.json
- src/components/DetailsPanelEvent.vue
- src/components/SqlCode.vue
- src/components/trace/TraceNodeBodySql.vue
> feat: highlight SQL syntax in Details panel

- src/components/Instructions.vue
- src/scss/_variables.scss
Trace instructions are added to maps. 
**NOTE:** Needs to be set to be open by default when first opening an AppMap
> feat: Trace instructions are added

- src/components/Instructions.vue
> style: update ux for instructions

- src/pages/VsCodeExtension.vue
Make `isEmptyAppMap` property computed and check `AppMap` contents after `AppMap` object creation.
> fix: make `isEmptyAppMap` property computed

- src/lib/models/event.js
@dustinbyrne this file contains an errant log statement
> Remove console.log statement

- src/components/Container.vue
- src/components/DiagramTrace.vue
- src/lib/diagrams/components/componentDiagram/graph/index.js
- src/lib/diagrams/components/componentDiagram/index.js
- src/lib/diagrams/helpers/container/index.js
- src/lib/diagrams/util.js
> feat: zoom in/out selected object when clicking on zoom buttons

- src/components/Instructions.vue
> Edit lists styling in instructions

- src/lib/diagrams/components/componentDiagram/graph/groups/clusterGroup.js
- src/lib/diagrams/components/componentDiagram/graph/groups/labelGroup.js
- src/lib/diagrams/components/componentDiagram/graph/groups/nodeGroup.js
- src/lib/diagrams/components/componentDiagram/graph/index.js
- src/lib/diagrams/components/componentDiagram/index.js
- src/scss/diagrams/components/_diagram.scss
- tests/e2e/specs/componentDiagram.spec.js
> feat: expand/collapse packages with single click on icon

- src/components/DetailsPanelEvent.vue
> fix: don't display 'View source' button for HTTP and SQL events

- src/pages/VsCodeExtension.vue
> fix: resize panel in VSCode extension

- src/components/DetailsPanelEdge.vue
- src/components/DetailsPanelListPairs.vue
- tests/e2e/specs/vsCodeExtension.spec.js
NB! Probably we need a styling to display from/to pairs.
Fixes: #38
> feat: show pair of 'from' and 'to' objects when clicking on edge

- src/components/DiagramComponent.vue
> fix: highlight function's class on Dependency Map when function was selected in Trace view

- src/pages/VsCodeExtension.vue
- Fixed an issue where text would be selected when dragging and cause the drag to fail
- Relaxed the size constraints to reduce snapping in small/narrow windows
> Panel resizing fixes

- src/lib/diagrams/components/componentDiagram/graph/groups/clusterGroup.js
- src/lib/diagrams/components/componentDiagram/graph/groups/labelGroup.js
- src/lib/diagrams/components/componentDiagram/graph/index.js
- src/scss/diagrams/components/_diagram.scss
> fix: cut long label when package is expanded

- src/components/Notification.vue
- adds light styling for the notifications dropdown
- partner PR with `appmap-mode` in **vscode-appland** repo (iframe styled there)
> style: notification banner & dropdown

- src/components/trace/TraceEventBlock.vue
- src/components/trace/TraceNode.vue
> fix: blink node when it was focused from eye button

- src/components/Notification.vue
add some styling so notification bar looks clickable
> style: notification bar looks clickable

- src/components/DetailsSearch.vue
> fix: use package color from Dependency Map in search panel packages list

- src/components/DetailsSearch.vue
> feat: show labels as cloud tags

- .travis.yml
This tiny change fixes failed Travis deploy script
> fix: Travis deploy script

- packages/components/src/components/DetailsSearch.vue
> fix: prevent form submit in Details search

- packages/components/src/components/trace/TraceNodeBodyDefault.vue
- packages/components/src/components/trace/TraceNodeBodyHttp.vue
> fix: trace port incorrect names when AppMap was changed

- packages/cli/package.json
- packages/cli/src/cli.js
- packages/cli/src/functionStats.js
- packages/cli/src/inspect/fields.js
- packages/cli/src/inspect/print.js
- packages/cli/src/search/codeObjectMatcher.js
- packages/cli/src/search/findCodeObjects.js
- packages/cli/src/search/findEvents.js
- packages/cli/src/search/matchSpec.js
- packages/cli/src/search/trigram.js
- packages/cli/src/search/types.d.ts
- packages/cli/src/utils.js
- packages/cli/tests/unit/inspect.spec.js
Search by package, class, database, http, query, route.
Show proper trigrams for these searches.
Show progress bar while loading results.
> feat: Search by package and class

- packages/components/src/components/DetailsSearch.vue
- packages/components/src/scss/_variables.scss
> feat: update Search panel styling

- packages/components/src/components/DetailsPanel.vue
> feat: styles for AppMap "View source" link

- packages/cli/src/fingerprint/algorithms.js
- packages/cli/src/fingerprint/canonicalize/eventTree.js
- packages/cli/src/fingerprint/fingerprinter.js
- packages/cli/src/search/codeObjectMatcher.js
- packages/cli/tests/unit/fingerprint/canonicalize.spec.js
- packages/cli/tests/unit/fixtures/canonicalize/revoke_api_key.info.json
- packages/cli/tests/unit/fixtures/canonicalize/revoke_api_key.update.json
fix: Suppress a benign warning in event search.
I tried to fix this before, but screwed it up. This time it's a robust solution.
> fix: Fix parent tree assignment in canonicalization

- packages/cli/src/agentInstaller/javaAgentInstaller.js
- packages/cli/src/agentInstaller/pythonAgentInstaller.js
- packages/cli/src/agentInstaller/rubyAgentInstaller.js
- packages/cli/src/cli.js
- packages/cli/tests/unit/agentInstall/python.spec.js
These changes fix the wording and the flows for both flavors of python
agent installation.
> fix: Reword instructions for python agent install

- packages/components/src/stories/VsCodeExtension.stories.js
- packages/components/tests/e2e/specs/vsCodeExtension.spec.js
> feat: e2e tests for global filters

- packages/components/src/components/DetailsLabel.vue
- packages/components/src/components/DetailsPanel.vue
- packages/components/src/components/DetailsPanelClass.vue
- packages/components/src/components/DetailsPanelEvent.vue
- packages/components/src/components/DetailsPanelFunction.vue
- packages/components/src/components/DetailsPanelHeader.vue
- packages/components/src/components/DetailsPanelQuery.vue
- packages/components/src/components/DetailsPanelRoute.vue
- packages/components/src/components/DetailsSearch.vue
- packages/components/src/components/DiagramComponent.vue
- packages/components/src/components/trace/TraceNode.vue
- packages/components/src/components/trace/TraceNodeBodySql.vue
- packages/components/src/stories/DetailsPanel.stories.js
- packages/components/src/stories/TraceNode.stories.js
- packages/models/src/event.js
> Trace node exceptions

- packages/components/src/pages/quickstart-docs/InstallAgent.vue
- packages/components/src/pages/quickstart-docs/Welcome.vue
> feat: update design for quickstart docs pages

- packages/cli/src/cmds/assert/assertionChecker.ts
- packages/cli/src/cmds/assert/command.ts
- packages/cli/src/cmds/assert/defaultAssertions.ts
- packages/cli/src/cmds/assert/formatter/formatter.ts
- packages/cli/src/cmds/assert/formatter/prettyFormatter.ts
- packages/cli/src/cmds/assert/formatter/progressFormatter.ts
- packages/cli/src/cmds/assert/strategy/strategy.ts
- packages/cli/src/cmds/assert/types.d.ts
Print failure details so that the developer can see the exact problem:
https://asciinema.org/a/xcE59zal7IvDPcuoBrVNgXYsT
> feat: Print failure details after the run

- packages/cli/src/cmds/agentInstaller/agentInstallerProcedure.ts
- packages/cli/src/cmds/agentInstaller/pythonAgentInstaller.ts
- packages/cli/src/cmds/agentInstaller/rubyAgentInstaller.ts
- packages/cli/tests/unit/agentInstall/python.spec.ts
- packages/cli/tests/unit/agentInstall/ruby.spec.ts
This also fixes an issue with the `pip` installer, where `pip install` was never actually run.
> fix: Add Poetry installer

- packages/components/src/components/DetailsSearch.vue
> fix: search regex in panel

- packages/cli/src/cli.ts
- packages/cli/src/cmds/agentInstaller/agentInstaller.ts
- packages/cli/src/cmds/agentInstaller/agentInstallerProcedure.ts
- packages/cli/src/cmds/agentInstaller/commandRunner.ts
- packages/cli/src/cmds/agentInstaller/commandStruct.ts
- packages/cli/src/cmds/agentInstaller/install-agent.ts
- packages/cli/src/cmds/agentInstaller/javaAgentInstaller.ts
- packages/cli/src/cmds/agentInstaller/pythonAgentInstaller.ts
- packages/cli/src/cmds/agentInstaller/rubyAgentInstaller.ts
- packages/cli/src/cmds/agentInstaller/userInteraction.ts
- packages/cli/tests/unit/agentInstall/command.spec.ts
- packages/cli/tests/unit/agentInstall/python.spec.ts
- packages/cli/tests/unit/agentInstall/ruby.spec.ts
**The history needs cleanup here**, so this PR shouldn't be merged till that happens.
> feat: Add validation step after install

- packages/cli/src/cmds/agentInstaller/abortError.js
- packages/cli/src/cmds/agentInstaller/agentInstaller.ts
- packages/cli/src/cmds/agentInstaller/agentInstallerProcedure.ts
- packages/cli/src/cmds/agentInstaller/commandRunner.ts
- packages/cli/src/cmds/agentInstaller/commandStruct.ts
- packages/cli/src/cmds/agentInstaller/commandUtil.ts
- packages/cli/src/cmds/agentInstaller/errors.ts
- packages/cli/src/cmds/agentInstaller/install-agent.ts
- packages/cli/src/cmds/agentInstaller/javaAgentInstaller.ts
- packages/cli/src/cmds/agentInstaller/pythonAgentInstaller.ts
- packages/cli/src/cmds/agentInstaller/rubyAgentInstaller.ts
- packages/cli/src/cmds/agentInstaller/userInteraction.ts
- packages/cli/src/cmds/agentInstaller/validationError.ts
- packages/cli/src/telemetry.ts
- packages/cli/tests/unit/agentInstall/command.spec.ts
- packages/cli/tests/unit/telemetry.spec.ts
Resolves #345
Resolves #350
Resolves #346   
This PR fixes a number of telemetry issues and adds a confirmation step before executing install which describes the installation environment.
> `install-agent` UX improvements

- packages/components/src/components/DiagramComponent.vue
- packages/components/src/pages/VsCodeExtension.vue
- packages/components/tests/e2e/specs/vsCodeExtension.spec.js
- packages/diagrams/src/componentDiagram/graph/index.js
- packages/diagrams/src/componentDiagram/index.js
- packages/models/src/classMap.js
> feat: apply 'Set as root' context menu action globally

- packages/components/src/components/DetailsPanelEvent.vue
- packages/components/tests/e2e/specs/vsCodeExtension.spec.js
> feat: show event exceptions in details panel

- packages/components/src/pages/VsCodeExtension.vue
- packages/components/tests/e2e/specs/vsCodeExtension.spec.js
> feat: filter events in Trace by label

- .travis.yml
- packages/models/package.json
- packages/models/src/util.js
- yarn.lock
Pull the SQL parser from npm, rather than referencing the GitHub repo
directly.
> fix: Use @appland/sql-parser

- packages/components/src/pages/VsCodeExtension.vue
> fix: root objects filter suggestions list objects from entire AppMap

- packages/components/src/components/DiagramTrace.vue
- packages/components/src/components/trace/Trace.vue
- packages/components/src/components/trace/TraceEventBlock.vue
- packages/components/src/components/trace/TraceNode.vue
- packages/components/src/pages/VsCodeExtension.vue
- packages/components/tests/e2e/specs/vsCodeExtension.spec.js
Fixes #489 
Fixes #490 
Fixes #491
> feat: highlight events while looping through filtered events

- packages/components/src/components/FiltersForm.vue
- packages/components/src/pages/VsCodeExtension.vue
> fix: hide filters panel on click

- packages/components/src/pages/VsCodeExtension.vue
- packages/components/tests/unit/VsCodeExtension.spec.js
> feat: get/set global filters state with state API

- packages/components/src/components/FiltersForm.vue
- packages/components/tests/e2e/specs/vsCodeExtension.spec.js
> fix: show filter suggestions when pressing Enter in empty input

- packages/cli/src/cmds/open/openers.ts
- packages/cli/src/cmds/open/showAppMap.ts
- packages/cli/src/cmds/record/configureRemainingRequestOptions.ts
- packages/cli/src/cmds/record/confirmProcessCharacteristics.ts
- packages/cli/src/cmds/record/createRecording.ts
- packages/cli/src/cmds/record/record.ts
See Git commit messages for details.
> fix: Apply fixes to the record command

- packages/components/src/pages/VsCodeExtension.vue
- packages/components/tests/e2e/specs/vsCodeExtension.spec.js
- packages/components/tests/unit/VsCodeExtension.spec.js
Fixes https://github.com/applandinc/appmap-server/issues/1007
> feat: remove default filters when 'setState()' was called with filtered out event

- packages/components/src/components/Tabs.vue
- packages/components/src/components/trace/TraceFilter.vue
- packages/components/src/pages/VsCodeExtension.vue
- packages/components/tests/e2e/specs/vsCodeExtension.spec.js
> feat: auto-complete suggestions list for Trace view filter

- packages/components/src/components/DetailsPanel.vue
- packages/components/src/components/SourceCodeLink.vue
- packages/components/src/stories/data/scenario.json
- packages/components/tests/e2e/specs/vsCodeExtension.spec.js
> feat: "View source" link in details panel

- packages/cli/src/cmds/agentInstaller/install-agent.ts
- packages/cli/tests/unit/agentInstall/installCommand.spec.ts
See: https://linear.app/appland/issue/MAP-318/install-command-accepts-d-argument
> feat: install command accepts -d for target directory

- packages/cli/src/cmds/record/action/saveRecording.ts
https://linear.app/appland/issue/MAP-323/save-remote-recordings-to-dollarappmap-dirremote
> feat: Save recordings to appmap dir remote

- packages/cli/src/cmds/agentInstaller/agentInstallerProcedure.ts
- packages/cli/src/cmds/record/action/printAppMapCount.ts
> feat: Suggest next step

- packages/scanner/package.json
- yarn.lock
This pulls in the fix provided by #623
> fix: Upgrade @appland/models to v1.16.1

- packages/components/src/components/install-guide/ProjectPickerRequirements.vue
- packages/components/src/pages/install-guide/ProjectPicker.vue
- packages/components/src/stories/ProjectPicker.stories.js
Closes https://github.com/applandinc/board/issues/82
Before: 
After:
> add margin to subheadings in install steps

- packages/components/src/components/install-guide/ProjectPickerRequirements.vue
- packages/components/src/components/install-guide/ProjectPickerTable.vue
- packages/components/src/components/quickstart/QuickstartLayout.vue
- packages/components/src/pages/install-guide/ProjectPicker.vue
Add media queries for responsive behavior of project-picker at small screens.
Fixes https://github.com/applandinc/board/issues/92
Before:
After:
> Project picker is responsive

- packages/components/src/components/CodeSnippet.vue
- packages/components/src/components/install-guide/NavigationButtons.vue
- packages/components/src/components/install-guide/ProjectPickerRequirements.vue
- packages/components/src/components/install-guide/ProjectPickerRow.vue
- packages/components/src/pages/install-guide/ProjectPicker.vue
- packages/components/src/stories/ProjectPicker.stories.js
- packages/components/tests/e2e/specs/projectPickerBadProject.spec.js
- packages/components/tests/e2e/specs/projectPickerEmptyProject.spec.js
- packages/components/tests/e2e/specs/projectPickerFourProjects.spec.js
- packages/components/tests/e2e/specs/projectPickerGoodProject.spec.js
Fixes: applandinc/board#90
Added tests for the project picker. Four possible states are tested: empty project, one good project, one bad project, and four projects.
> Test: project picker tests

- packages/cli/bin/build-native
- packages/cli/package.json
- packages/scanner/package.json
- yarn.lock
Fixes applandinc/board#111
Update scripts to generate binaries for CLI and scanner
> feat: scripts to generate binaries for scanner and cli

- packages/client/src/reportJson.ts
- packages/scanner/.gitignore
- packages/scanner/doc/rules/http-500.md
- packages/scanner/src/cli/scan/breakpoint.ts
- packages/scanner/src/cli/scan/command.ts
- packages/scanner/src/cli/scan/interactiveScan.ts
- packages/scanner/src/cli/scan/options.ts
- packages/scanner/src/cli/scan/singleScan.ts
- packages/scanner/src/cli/scan/ui/interactiveProgess.ts
- packages/scanner/src/cli/scan/ui/scanContext.ts
- packages/scanner/src/cli/scan/ui/state.ts
- packages/scanner/src/cli/scan/ui/state/addBreakpoint.ts
- packages/scanner/src/cli/scan/ui/state/eval.ts
- packages/scanner/src/cli/scan/ui/state/hint.ts
- packages/scanner/src/cli/scan/ui/state/hitBreakpoint.ts
- packages/scanner/src/cli/scan/ui/state/initial.ts
- packages/scanner/src/cli/scan/ui/state/scan.ts
- packages/scanner/src/cli/scan/ui/userInteraction.ts
- packages/scanner/src/cli/scan/watchScan.ts
- packages/scanner/src/progressReporter.ts
- packages/scanner/src/ruleChecker.ts
- packages/scanner/src/rules/lib/parseRuleDescription.ts
- packages/scanner/src/rules/lib/util.ts
- packages/scanner/test/cli/scan.spec.ts
Run the scan command with `-i` flag:
[![asciicast](https://asciinema.org/a/xucu7IiuPe1bMdMl2TVpRhSc4.svg)](https://asciinema.org/a/xucu7IiuPe1bMdMl2TVpRhSc4)
A useful way to use this:
* Start a JavaScript debug console for the scanner project
* Run the scanner in interactive mode
* Run the scan once
* Set a scanner breakpoint at a particular code object or event
* When the scanner breaks at that code object or event, set a breakpoint in the scanner JavaScript code
* Continue the scanner
* Debug the scanner rule
> feat: Scan interactive

- packages/models/src/event/hash.js
This case occurred scanning AppLand with the latest rules.
> fix: Handle null value case

- packages/cli/src/cmds/record/testCaseRecording.ts
The previous changes to show the test command output in a support
request kept them from showing up in the console.
asciinema with the new behavior: https://asciinema.org/a/mmdX0qw4WPlvvAYy64jhSz7hG
Fixes applandinc/board#137 .
> fix: Don't swallow output from test commands

- packages/cli/src/cmds/agentInstaller/pythonAgentInstaller.ts
- packages/cli/tests/unit/agentInstall/installCommand.spec.ts
> fix: users with older versions of pip can install

- packages/cli/src/cmds/agentInstaller/agentInstallerProcedure.ts
Fixes getappmap/appmap-ruby#286
When there is an architecture mismatch, then the following is displayed to the user:
> feat: detect architecture mismatch errors in Ruby

- packages/cli/src/cmds/runCommand.ts
- packages/cli/tests/unit/depends.spec.ts
- packages/cli/tests/unit/fingerprint/fingerprintWatchCommand.spec.ts
- packages/cli/tests/unit/stats/stats.spec.ts
- packages/cli/tests/unit/utils.spec.ts
> fix: fix broken tests

- packages/components/package.json
- packages/components/src/pages/VsCodeExtension.vue
- packages/components/src/store/vsCode.js
- packages/components/tests/unit/VsCodeExtension.spec.js
- yarn.lock
- `getState` will now return a Base 64 URL encoded string instead of a stringified JSON object.
- `setState` now supports deserialization of the above strings (in addition to the old style JSON string)
- `getState` will no longer serialize default fields
> feat: State serialization now ignores defaults and is Base64URL encoded

- packages/openapi/src/provider.ts
- packages/scanner/bin/preBuild.js
- packages/scanner/package.json
- packages/scanner/src/rules/lib/parseRuleDescription.ts
- packages/scanner/test/testFilter.js
Fixes getappmap/board#189
This fixes all of the tests except one:
I've been trying to fix this one and it's been resisting my attempts. I'll make a separate issue for it. Any thoughts would be appreciated.
> fix: fix scanner tests in windows

- .travis.yml
> feat: run all tests on windows in ci

- packages/scanner/src/cli/scan/watchScan.ts
> fix: scanner works on windows

- packages/cli/tests/helper.ts
- packages/cli/tests/unit/record/record.spec.ts
- packages/cli/tests/unit/record/record.test.spec.ts
- packages/cli/tests/unit/stats/stats.spec.ts
Fix some tests that weren't stubbing telemetry. Fixes getappmap/board#212.
> test: make sure Telemetry.sendEvent is stubbed

- packages/cli/src/cmds/agentInstaller/agentProcedure.ts
Makes it more readable when looking at logs.
Improves https://github.com/getappmap/board/issues/220
> refactor: use , as fillesDiffText separator

- packages/scanner/src/cli/scan/watchScan.ts
- packages/scanner/test/cli/scan.spec.ts
Fix a bug that would prevent watch scanning from working correctly once a couple files has been skipped (perhaps because they have been already up-to-date).
The problem was that `scan()` function had been modified to take and call a callback, but that change had omitted several early returns; in those cases, the callback would never have been called and the jobs would never finish and let the queue continue.
@ahtrotta , could you verify that this still resolves whatever issue #807 fixed?
> Continue watching correctly after skipping files

- packages/sequence-diagram/src/buildDiagram.ts
- packages/sequence-diagram/src/formatter/plantUML.ts
- packages/sequence-diagram/src/mergeWindow.ts
- packages/sequence-diagram/src/types.ts
- packages/sequence-diagram/tests/fixtures/app/Rakefile
- packages/sequence-diagram/tests/fixtures/app/tmp/appmap/list_users.appmap.json
- packages/sequence-diagram/tests/fixtures/app/tmp/appmap/list_users.sequence.uml
- packages/sequence-diagram/tests/fixtures/app/tmp/appmap/list_users_prefetch.appmap.json
- packages/sequence-diagram/tests/fixtures/app/tmp/appmap/list_users_prefetch.sequence.uml
- packages/sequence-diagram/tests/fixtures/app/tmp/appmap/show_user.appmap.json
- packages/sequence-diagram/tests/fixtures/app/tmp/appmap/show_user.sequence.uml
- packages/sequence-diagram/tests/fixtures/app/tmp/appmap/user_not_found.appmap.json
- packages/sequence-diagram/tests/fixtures/app/tmp/appmap/user_not_found.sequence.uml
- packages/sequence-diagram/tests/fixtures/sequenceDiagrams/listVsListWithPrefetch.sequence.uml
- packages/sequence-diagram/tests/fixtures/sequenceDiagrams/userFoundVsNotFound.sequence.uml
- packages/sequence-diagram/tests/integration/sequenceDiagram.spec.ts
- packages/sequence-diagram/tests/integration/sequenceDiagramDiff.spec.ts
- packages/sequence-diagram/tests/util.ts
(Download and load into your browser to view properly)
> feat: Display timing info on sequence diagram

- packages/cli/src/fingerprint/fingerprintWatchCommand.ts
- packages/cli/tests/unit/fingerprint/fingerprintWatchCommand.spec.ts
Branch created from `sw/indexer_catch_EMFILE`.
Before this change, the indexer crashes if the user created a symbolic link that points to a directory further up, because traversing the directory contents recursively goes in an infinite loop.
The loop stops when this directory is traversed for a 41st time.
```
>>> a = '/home/test/tmp/symlink_points_to_higher_dir/topdir/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subdir1/point_up/subd …
```
> fix: Don't let indexer crash with `Error: ELOOP: too many symbolic links encountered, stat`

- packages/components/src/pages/install-guide/ProjectPicker.vue
> Add terms of service to project picker

- packages/cli/package.json
- packages/cli/src/cmds/openapi.ts
- packages/cli/tests/unit/openapi.spec.ts
https://asciinema.org/a/v69jrmpHLOasAH27JagH1wBeR
> feat: OpenAPI max file size

- packages/cli/src/cli.ts
- packages/cli/src/cmds/upload.ts
- packages/cli/src/lib/appNameFromConfig.ts
- packages/cli/src/lib/appmapDirFromConfig.ts
- packages/cli/src/lib/loadAppMapConfig.ts
- packages/cli/tests/unit/cmds/upload.spec.ts
Adds upload command. Fixes #962 
Still no full feature-parity with the go cli, I'll keep adding to this or as new PRs if this has been merged.
> feat: Upload command

- .releaserc.js
- .travis.yml
- bin/notarize
- bin/presign
- bin/sign
- package.json
- packages/cli/bin/notarize
- packages/cli/package.json
- packages/scanner/package.json
This PR contains a commit labelled as `fix` so the affected binaries will re-release.
> fix: Codesign and notarize MacOS binaries

- packages/cli/src/cmds/agentInstaller/projectConfiguration.ts
- packages/cli/src/cmds/errors.ts
- packages/cli/tests/unit/agentInstall/installCommand.spec.ts
- packages/cli/tests/unit/agentInstall/projectConfiguration.spec.ts
- packages/cli/tests/unit/support/mockCommand.ts
> fix: Don't error out with yarn 1 projects without workspaces

- packages/components/src/components/SignIn.vue
- packages/components/tests/e2e/specs/sidebarSignIn.spec.js
Fixes #1084 
Add tests to check that the sidebar sign-in page renders correctly.
> Add tests for sidebar sign-in page

- packages/components/src/components/DiagramSequence.vue
- packages/components/src/components/sequence/ActionSpec.ts
- packages/components/src/components/sequence/DiagramSpec.ts
- packages/components/src/components/sequence/DownloadSequenceDiagram.vue
- packages/sequence-diagram/src/buildDiagram.ts
- packages/sequence-diagram/src/buildDiffDiagram.ts
- packages/sequence-diagram/src/diff.ts
- packages/sequence-diagram/src/formatter/plantUML.ts
- packages/sequence-diagram/src/selectEvents.ts
Fixes #1098 
Remove node library code from Vue components to avoid complex polyfilling.
> Remove assert and util from vue code

- packages/components/src/pages/VsCodeExtension.vue
- packages/models/src/appMapFilter.js
- packages/models/tests/unit/appMapFilter.spec.js
- packages/models/types/index.d.ts
* Filter out code from outside the source tree
* **Important!** Cache RegExp for filter expressions
* Code name filter can be an explicit RegExp
> feat: Better filters

- packages/components/src/components/SignIn.vue
- packages/components/tests/e2e/specs/sidebarSignIn.spec.js
Visual design and messaging updates for **Messaging test 1**
- [Notion](https://www.notion.so/Messaging-Test-1-7a9ec13dd7084e2d970d980c1e9f08c3?pvs=4)
- Closes getappmap/board/issues/262
> messaging test 1

- packages/cli/src/cmds/agentInstaller/installerUI.ts
> fix: Make sure non-interactive mode doesn't ask questions

- packages/cli/src/html/appmap.js
- packages/components/jest.config.js
- packages/components/package.json
- packages/components/src/components/DiagramFlamegraph.vue
- packages/components/src/lib/flamegraph.js
- packages/components/src/pages/VsCodeExtension.vue
- packages/components/src/store/vsCode.js
- packages/components/src/stories/DiagramFlamegraph.stories.js
- packages/components/src/stories/VsCodeExtension.stories.js
- packages/components/tests/e2e/specs/appmap/componentDiagram.spec.js
- packages/components/tests/e2e/specs/appmap/eventSearch.spec.js
- packages/components/tests/e2e/specs/appmap/traceDiagram.spec.js
- packages/components/tests/e2e/specs/appmap/viewFilter.spec.js
- packages/components/tests/e2e/specs/diagramFlamegraph.spec.js
- packages/components/tests/unit/flamegraph.spec.js
- yarn.lock
This is a prototype and it is hidden behind `flamegraphEnabled` prop which is false by default.
> feat: implement basic flame graph diagram

- packages/components/src/pages/install-guide/InvestigateFindings.vue
Closes https://github.com/getappmap/appmap-js/issues/1198
Old text:
New text:
> Update text on runtime analysis page

- packages/components/tests/unit/FindingsOverview.spec.js
Fixes #1226 
I removed a couple of system tests in `vscode-appland` that were intermittently failing, so I added new tests in `appmap-js` that test the same code.
> Test: findings overview emits correct events

- packages/cli/src/cmds/agentInstaller/javaScriptAgentInstaller.ts
- packages/cli/tests/unit/agentInstall/installCommand.spec.ts
> fix: Make sure AppMap JS agent is up to date before running it

- packages/components/src/pages/InstallGuide.vue
- packages/components/src/pages/install-guide/InvestigateFindings.vue
- packages/components/src/stories/install-guide/InvestigateFindings.stories.js
Cleanup after https://github.com/getappmap/vscode-appland/issues/699
> Remove leftovers of deprecated findingsEnabled flag

- packages/scanner/package.json
- packages/scanner/src/cli/upload.ts
- packages/scanner/src/lastGitOrFSModifiedDate.ts
- packages/scanner/src/ruleChecker.ts
- packages/scanner/src/rules/lib/util.ts
- packages/scanner/src/types.d.ts
- packages/scanner/test/fixtures/ruby/fixture/appmap.yml
- packages/scanner/test/fixtures/ruby/fixture/tmp/appmap/minitest/Circular_cycle.appmap.json
- packages/scanner/test/fixtures/ruby/fixture/tmp/appmap/minitest/Crypt_crypt_aes_128_cbc.appmap.json
- packages/scanner/test/fixtures/ruby/fixture/tmp/appmap/minitest/Crypt_crypt_aes_256_gcm.appmap.json
- packages/scanner/test/git.spec.ts
- packages/scanner/test/scanner/circularDependency.spec.ts
- packages/scanner/test/scanner/deprecatedCryptoAlgorithm.spec.ts
- packages/scanner/test/scanner/illegalPackageDependency.spec.ts
- packages/scanner/test/util.ts
- yarn.lock
Add two fields to the Finding type:
* `scopeModifiedDate?: Date` Latest modified date of any project source file in the finding scope. May be undefined if the scope event does not contain any descendent that comes from a local source file - which is unlikely.
* `eventsModifiedDate?: Date` Latest modified date of the source file of any finding event or ancestor of a finding event. May be undefined if no finding events come from a local source file.
These dates can be used to estimate when a finding was introduced into the code base.
* _Latest modified date_ If the source file has a git status, use the date of the last git commit. Otherwise, use the file mtime.
* _Finding scope_ The `scope` event on the finding. For example, the HTTP server request in which the finding was detected.
* …
> feat: Add modified date fields to Finding

- packages/components/src/components/flamegraph/FlamegraphItem.vue
> External routes are yellow in flame graph

- packages/components/src/components/sequence/LoopAction.vue
- packages/components/src/components/sequence/ReturnLabel.vue
- packages/sequence-diagram/src/buildDiagram.ts
- packages/sequence-diagram/src/types.ts
- packages/sequence-diagram/tests/fixtures/app/tmp/appmap/list_users.sequence.uml
- packages/sequence-diagram/tests/fixtures/app/tmp/appmap/list_users_prefetch.sequence.uml
- packages/sequence-diagram/tests/fixtures/app/tmp/appmap/show_user.sequence.uml
- packages/sequence-diagram/tests/fixtures/app/tmp/appmap/user_not_found.sequence.uml
- packages/sequence-diagram/tests/fixtures/sequenceDiagrams/listVsListWithPrefetch.sequence.uml
- packages/sequence-diagram/tests/fixtures/sequenceDiagrams/userFoundVsNotFound.sequence.uml
- packages/sequence-diagram/tests/unit/sequenceDiagram.spec.ts
Fixes #1052 
To fix strange rendering of loop boxes, this PR adds return arrows to:
* Functions that have no return value
* SQL queries
The return arrows do not have a label.
Before: 
After:
> Loop boxes surround calls

- packages/components/src/components/DetailsPanel.vue
- packages/components/src/components/DetailsPanelEvent.vue
- packages/components/src/pages/VsCodeExtension.vue
- packages/components/src/stories/VsCodeExtension.stories.js
> Remove flame graph feature flag

- packages/components/src/components/install-guide/record-instructions/IntelliJ.vue
- packages/components/src/components/install-guide/record-instructions/Java.vue
- packages/components/src/components/install-guide/record-instructions/Python.vue
- packages/components/src/components/install-guide/record-instructions/Ruby.vue
- packages/components/src/components/install-guide/record-instructions/TestsPrompt.vue
- packages/components/src/pages/install-guide/InvestigateFindings.vue
This fixes two minor issues reported by Vue.
> fix: Errors reported by Vue

- package.json
- packages/components/src/components/install-guide/Status.vue
- packages/components/tests/unit/Status.spec.js
- packages/scanner/appmap.yml
- packages/scanner/package.json
- packages/scanner/src/cli/scan/watchScan.ts
- packages/scanner/test/cli/scan.spec.ts
- packages/scanner/test/git.spec.ts
- yarn.lock
> fix: 'next' button goes to the next step if setup complete

- package.json
- packages/cli/package.json
- packages/cli/src/cmds/open/openers.ts
- packages/cli/src/cmds/open/showAppMap.ts
- packages/cli/tests/unit/cmds/open/showAppMap.spec.ts
- packages/scanner/package.json
- yarn.lock
> Fall back to browser when opening AppMap on Darwin in VSCode

- package.json
- packages/components/package.json
- yarn.lock
Fixes #1295 
Remove `husky` hooks
> Remove husky hooks

- packages/validate/lib/index.js
- packages/validate/test/invalid/missing-function.appmap.json
- packages/validate/test/real.js
This will help prevent regression of: https://github.com/getappmap/appmap-agent-js/issues/219
> Feat check missing function

- packages/cli/tests/unit/compare/ChangeReporter.spec.ts
> Fx broken compare CLI test

- packages/scanner/src/cli/scan/watchScan.ts
If the scan function exited here https://github.com/getappmap/appmap-js/pull/1334/files#diff-dabfb7d0345830c8fbb1494614af8c5b594367024d8b589453e08d6b2fd0eb60L176 or here https://github.com/getappmap/appmap-js/pull/1334/files#diff-dabfb7d0345830c8fbb1494614af8c5b594367024d8b589453e08d6b2fd0eb60L192
Then https://github.com/getappmap/appmap-js/pull/1334/files#diff-dabfb7d0345830c8fbb1494614af8c5b594367024d8b589453e08d6b2fd0eb60L204 would never be called
And so the AppMap, when modified, would not be enqueued - https://github.com/getappmap/appmap-js/blob/e051d8db4e7d7b6b8ad8420573f0f02939d9e3bc/packages/scanner/src/cli/scan/watchScan.ts#L162C25-L162C25
> fix: Ensure that AppMaps are un-marked as being scanned

- packages/cli/src/cmds/archive/buildFilter.ts
- packages/cli/src/lib/loadAppMapConfig.ts
- packages/cli/tests/unit/archive/buildFilter.spec.ts
Suppress diagram diffs like this:
> feat: Hide SQL SHOW from compare

- packages/components/src/components/sequence/ReturnLabel.vue
- packages/components/src/stories/VsCodeExtension.stories.js
- packages/components/src/stories/data/long-package.appmap.json
- packages/components/tests/e2e/specs/appmap/longPackageSequenceDiagram.spec.js
> fix: Long package names are clipped

- packages/cli/src/cmds/stats/stats.ts
- packages/cli/tests/unit/stats/stats.spec.ts
Fixes #1200 
refactor(cli/src/cmds/stats/stats.ts): simplify appmap file resolution logic
test(cli/tests/unit/stats/stats.spec.ts): adjust and add tests for appmap file resolution
> Stats command relative path support

- packages/components/src/components/sequence/ActionSpec.ts
- packages/components/src/components/sequence/CallAction.vue
- packages/components/tests/e2e/specs/appmap/boxTooHighSequenceDiagram.spec.js
> fix: Box too high on the lifeline

- packages/components/src/components/sequence/CallLabel.vue
- packages/components/src/stories/VsCodeExtension.stories.js
- packages/components/src/stories/data/long_call_labels_are_cut_off.appmap.json
- packages/components/tests/e2e/specs/appmap/longCallLabelsSequenceDiagram.spec.js
> fix: Long call labels are cut off

- packages/components/src/components/FilterMenu.vue
- packages/components/src/components/PopperMenu.vue
- packages/components/src/components/Tabs.vue
- packages/components/src/pages/VsCodeExtension.vue
- packages/components/src/stories/VsCodeExtension.stories.js
- packages/components/tests/e2e/specs/appmap/smallDevice.spec.js
> feat: Add responsive styling for mobile

- packages/cli/src/cmds/agentInstaller/gradleInstaller.ts
- packages/cli/src/cmds/agentInstaller/mavenInstaller.ts
- packages/cli/tests/unit/agentInstall/__snapshots__/gradleInstaller.spec.ts.snap
- packages/cli/tests/unit/fixtures/java/gradle/data/buildscript-plugins.gradle
- packages/cli/tests/unit/fixtures/java/gradle/data/buildscript-plugins.gradle.kts
- packages/cli/tests/unit/fixtures/java/gradle/data/extra-repo-block.gradle
- packages/cli/tests/unit/fixtures/java/gradle/data/extra-repo-block.gradle.kts
- packages/cli/tests/unit/fixtures/java/gradle/data/no-maven.gradle
- packages/cli/tests/unit/fixtures/java/gradle/data/no-maven.gradle.kts
- packages/cli/tests/unit/fixtures/java/maven/data/existing-no-version.expected.xml
- packages/cli/tests/unit/fixtures/java/maven/data/existing.expected.xml
- packages/cli/tests/unit/fixtures/java/maven/data/no-build.expected.xml
- packages/cli/tests/unit/fixtures/java/maven/data/no-plugins.expected.xml
- packages/cli/tests/unit/fixtures/java/maven/data/plugins.expected.xml
Upgrading each one to the latest (trying to specify a range was not fruitful).
> Change gradle and maven installers to use the latest versions of those plugins

- packages/components/src/components/DiagramSequence.vue
- packages/components/src/pages/VsCodeExtension.vue
- packages/components/tests/e2e/specs/appmap/sequenceDiagram.spec.js
Fixes: #1447 
feat(DetailsPanelEvent.vue): add SET_FOCUSED_EVENT in viewEventInSequence
feat(DiagramSequence.vue): emit 'updateCollapseDepth' on collapse change
feat(VsCodeExtension.vue): add handler for new collapse depth
test(sequenceDiagram.spec.js): test action expansion in sequence view
> Show in sequence when collapse level is low

- packages/cli/resources/inventory-report/summary/summary.hbs
- packages/cli/resources/inventory-report/welcome/welcome.hbs
- packages/cli/src/cmds/inventory-report/Reporter.ts
- packages/cli/src/cmds/inventory-report/SummaryReport.ts
- packages/cli/src/cmds/inventory-report/SummaryReporter.ts
- packages/cli/src/cmds/inventory-report/WelcomeReport.ts
- packages/cli/src/cmds/inventory-report/WelcomeReporter.ts
- packages/cli/src/cmds/inventory/Report.ts
- packages/cli/src/cmds/inventory/analyzers/collectAppMapSize.ts
- packages/cli/src/cmds/inventory/analyzers/collectFindings.ts
- packages/cli/src/cmds/inventory/analyzers/collectFunctionOccurances.ts
- packages/cli/src/cmds/inventory/analyzers/collectMetadata.ts
- packages/cli/src/cmds/inventory/buildReport.ts
- packages/cli/src/cmds/inventory/inventory.ts
- packages/cli/src/cmds/stats/accumulateEvents.ts
- packages/cli/src/cmds/stats/stats.ts
- packages/cli/src/cmds/stats/statsForDirectory.ts
- packages/cli/src/cmds/stats/statsForMap.ts
- packages/cli/src/lib/emitUsage.ts
- packages/cli/tests/unit/inventory/inventory.spec.ts
- packages/cli/tests/unit/inventoryReport/inventory.json
- packages/cli/tests/unit/inventoryReport/summary.md.txt
- packages/cli/tests/unit/inventoryReport/welcome.md.txt
- packages/cli/tests/unit/lib/emitUsage.spec.ts
- packages/cli/tests/unit/stats/stats.spec.ts
- packages/client/src/usage.ts
* _changed_ `metadata` is an object, rather than a serialized String
* _added_ `appmapConfig` is reported as an Object.
Configuration  report is expanded to provide:
* largeAppMaps
* frequentFunctions
To help the user streamline and prune their config.
**Example**
https://gist.github.com/kgilpin/1bd0783c330743ae2440522ce0f00e97
```json
"largeAppMaps": {
"tmp/appmap/minitest/Password_resets_password_resets.appmap.json": 2150673,
"tmp/appmap/minitest/Microposts_interface_micropost_interface.appmap.json": 2039187,
"tmp/appmap/minitest/Users_login_login_with_valid_information_followed_by_logout.appmap.json": 982768
}
```
```json
"frequentFunctions": {
"function:ruby/Array#pack": {
"function": "function:ruby/Array#pack",
"count": 3410,
"size": 1428513,
"location": "<internal:pack>:133"
}, …
```
> feat: Expand inventory and run stats

- packages/client/src/app.ts
- packages/client/src/appMap.ts
- packages/client/src/get.ts
- packages/client/src/index.ts
- packages/client/src/licenseKey.ts
- packages/client/src/mapset.ts
Client API method to check a license key.
```javascript
const client = require('./dist/src/index');
const licenseKey = process.argv[2];
(async () => {
const status = await client.LicenseKey.check(licenseKey);
console.log(status);
})();
```
```
$ APPMAP_URL=http://127.0.0.1:3000 node ./testClient.js ZGF2aWRAdGVzdC5jb206ODBlMzUzMGQtMDYzNi00MjQ4LWEyZTYtMjk2OGY0MzZiMWRk
true
$ APPMAP_URL=http://127.0.0.1:3000 node ./testClient.js Zm9vCg==
false
```
https://github.com/getappmap/appmap-server/pull/1391 (must be merged first, of course)
> feat: Check license key

- packages/components/src/pages/VsCodeExtension.vue
> Reset collapse depth on diagram refresh

- packages/scanner/doc/rules/unfulfilled-promise.md
- packages/scanner/src/rules/unfulfilledPromise.ts
- packages/scanner/test/fixtures/appmaps/unfulfilled-promise.appmap.json
- packages/scanner/test/scanner/unfulfilledPromise.spec.ts
> feat: Scanner rule for unfulfilled promises

- packages/cli/package.json
- packages/client/package.json
- packages/components/package.json
- packages/diagrams/package.json
- packages/openapi/package.json
- packages/scanner/package.json
- packages/sequence-diagram/package.json
- yarn.lock
Sync/update other versions too
> feat: Update @appland/client in @appland/appmap

- packages/components/src/components/chat/Chat.vue
- packages/components/src/components/quickstart/QuickstartLayout.vue
This PR fixes two issues.
First, the 'New chat' button would appear slightly underneath the AppMap view
Secondly, there was some overflow occurring in the project picker.
> Style fixes for VS Code

- packages/components/src/components/chat/Chat.vue
- packages/components/src/components/chat/SuggestionGrid.vue
- packages/components/src/pages/Chat.vue
- packages/components/src/stories/Chat.stories.js
- packages/components/tests/unit/chat/SuggestionGrid.spec.js
This change allows instances of the Chat page to specify their own prompt recommendations.
> Parameterize prompts

- packages/components/src/components/DetailsPanelHeader.vue
> Remove extra chevron in parents section of details panel

- packages/cli/src/fulltext/FindEvents.ts
- packages/cli/src/rpc/explain/context.ts
- packages/cli/src/rpc/explain/explain.ts
- packages/cli/src/rpc/explain/lookupSourceCode.ts
- packages/cli/tests/integration/fixtures/search/api_key.search.json
- packages/components/src/components/DiagramComponent.vue
- packages/components/src/components/sequence/CallLabel.vue
- packages/components/src/lib/AppMapRPC.ts
- packages/components/src/pages/ChatSearch.vue
- packages/components/src/pages/VsCodeExtension.vue
- packages/components/src/store/vsCode.js
- packages/components/src/stories/VsCodeExtension.stories.js
- packages/components/tests/unit/chat/AppMapRPC.spec.js
- packages/components/tests/unit/chat/ChatSearch.spec.js
- yarn.lock
Some fixes for Chat Search. Each commit should be pretty self-explanatory.
Fixes https://github.com/getappmap/appmap-js/issues/1525
> fix: ChatSearch fixes

- .github/workflows/main.yml
Add AppMap Analysis for the CLI package.
> ci: Run appmap-analysis on packages/cli

- packages/components/src/components/chat/Chat.vue
- packages/components/src/pages/ChatSearch.vue
- packages/components/tests/e2e/specs/chat/chatSearch.spec.js
> New chat clears appmaps

- packages/components/build/vue.d.ts
- packages/components/src/components/chat/Chat.vue
- packages/components/src/components/chat/Loader.vue
- packages/components/src/components/chat/ToolStatus.vue
- packages/components/src/components/chat/UserMessage.vue
- packages/components/src/pages/Chat.vue
- packages/components/src/pages/ChatSearch.vue
- packages/components/src/stories/ChatSearch.stories.js
- packages/components/src/stories/ChatTools.stories.js
- packages/components/tests/e2e/specs/chat/chatSearch.spec.js
- packages/components/tests/unit/chat/ChatComponent.spec.js
- packages/components/tests/unit/chat/ChatSearch.spec.js
- packages/components/tsconfig.json
This change adds an inline status for AppMap searches.
It also replaces the previous spinning loading indicator with a 'text cursor'.
[Peek 2024-01-19 16-45.webm](https://github.com/getappmap/appmap-js/assets/8737782/18570242-0770-4cd5-98f0-6ed970d295dc)
Resolves [#1558](https://github.com/getappmap/appmap-js/issues/1558)
> Render the presence and progress of search in the chat window 

- .github/workflows/main.yml
- packages/components/src/components/sequence/CallLabel.vue
- packages/components/src/components/sequence/ReturnLabel.vue
- packages/components/tests/e2e/specs/appmap/collapsibleSidebar.spec.js
- packages/components/tests/e2e/specs/appmap/sequenceDiagram.spec.js
- packages/components/tests/e2e/specs/appmap/sequenceDiagramDiff.spec.js
> Fix the clipping of long hover labels in sequence diagram

- packages/components/src/pages/VsCodeExtension.vue
This won't ever resolve and results in console errors.
> fix: Don't attempt to load a font from URL

- .github/workflows/main.yml
- packages/components/src/components/chat/Chat.vue
- packages/components/src/components/chat/UserMessage.vue
- packages/components/src/pages/ChatSearch.vue
- packages/components/tests/unit/chat/ChatSearch.spec.js
This PR changes the explain chat to:
- Only render a search status after the first prompt ([referenced here](https://github.com/getappmap/appmap-js/pull/1547#issuecomment-1907207107))
- Fix resizing via click+drag and initial size of the chat ([view the issue here](https://5fe18baf66f2280021e634d0-axkxxfcjlj.chromatic.com/iframe.html?args=&id=pages-chatsearch--chat-search-mock-search-prepopulated&viewMode=story))
These changes are already included in the VSCode release candidate.
> Search feedback tweaks

- packages/components/src/components/chat/Chat.vue
- packages/components/src/components/chat/ChatInput.vue
- packages/components/src/pages/ChatSearch.vue
- packages/components/tests/unit/chat/ChatComponent.spec.js
Ensure that `codeSelections` are sent to the backend.
> fix: Propagate codeSelections

- packages/components/src/components/chat/UserMessage.vue
> Nicer chat cursor

- packages/components/src/components/chat-search/Instructions.vue
- packages/components/src/components/chat-search/MatchInstructions.vue
- packages/components/src/components/chat/Chat.vue
- packages/components/src/components/chat/SuggestionCard.vue
- packages/components/src/components/chat/SuggestionGrid.vue
- packages/components/src/components/chat/ToolStatus.vue
- packages/components/src/components/chat/UserMessage.vue
- packages/components/src/pages/Chat.vue
- packages/components/src/pages/ChatSearch.vue
- packages/components/src/pages/VsCodeExtension.vue
- packages/components/tests/unit/chat/ChatSearch.spec.js
Style updates for the Navie chat interface.
[Try it here](https://5fe18baf66f2280021e634d0-imwppwivnz.chromatic.com/iframe.html?args=&id=pages-chatsearch--chat-search-mock&viewMode=story)
> Navie chat interface style updates

- packages/cli/LICENSE.txt
- packages/client/src/aiClient.ts
- packages/components/LICENSE.txt
- packages/diagrams/LICENSE.txt
- packages/openapi/LICENSE.txt
- packages/rpc/LICENSE.txt
- packages/scanner/LICENSE.txt
- packages/sequence-diagram/LICENSE.txt
aiClient will `warn` when an unexpected Socket message is received, rather than disconnecting. This enables the client to be compatible with new server messages.
Also update the Copyright year.
> fix: Warn not disconnect

- packages/components/src/components/SignIn.vue
Ensure that leading and trailing whitespace is removed from strings during email verification flow.
> Better whitespace handling in sign-in forms

- docs/reference/appmap-java.md
feat: Sync docs from applandinc.appmap.io
> feat: Sync docs from applandinc.appmap.io

- packages/cli/src/rpc/explain/navie/navie-local.ts
- packages/cli/tests/integration/rpc.explain.spec.ts
Fixes #1712
On first explain request, emits an event like
```yaml
name: "@appland/appmap/navie-local"
properties:
modelName: some-model
azureVersion?: version
```
This allows tracking bring your own key/model. If one is just using bring you own key, the model will be the default (currently `gpt-4-0125-preview`). If Azure OpenAI is used, azureVersion field will be present.
> feat: Emit navie-local telemetry events

- packages/components/src/components/chat-search/Context.vue
- packages/components/src/components/chat-search/ContextItem.vue
- packages/components/src/pages/ChatSearch.vue
- packages/components/src/stories/ChatSearch.stories.js
- packages/components/src/stories/data/navie_context.json
- packages/components/tests/e2e/specs/chat/chatSearch.spec.js
- packages/components/tests/unit/chat/ChatSearch.spec.js
Fixes #1731 
It looks like the `appmap.data` RPC method is no longer used? We might want to check that at some point. It was safely removed from the test data.
> Show Navie Context with code highlighting

- packages/components/src/components/chat-search/Context.vue
- packages/components/src/components/chat-search/ContextItem.vue
- packages/components/src/pages/ChatSearch.vue
Fixes #1737 
I didn't add tests because this is an edge case that will become essentially obsolete in the near future once everyone is upgraded to the most recent UI and CLI.
> New Navie UI works with the old RPC

- .github/workflows/build-native.yml
- bin/hash.js
- Resolves https://github.com/getappmap/appmap-js/issues/1740
- Resolves https://github.com/getappmap/appmap-js/issues/1735
> Windows fixes

- packages/components/src/pages/ChatSearch.vue
- packages/components/tests/unit/chat/ChatSearch.spec.js
> Update Navie tool status message

- package.json
- packages/cli/src/cmds/index/aiEnvVar.ts
- packages/cli/src/cmds/index/rpc.ts
- packages/cli/src/fulltext/listProjectFiles.ts
- packages/cli/src/rpc/appmap/data.ts
- packages/client/src/ai.ts
- packages/client/src/index.ts
- packages/client/test/ai.spec.ts
- yarn.lock
Client API functions to populate the fields defined in https://github.com/getappmap/appmap-server/pull/1456/files
* **createUserMessage** Allocates a user message record and populates initial metadata such as the question length.
* **createAgentMessage** Allocates an agent message record.
* **updateUserMessage** Updates the user message record with Navie-computed information such as the agent name and classification.
* **updateAgentMessage** Updates the agent record with response information such as the response length and elapsed time.
Once this PR is merged, the server-side implementation of these routes will be introduced, using the types defined in this PR.
> feat: Client APIs for reporting AI conversation parameters

- packages/components/src/pages/ChatSearch.vue
- packages/components/tests/unit/chat/ChatSearch.spec.js
This fixes an issue where the context side panel was not updating after receiving a subsequent context response.
> fix: Update context UI

- packages/cli/package.json
Reduce the amount of useless and wrong details produced by Navie by providing her with only the high level docs.
> feat: Sync only high level docs

- packages/cli/src/cmds/navie.ts
- packages/cli/src/rpc/explain/navie/navie-local.ts
- packages/navie/src/lib/completion.ts
- packages/navie/src/lib/oracle.ts
- packages/navie/src/services/classification-service.ts
- packages/navie/src/services/completion-service.ts
- packages/navie/src/services/file-patch-service.ts
- packages/navie/src/services/tech-stack-service.ts
- packages/navie/src/services/vector-terms-service.ts
- packages/navie/test/fixture.ts
- yarn.lock
No effort is currently done to summarize it; it's just output in the logs:
```console
$ PYTHONPATH=. python ./appmap/solve.py --path_conda $(conda info --base) --split dev --num_workers 1 --appmap_command ~/projects/appmap-js/packages/cli/built/cli.js --filter marshmallow
$ grep cost logs/solve/marshmallow-code__marshmallow-*/*/*.log
logs/solve/marshmallow-code__marshmallow-1343/1/apply.log:Tokens (prompt/compl/total): 535/30/565, cost: $0.00
logs/solve/marshmallow-code__marshmallow-1343/1/generate.log:Tokens (prompt/compl/total): 13091/31/13122, cost: $0.07
logs/solve/marshmallow-code__marshmallow-1343/1/generate.log:Tokens (prompt/compl/total): 12502/401/12903, cost: $0.06
logs/solve/marshmallow-code__marshmallow-1343/1/list-files.log:Tokens (prompt/compl/total): 786/30/816, cost: $0.00 …
```
> Show cost estimates when calling the LLM

- .github/workflows/build-native-scanner.yml
- .github/workflows/build-native.yml
- packages/cli/package.json
- yarn.lock
I updated the pkg package due to this error https://github.com/vercel/pkg/issues/1870
> Build a linux-arm64 binary

- packages/components/src/assets/stop-icon.svg
- packages/components/src/components/chat/Chat.vue
- packages/components/src/components/chat/ChatInput.vue
- packages/components/src/lib/AppMapRPC.ts
- packages/components/src/pages/ChatSearch.vue
- packages/components/tests/e2e/specs/chat/chatSearch.spec.js
- packages/components/tests/unit/chat/ChatComponent.spec.js
- packages/components/tests/unit/chat/ChatSearch.spec.js
Adds functionality to stop the assistant's responses mid-answer.
> feat: Stop Navie answer

- packages/cli/src/cmds/navie/help.ts
- packages/cli/src/fulltext/AppMapIndex.ts
- packages/cli/src/fulltext/FileIndex.ts
- packages/cli/src/fulltext/FindEvents.ts
- packages/cli/src/fulltext/fileNameMatchesFilterPatterns.ts
- packages/cli/src/rpc/explain/collectContext.ts
- packages/cli/src/rpc/explain/explain.ts
- packages/cli/tests/unit/fulltext/AppMapIndex.spec.ts
- packages/cli/tests/unit/fulltext/FileIndex.spec.ts
- packages/navie/src/agent.ts
- packages/navie/src/agents/explain-agent.ts
- packages/navie/src/agents/generate-agent.ts
- packages/navie/src/agents/plan-agent.ts
- packages/navie/src/agents/test-agent.ts
- packages/navie/src/commands/context-command.ts
- packages/navie/src/context.ts
- packages/navie/src/lib/parse-options.ts
- packages/navie/src/services/agent-selection-service.ts
- packages/navie/src/services/apply-context-service.ts
- packages/navie/src/services/context-service.ts
- packages/navie/src/services/lookup-context-service.ts
- packages/navie/test/agent-options.spec.ts
- packages/navie/test/agents/explain-agent.spec.ts
- packages/navie/test/agents/generate-agent.spec.ts
- packages/navie/test/services/context-service.spec.ts
Add context filters:
* `/include=pattern` Include files by regexp pattern
* `/exclude=pattern` As above
* `/itemtype=code-snippet,sequence-diagram,data-request` Include/exclude content by content type
> feat: Context control

- packages/components/src/assets/request-arrows-icon.svg
- packages/components/src/components/Badge.vue
- packages/components/src/components/PopperMenu.vue
- packages/components/src/components/install-guide/record-instructions/JavaScript.vue
- packages/components/src/components/install-guide/record-instructions/RecordingMethod.vue
- packages/components/src/components/install-guide/record-instructions/RecordingMethodGrid.vue
- packages/components/src/components/quickstart/QuickstartLayout.vue
- packages/components/src/lib/buildPrompts.ts
- packages/components/src/pages/install-guide/RecordAppMaps.vue
- packages/components/src/scss/_variables.scss
- packages/components/tests/e2e/specs/appmap/export.spec.js
- packages/components/tests/unit/VsCodeExtension.spec.js
This change introduces the Navie concept to the 'record AppMaps' step of installation. Users can easily ask Navie questions about how to get started with recording with the click of a button. Some cosmetic changes accompany this to make room for the 'ask Navie' buttons associated with each recording type. A fair amount of text was dropped to improve readability.
Work in progress.
https://github.com/getappmap/appmap-js/assets/8737782/c67d90aa-d384-4f3b-83d8-8302f311e793
> feat: Add Navie help to recording record-instructions

- packages/components/src/components/chat-search/LlmConfiguration.vue
- packages/components/src/pages/ChatSearch.vue
- packages/components/src/stories/ChatSearch.stories.js
Cosmetic changes for UI for VSCode LM API support.
- Show the LLM vendor in the model callout.
- Make sure blinking cursor is shown before the first token is received.
(Followup to https://github.com/getappmap/vscode-appland/pull/983 )
> Cosmetic changes for VSCode LM API support

- packages/cli/src/rpc/explain/explain.ts
- packages/navie/package.json
- packages/navie/src/agent.ts
- packages/navie/src/agents/diagram-agent.ts
- packages/navie/src/agents/explain-agent.ts
- packages/navie/src/agents/generate-agent.ts
- packages/navie/src/agents/help-agent.ts
- packages/navie/src/agents/plan-agent.ts
- packages/navie/src/agents/test-agent.ts
- packages/navie/src/commands/explain-command.ts
- packages/navie/src/context.ts
- packages/navie/src/lib/filter.ts
- packages/navie/src/lib/mermaid-filter.ts
- packages/navie/src/lib/mermaid-fixer.ts
- packages/navie/src/lib/mermaid-validator.ts
- packages/navie/src/navie.ts
- packages/navie/src/prompt.ts
- packages/navie/src/services/agent-selection-service.ts
- packages/navie/src/services/classification-service.ts
- packages/navie/src/services/completion-service.ts
- packages/navie/src/services/mermaid-fixer-service.ts
- packages/navie/test/agents/diagram-agent.spec.ts
- packages/navie/test/agents/explain-agent.spec.ts
- packages/navie/test/commands/explain-command.spec.ts
- packages/navie/test/lib/mermaid-fixer.spec.ts
- packages/navie/test/lib/mermaid-validator.spec.ts
- packages/navie/test/services/agent-selection-service.spec.ts
- packages/navie/test/services/classification-service.spec.ts
- packages/navie/test/services/mermaid-filter.spec.ts
- yarn.lock
Adds `@diagram` agent mode, with built-in prompts for entity-relationship, flowchart, and class map diagrams.
1. [ ] **Diagram Generation Mode**: Introduced a new `AgentMode` called `Diagram` for generating software diagrams (flowcharts, ER diagrams, UML class diagrams).
2. [ ] **DiagramAgent**: Created a new `DiagramAgent` class for handling diagram generation requests.
3. [ ] **Agent Selection for Diagrams**: Updated `AgentSelectionService` to handle `@diagram` mode requests.
4. [ ] **Mermaid Library Integration**: Added `mermaid` library dependency for diagram rendering.
5. [ ] **MermaidValidator**: Added `MermaidValidator` to validate Mermaid diagram syntax.
6. [ ] **MermaidFilter**: Implemented `MermaidFilter` to parse and validate Mermaid diagram syntax. Tokens are withheld from the …
> feat: Diagram agent

- packages/cli/src/rpc/explain/EventCollector.ts
- packages/cli/src/rpc/explain/LocationContextCollector.ts
- packages/cli/src/rpc/explain/SearchContextCollector.ts
- packages/cli/src/rpc/explain/SourceCollector.ts
- packages/cli/src/rpc/explain/collectContext.ts
- packages/cli/src/rpc/explain/explain.ts
- packages/cli/src/rpc/explain/location.ts
- packages/cli/tests/unit/rpc/explain/ContextCollector.spec.ts
- packages/cli/tests/unit/rpc/explain/EventCollector.spec.ts
- packages/cli/tests/unit/rpc/explain/LocationContextCollector.spec.ts
- packages/cli/tests/unit/rpc/explain/SearchContextCollector.spec.ts
- packages/cli/tests/unit/rpc/explain/location.spec.ts
- packages/navie/src/agent.ts
- packages/navie/src/agents/diagram-agent.ts
- packages/navie/src/agents/explain-agent.ts
- packages/navie/src/agents/generate-agent.ts
- packages/navie/src/agents/plan-agent.ts
- packages/navie/src/agents/test-agent.ts
- packages/navie/src/commands/explain-command.ts
- packages/navie/src/navie.ts
- packages/navie/src/services/agent-selection-service.ts
- packages/navie/src/services/context-service.ts
- packages/navie/src/services/file-content-fetcher.ts
- packages/navie/src/services/lookup-context-service.ts
- packages/navie/test/agents/diagram-agent.spec.ts
- packages/navie/test/agents/explain-agent.spec.ts
- packages/navie/test/agents/generate-agent.spec.ts
- packages/navie/test/commands/explain-command.spec.ts
- packages/navie/test/services/agent-selection-service.spec.ts
- packages/navie/test/services/context-service.spec.ts
@generate and @test are updated to fetch the full text of mentioned files.
Adds location-based context to the search context
```mermaid
sequenceDiagram
participant GenerateAgent as GenerateAgent
participant ContextService as ContextService
participant LookupContextService as LookupContextService
GenerateAgent->>ContextService: searchContext(options, tokensAvailable)
activate ContextService
ContextService->>LookupContextService: lookupContext(vectorTerms, tokenCount, options)
activate LookupContextService
LookupContextService-->>ContextService: Context[]
deactivate LookupContextService
ContextService-->>GenerateAgent: void
deactivate ContextService
GenerateAgent->>ContextService: locationContext(fileNames)
activate ContextService
ContextService->>LookupContextService: lookupContext([], 0, …
```
> feat: Fetch full text of files to @generate

- packages/cli/src/cmds/index/rpc.ts
- packages/cli/src/rpc/navie/metadata.ts
- packages/components/src/components/Popper.vue
- packages/components/src/components/chat/AutoComplete.vue
- packages/components/src/components/chat/Chat.vue
- packages/components/src/components/chat/ChatInput.vue
- packages/components/src/components/chat/WelcomeMessage.vue
- packages/components/src/lib/AppMapRPC.ts
- packages/components/src/pages/ChatSearch.vue
- packages/components/src/stories/ChatSearch.stories.js
- packages/components/tests/unit/chat/AutoComplete.spec.js
- packages/components/tests/unit/chat/ChatInput.spec.js
- packages/components/tests/unit/chat/ChatSearch.spec.js
- packages/components/tests/unit/support/polyfills.js
- packages/rpc/src/index.ts
- packages/rpc/src/navie.ts
https://github.com/user-attachments/assets/d5806790-ec55-490c-9c7f-6b392f91cdbe
Sample:
https://5fe18baf66f2280021e634d0-whvhlpbixz.chromatic.com/?path=/story/pages-chatsearch--chat-search-mock
> feat: Auto-completions and welcome message

- packages/cli/src/rpc/explain/navie/historyHelper.ts
- packages/cli/tests/unit/rpc/explain/historyHelper.spec.ts
> fix: Create history dir if it does not exist

- packages/components/src/components/Popper.vue
- packages/components/src/components/chat/ContextContainer.vue
This PR adds hover tooltips to code snippet / context items
https://github.com/user-attachments/assets/0acdd5d1-1f18-43b0-99dd-e26c8c522b1e
> feat: Add tooltips to code snippet buttons

- packages/components/src/components/Popper.vue
- packages/components/src/components/chat/AutoComplete.vue
- packages/components/tests/unit/chat/AutoComplete.spec.js
Resolves https://github.com/getappmap/appmap-js/issues/1991
> fix: Prevent an issue where autocompletion becomes stuck

- packages/navie/src/services/openai-completion-service.ts
- packages/navie/test/services/openai-completion-service.spec.ts
This commit introduces a retry mechanism for handling server errors during the streaming of OpenAI API responses. Let's break down the changes and their implications:
The main change is in the `complete` method of the `OpenAICompletionService` class. A new retry loop has been added to handle potential server errors during streaming.
```typescript
for (let attempt = 0; attempt < 5; attempt++) {
const response = await fetchResponse();
try {
for await (const token of response) {
// ... process tokens ...
}
break; // Exit loop if successful
} catch (error) {
if (!(error instanceof APIError) || error.type !== 'server_error') throw error;
if (tokensYielded || attempt === 4) throw error;
await new Promise((resolve) => setTimeout(resolve, 1000 * Math.pow(2, attempt)));
}
}
```
This code attempts …
> fix: Retry completion if OpenAI throws a server error while streaming

- packages/components/src/components/chat/ContextContainer.vue
- packages/components/src/components/chat/NextPromptButton.vue
- packages/components/src/components/chat/UserMessage.vue
- packages/components/tests/unit/chat/NextPromptButton.spec.js
- packages/navie/src/services/next-step-classification-service.ts
This pull request addresses several UI and functionality issues to improve user experience and maintain consistency across the application. The changes include updates to styling, tooltips, prompt handling, and event triggers in the chat components.
- **Prevent Icons Clipping**: Fixed an issue where some icons were clipped on the right side.
- **Truncated Context Item Names**: Resolved the problem where context item names were truncated on the right, obscuring the file name.
- **Pending Apply Indicator**: Corrected the placement of the pending apply indicator.
- **Clickable Code Snippet Headers**: Added a visual indicator for clickable code snippet headers.
- **Tooltips Limitation**: Limited tooltips to only code snippet headers, where they were previously displayed over the content of …
> fix: Navie clean up

- packages/components/src/pages/ChatSearch.vue
- packages/navie/src/agents/test-agent.ts
- yarn.lock
Fixes #1983
I tried more complicated ways but it turns out if you just concatenate format instructions it works out fine.
> feat: Generate diff output with @test command

- packages/cli/src/fulltext/FileIndex.ts
- packages/cli/tests/unit/fulltext/FileIndex.spec.ts
I think I let Copilot write that.
> fix: mjs file is not binary data

- packages/navie/src/lib/get-most-recent-messages.ts
Resolves https://github.com/getappmap/appmap-js/issues/2054
> fix: Use 4 historical chat messages

- .github/actions/setup-node/action.yml
- packages/cli/src/rpc/explain/explain.ts
- packages/cli/src/rpc/explain/navie/history.ts
- packages/cli/src/rpc/explain/navie/ihistory.ts
- packages/cli/src/rpc/explain/navie/inavie.ts
- packages/components/src/components/chat/MarkdownCodeSnippet.vue
- packages/components/src/components/chat/PinEvent.ts
- packages/components/src/lib/AppMapRPC.ts
- packages/components/src/pages/ChatSearch.vue
- packages/navie/src/agent.ts
- packages/navie/src/commands/explain-command.ts
- packages/navie/src/commands/update-command.ts
- packages/navie/src/context.ts
- packages/navie/src/index.ts
- packages/navie/src/navie.ts
- packages/navie/src/services/code-selection-service.ts
- packages/navie/src/services/context-service.ts
- packages/navie/src/services/file-change-extractor-service.ts
- packages/navie/src/user-context.ts
- packages/rpc/src/explain.ts
Add the locations of pinned files to Navie requests, rather than their contents.
Fixes #2049 .
> fix: add locations to explain requests

- packages/cli/src/rpc/file/applyFileUpdate.ts
- packages/cli/tests/unit/rpc/file/applyFileUpdate.spec.ts
- packages/cli/tests/unit/rpc/file/applyFileUpdate/missing-firstline-indent/apply.yml
- packages/cli/tests/unit/rpc/file/applyFileUpdate/missing-firstline-indent/expected.txt
- packages/cli/tests/unit/rpc/file/applyFileUpdate/missing-firstline-indent/original.txt
- packages/cli/tests/unit/rpc/file/applyFileUpdate/trailing-newlines/expected.txt
> fix: Adjust whitespace of the first line of patch separately

- packages/cli/src/rpc/explain/explain.ts
- packages/cli/src/rpc/explain/review.ts
- packages/cli/tests/unit/rpc/explain/review.spec.ts
- packages/navie/src/command.ts
- packages/navie/src/commands/review-command.ts
- packages/navie/src/index.ts
- packages/navie/src/navie.ts
- packages/navie/src/user-context.ts
- packages/navie/test/commands/review-command.spec.ts
This pull request introduces a new `@review` command, enabling a seamless integration for conducting code reviews based on git diffs. This feature helps automate and streamline the code review process for pull requests by providing a structured analysis of code changes. 
- **Command Integration**: 
- The `@review` command hooks into the pre-existing explain functionality to identify user requests for code review, then generates the necessary git diff data.
- **Git Diff Handling**: 
- The command efficiently extracts git diffs from the specified range (e.g., `base..HEAD`) and integrates this into the user context for review.
- **Contextual Analysis**:
- Conducts a robust analysis of diffs in two rounds:
1. An initial chain-of-thought review focusing on specified areas of concern.
2. A …
> Add a `@review` command

- packages/cli/package.json
- yarn.lock
This update includes the fix to `@review` search terms.
> fix: Update `@appland/navie` to v1.36.2

- packages/navie/src/command.ts
- packages/navie/src/commands/welcome-command.ts
- packages/navie/src/navie.ts
- packages/navie/test/commands/welcome-command.spec.ts
This pull request introduces the `@welcome` command to the Navie service. The command returns structured JSON for a welcome message, enhancing user interaction by providing prompt suggestions and a descriptive activity statement. The main components of this update include the addition of the `WelcomeCommand` class, modifications to support the new command mode, and corresponding unit tests to ensure proper functionality.
- Added a new `Welcome` mode to the `CommandMode` enumeration.
- Implemented the `WelcomeCommand` class to process user inputs and generate appropriate outputs using the `completionService`.
- Integrated the `WelcomeCommand` into the existing command framework within the Navie application.
- Developed comprehensive unit tests for the `WelcomeCommand` to ensure reliability …
> feat: Add `@welcome` command

- packages/cli/src/cmds/index/rpc.ts
- packages/cli/src/lib/executeCommand.ts
- packages/cli/src/lib/git.ts
- packages/cli/src/rpc/explain/review.ts
- packages/cli/src/rpc/navie/isCustomWelcomeMessageEnabled.ts
- packages/cli/src/rpc/navie/metadata.ts
- packages/cli/tests/unit/rpc/explain/review.spec.ts
- packages/cli/tests/unit/rpc/navie/metadata.spec.ts
This pull request introduces several improvements and new features to the AppMap JavaScript project, particularly focusing on the handling of Git diffs for better code reviews and welcome message functionality.
1. **Git Diff and Base Commit Handling**: New functions like `getDiffLog`, `getCommitDistance`, `findNearestBranch`, and `findBaseCommit` have been added to effectively manage and calculate Git commit distances and determine the base branch. This refinement ensures that the least number of commits between the base and head are analyzed.
2. **Welcome Message Enhancements**: The welcome message now dynamically reflects the current task by analyzing changes in the current branch and within the worktree, providing relevant suggestions based on recent activities.
3. **Testing …
> feat: Welcome message is dynamic, reflecting what the user is working on

- packages/cli/.gitignore
Mainly doing this to trigger a release
> fix: Update gitignore

- packages/components/src/components/AddFileButton.vue
- packages/components/src/components/Button.vue
- packages/components/src/components/CodeSnippet.vue
- packages/components/src/components/chat-search/Context.vue
- packages/components/src/components/chat-search/ContextItem.vue
- packages/components/src/components/chat-search/CopilotNotice.vue
- packages/components/src/components/chat-search/LlmConfiguration.vue
- packages/components/src/components/chat-search/PinnedItems.vue
- packages/components/src/components/chat-search/VSCodeNotice.vue
- packages/components/src/components/chat/Chat.vue
- packages/components/src/components/chat/ChatInput.vue
- packages/components/src/components/chat/CodeSelection.vue
- packages/components/src/components/chat/ContextContainer.vue
- packages/components/src/components/chat/Loader.vue
- packages/components/src/components/chat/MarkdownCodeSnippet.vue
- packages/components/src/components/chat/MermaidDiagram.vue
- packages/components/src/components/chat/NextPromptButton.vue
- packages/components/src/components/chat/ToolStatus.vue
- packages/components/src/components/chat/UserMessage.vue
- packages/components/src/components/chat/WelcomeMessageV2.vue
- packages/components/src/pages/ChatSearch.vue
- packages/components/src/scss/_variables.scss
https://github.com/user-attachments/assets/84280d25-d5d1-4664-b279-6cdd8b9b3544
> feat: Navie uses user themes

- packages/cli/src/rpc/explain/collect-context.ts
- packages/cli/src/rpc/explain/collect-location-context.ts
- packages/cli/src/rpc/explain/collect-snippets.ts
- packages/cli/src/rpc/explain/explain.ts
- packages/cli/src/rpc/explain/location.ts
- packages/cli/src/rpc/explain/navie/navie-local.ts
- packages/cli/tests/unit/rpc/explain/collect-context.spec.ts
- packages/cli/tests/unit/rpc/explain/collect-location-context.spec.ts
- packages/cli/tests/unit/rpc/explain/collect-snippets.spec.ts
- packages/cli/tests/unit/rpc/explain/location.spec.ts
- packages/navie/src/agents/explain-agent.ts
- packages/navie/src/agents/gatherer.ts
- packages/navie/src/agents/generate-agent.ts
- packages/navie/src/commands/explain-command.ts
- packages/navie/src/context.ts
- packages/navie/src/prompt.ts
- packages/navie/src/services/agent-selection-service.ts
- packages/navie/src/services/apply-context-service.ts
- packages/navie/src/services/context-service.ts
- packages/navie/src/services/google-vertexai-completion-service.ts
- packages/navie/test/agents/__snapshots__/gatherer.spec.ts.snap
- packages/navie/test/agents/diagram-agent.spec.ts
- packages/navie/test/agents/examples/interaction-history.json
- packages/navie/test/agents/gatherer.spec.ts
- packages/navie/test/services/context-service.spec.ts
- packages/search/src/splitter.ts
- packages/search/test/splitter.spec.ts
This pull request introduces a significant enhancement to the AppMap-JS project through the implementation of a new Gatherer mechanism. The Gatherer is designed to efficiently collect comprehensive context information from a project to improve the accuracy and completeness of tasks performed by AI agents. Key aspects of this implementation include:
1. **Introduction of the Gatherer**: The Gatherer is a new component that optimizes the process of gathering all necessary information about a software project, enabling tasks to be accomplished with minimal guesswork and increased accuracy. Note currently it's only enabled if requested with `/gather` switch, agent mode is `@test` or `@generate` or the classifier is `overview`.
3. **Gatherer Functionality**:
- Utilizes AI completion services to …
> Implement Gatherer for enhanced context collection

- packages/cli/src/cmds/index/index.ts
- packages/cli/src/cmds/navie.ts
- packages/cli/src/rpc/explain/navie/navie-nop.ts
- packages/cli/tests/unit/rpc/explain/nop-navie.spec.ts
This provider effectively disables remote Navie and prevents transmission of any data.
> feat: Add a nop replacement for remote Navie

- packages/navie/src/lib/parse-json.ts
- packages/navie/src/services/context-service.ts
- packages/navie/src/services/openai-completion-service.ts
- packages/navie/src/services/vector-terms-service.ts
- packages/navie/test/agents/explain-agent.spec.ts
- packages/navie/test/lib/parse-json.spec.ts
This PR addresses the following:
1. JSON Parsing Enhancements:
- Improved parsing of JSON responses, especially for cases with or without code fences
- Added better support for multi-line JSON objects
- Implemented a more robust JSON object detection algorithm
- Added fallback parsing strategies for different response formats
2. Vector Search Improvements:
- Updated system prompt terminology from "question" to "inquiry" for better LLM compatibility
- I've observed Sonnet saying things like "you didn't provide a question" to inquiries such as "analyze this".
- Fixed pinned items inclusion in vector terms generation
> Enhance JSON parsing and improve vector search with pinned items

- packages/navie/src/services/openai-completion-service.ts
- packages/navie/test/services/openai-completion-service.spec.ts
This pull request addresses a critical update to the `OpenAICompletionService` by implementing a mechanism to notify users when a response is prematurely terminated due to content filtering restrictions. Additionally, it ensures proper handling of code blocks within responses under these circumstances.
- **Content Restriction Notification**: The system now detects when the LLM provider terminates a response due to content filtering (e.g., matches with public code). The user will be clearly notified with a message to explain the situation.
- **Proper Code Block Handling**: In cases where content filtering occurs during an ongoing code block response, the update will close any open code blocks before notifying the user, thus ensuring cleaner output.
- Updated test scenarios verify that …
> fix: Notify users of termination due to content restrictions

- packages/cli/src/cmds/navie/projectInfo.ts
- packages/cli/src/rpc/navie/services/contextService.ts
- packages/cli/tests/unit/rpc/navie/services/contextService.spec.ts
- packages/components/src/components/chat-search/ContextItem.vue
- packages/components/src/components/chat-search/ModelSelector.vue
- packages/components/src/components/chat/Chat.vue
- packages/components/src/components/chat/CodeSelection.vue
- packages/components/src/components/chat/MarkdownCodeSnippet.vue
- packages/components/src/components/chat/UserMessage.vue
- packages/components/src/pages/ChatSearch.vue
- packages/components/src/stories/UserMessage.stories.js
- packages/components/tests/unit/chat/ChatComponent.spec.js
- packages/components/tests/unit/chat/MarkdownCodeSnippet.spec.js
- packages/components/tests/unit/chat/ModelSelector.spec.js
This pull request introduces several fixes and improvements related to context handling and user interface elements in the chat and CLI components.
**Key Changes:**
*   **Diff Calculation:** Resolves an issue where diff generation could be ignored in projects lacking specific AppMap configurations. Diffs should now be calculated correctly across all defined project directories when requested via the CLI.
*   **UI - Model Selector:** Enhances the model selection UI. The provider's name (e.g., "via OpenAI") is now displayed alongside the selected model name. Additionally, the currently selected model is visually highlighted within the dropdown list for better clarity.
*   **UI - Message Attachments:** Corrects how message attachments (like code snippets added before sending a message) are …
> Chat bug fixes and cosmetics

- packages/cli/src/rpc/configuration.ts
- packages/cli/src/rpc/navie/thread/index.ts
- packages/cli/tests/unit/rpc/explain/location.spec.ts
- packages/components/src/pages/ChatSearch.vue
This avoids issues with equality checks and path joining internally.
> fix: Normalize Windows paths on ingress

- packages/cli/src/lib/ticket/zendesk.ts
- packages/cli/tests/unit/lib/zendesk.spec.ts
- packages/cli/tsconfig.json
- packages/navie/src/commands/review-command.ts
- packages/navie/test/commands/review-command.spec.ts
- yarn.lock
This is a hotfix for token limit handling in review command with copilot. A comment indicates a proper fix (for future implementation).
(This pull request also includes two unrelated changes I've had lying around from a while ago: update of `elliptic` dependency (got flagged for security, although I don't believe the problem impacted us) and refactoring of zendesk submission (a step to remove axios dependency which we're barely using).)
* [`packages/navie/src/commands/review-command.ts`](diffhunk://#diff-c56ef7ba1132c7e31c9f4fe2c1d14cd5a563b569f9ec8589b8503775e2f18a48R345-R382): Implemented error handling for token limit exceeded errors in the review command, providing user guidance on how to proceed.
* [`packages/navie/test/commands/review-command.spec.ts`](diffhunk://#diff-38675863df6e40 …
> fix: Handle copilot limit in review command

- packages/cli/src/fingerprint/appmapIndex.ts
- packages/cli/src/fingerprint/fileTooLargeError.ts
- packages/cli/src/fingerprint/fingerprintDirectoryCommand.ts
- packages/cli/src/fingerprint/fingerprintQueue.ts
- packages/cli/src/fingerprint/fingerprintWatchCommand.ts
- packages/cli/src/fingerprint/fingerprintWorker.ts
- packages/cli/src/fingerprint/fingerprinter.ts
- packages/cli/src/lib/UpToDate.ts
- packages/cli/src/lib/workerPool.ts
- packages/cli/tests/binary/index.bin-spec.ts
- packages/cli/tests/unit/fingerprint/fingerprintQueue.spec.ts
This pull request introduces significant changes to the `packages/cli` module, primarily focusing on enhancing the fingerprinting process and error handling. The updates include the implementation of a worker pool for parallel processing, improvements to error handling, and refactoring for better code structure and readability.
* [`packages/cli/src/fingerprint/fingerprintQueue.ts`](diffhunk://#diff-1cbf0d56a4e333af286a2005e644c557e7db7a5b8e5833f7c79861338b22ff33L1-R107): Refactored `FingerprintQueue` to use a worker pool for parallel processing of AppMap files, improving efficiency and scalability. Added detailed comments and examples for better understanding.
* [`packages/cli/src/fingerprint/fingerprintWorker.ts`](diffhunk://#diff-0c3bb230d76ac3f4271eea8bbc62a3c648a1a8c3faecaaf4a28bce843b …
> More robust indexing 

- packages/navie/src/services/openai-completion-service.ts
- packages/navie/src/services/vector-terms-service.ts
Update the user prompt format in the suggestTerms method to clarify intent for the model. This change aims to prevent models from misinterpreting the input when generating search terms.
> Enhance debugging and improve user prompt format in suggestTerms method

- packages/cli/LICENSE.txt
- packages/models/LICENSE.txt
- packages/navie/LICENSE.txt
- packages/rpc/LICENSE.txt
- packages/scanner/LICENSE.txt
- packages/search/LICENSE.txt
- packages/sequence-diagram/LICENSE.txt
Making sure our licenses are up to date
> chore: Update copyright to 2025

- packages/navie/package.json
- packages/navie/src/commands/review2-command.ts
- packages/navie/test/commands/review2-command.spec.ts
- packages/rpc/src/index.ts
- packages/rpc/src/review.ts
- yarn.lock
This pull request introduces significant improvements to the `Review2Command` in `packages/navie` and adds new types and functionality to the `ReviewRpc` namespace in `packages/rpc`. The changes enhance the handling of AppMaps (sequence diagrams), improve output formatting, and streamline the conversion of suggestions for better integration with the review process.
This is prerequisite work to support the new review UI.
* **AppMap Integration**:
- Added support for AppMaps in suggestions to provide additional context. Suggestions now include an optional `appmaps` field, which lists related AppMaps and their metadata. [[1]](diffhunk://#diff-0bafb68b68f6773fcaffd9ca69789e5fd59e62a967d99c5218ca93faa76716e3R301-R306) [[2]](diffhunk://#diff-0bafb68b68f6773fcaffd9ca69789e5fd59e62a967d99c5218ca93 …
> JSONL support in review2
