getappmap/appmap-js

src/pages/VsCodeExtension.vue

Since PR #115 has been approved and merged switching between tabs becomes smooth and fast.
This PR add global app loader when app instance was initialized, but AppMap data wasn't loaded yet.
Fixes #101

feat: show app loader while AppMap data is loading

---

.eslintrc.js
src/components/DetailsPanel.vue
src/components/DetailsPanelList.vue
src/components/DetailsPanelQuery.vue
src/components/DetailsSearch.vue
src/pages/VsCodeExtension.vue
tests/e2e/specs/vsCodeExtension.spec.js

Display code object with type `query` in Details panel.
Fixes: #129

feat: show SQL queries as code objects in Details panel

---

src/pages/VsCodeExtension.vue
tests/unit/components/VsCodeExtension.spec.js

**NB!** There is a breaking change, because `setSelectedObject` method and `selectedObject` event were removed from `VsCodeExtension` component.
With this PR we must read/write app state only with:
- `getState/setState` methods
- `stateChanged` event

Manage app state with getState/setState API

---

src/stories/DiagramComponent.stories.js
src/stories/DiagramFlow.stories.js
src/stories/Trace.stories.js
src/stories/VsCodeExtension.stories.js
src/stories/VsCodeExtensionJava.stories.js

Set delay for Chromatic screenshots for some components with animation (`DiagramComponent`, `DiagramTrace` and `VsCodeExtension`).
Fixes: #179

test: set Chromatic delay for some components with animation

---

src/lib/models/appMapBuilder/index.js
src/lib/models/event.js

In Details panel HTTP `status` will be displayed with status key, despite [`the official specification`](https://github.com/applandinc/appmap#http-server-request-return-attributes) where HTTP response event must have required `status_code` key.
Fixes: #171

fix: display HTTP server response status in 'status' property

---

src/components/TabButton.vue
src/pages/VsCodeExtension.vue

- add `white-space: nowrap;` for tab buttons
- set minimum width for diagrams container (right column)
Fixes: #189

fix: prevent word wrapping in tab buttons

---

packages/diagrams/src/componentDiagram/index.js

fix: don't expand class with one function by default

---

packages/components/src/components/DetailsSearch.vue

fix: empty lists are not visible in search panel results

---

packages/components/tests/e2e/specs/vsCodeExtension.spec.js
packages/models/src/classMap.js
packages/models/tests/unit/classMap.spec.js

With this change we don't filter out CodeObjects array anymore because it used by Dependency Map where packages/classes without events are still present.
Fixes: #206

fix: filter out ClassMap nodes without events

---

packages/components/src/pages/VsCodeExtension.vue

CSS property `position: relative;` was missing on `#app`, that's why "no data" notice was rendered full-screen.
Before:
After:
Fixes: #240

fix: "no data" screen is rendered inside it's parent

---

packages/components/src/stories/data/java_scenario.json
packages/models/src/classMap.js
packages/models/src/codeObject.js
packages/models/tests/unit/fixtures/spring_petclinic.json

Improve the performance and correctness of the code which binds events to code objects.
When loading many AppMaps, the `O(N*M)` nature of event registration was a problem. 
Scanning all code objects (M) for every event (N) is the issue: https://github.com/applandinc/appmap-js/pull/239/files#diff-2208f30747bef29ba042cc56931d47112b3bf25d8b47d9760ad31178e249a5e8L84

fix: Improve bind events

---

packages/components/src/components/Container.vue
packages/components/src/components/DiagramTrace.vue
packages/components/src/components/trace/TraceNode.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/e2e/specs/vsCodeExtension.spec.js
packages/diagrams/src/util.js

Tweening the viewport to focus on nodes was behaving unexpectedly, leaving many nodes clipped or completely outside of the viewport.
https://github.com/applandinc/appmap-js/issues/251

fix: Trace node panning now guarantees that the selected node ends in the viewport

---

packages/cli/src/search/codeObjectMatcher.js
packages/cli/src/search/findCodeObjects.js
packages/cli/src/search/trigram.js

Don't terminate the search once a match is found.
Keep searching for all e.g. matching tables in an AppMap.

fix: Find all matching events in each AppMap

---

packages/cli/src/telemetry.ts
packages/cli/tests/unit/telemetry.spec.ts

Ignore the value of process.env.APPMAP_TELEMETRY_DISABLED when running
tests.

tests: Ignore APPMAP_TELEMETRY_DISABLED

---

packages/cli/src/telemetry.ts

fix: user's machine ID in CLI is calculated as in VSCode source code

---

packages/cli/src/cmds/agentInstaller/commandRunner.ts
packages/cli/src/cmds/agentInstaller/pythonAgentInstaller.ts

Avoid quoting issues (especially on Windows) by using
child_process.spawn instead of exec. Take advantage of this change by
removing some quoting in the Python installer.
I don't see any tests for this functionality. I've tested the python installer on macOS and Windows, and it works on both platforms. I've also inspected all places where `CommandStruct`s are created, so finger's crossed....

fix: Use child_process.spawn instead of exec

---

packages/cli/src/telemetry.ts
packages/cli/tests/unit/telemetry.spec.ts

Session identifiers were being regenerated on every run because they were not being written to disk.
Resolves #371

fix: Sessions are now properly persisted on disk

---

packages/components/src/pages/quickstart-docs/InstallAgent.vue
packages/components/src/stories/QuickstartDocsInstallAgent.stories.js

I found that the command was hardcoded after attempting to change it downstream. This fixes that.

fix: Move install docs command and copied text to props

---

packages/cli/src/cmds/agentInstaller/agentInstallerProcedure.ts
packages/cli/src/cmds/agentInstaller/agentProcedure.ts
packages/cli/src/cmds/agentInstaller/agentStatusProcedure.ts
packages/cli/src/cmds/agentInstaller/commandRunner.ts
packages/cli/src/cmds/agentInstaller/install-agent.ts
packages/cli/src/cmds/agentInstaller/installers.ts
packages/cli/src/cmds/agentInstaller/projectConfiguration.ts
packages/cli/src/cmds/agentInstaller/status.ts
packages/cli/src/cmds/agentInstaller/telemetryUtil.ts
packages/cli/src/cmds/errors.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts
packages/cli/tests/unit/agentInstall/statusCommand.spec.ts
packages/cli/tests/unit/fixtures/java/multi-project/project-a/pom.xml
packages/cli/tests/unit/fixtures/java/multi-project/project-b/build.gradle

If sub-projects are detected, this change will ask the user if they'd like to select sub-projects. If so, they'll have the ability to select which sub-projects to install to. The installer flow will then be run for each directory selected.
Also, incorrect installer path errors or process abort cases are now reported as `soft_failure`.
See the updated flow here: https://asciinema.org/a/e3sVXMwRHN8Ul1s4YKd10GMeg

feature: multi-project installer

---

package.json
packages/cli/package.json
packages/cli/webpack.config.js
yarn.lock

When creating the package for publishing, make sure to include the `resources` folder. Fixes #440.
Also, temporarily include a `devDependency` on `node-gyp` to fix a problem installing dependencies on macOS.

Copy resources folder when bundling

---

packages/cli/src/cmds/agentInstaller/agentInstallerProcedure.ts
packages/cli/src/cmds/agentInstaller/javaBuildToolInstaller.ts
packages/cli/src/cmds/agentInstaller/jetBrainsSupport.ts
packages/cli/src/cmds/agentInstaller/mavenInstaller.ts
packages/cli/tests/unit/agentInstall/javaBuildToolInstaller.spec.ts

Use the IntelliJ embedded JDK and build tools, if available and not overriden, when installing and validating the Java agent. The user can override the use of the embedded components by setting the `PATH` and `JAVA_HOME` environment variables appropriately.
Fixes #413.

Use IntelliJ JDK and build tools

---

packages/cli/src/cmds/agentInstaller/install-agent.ts
packages/cli/src/telemetry.ts

`Yargs.exit` results in a call to `process.exit`, immediately exiting the process without waiting for promises to resolve. This was resulting in us losing some data. As a result, all telemetry events are now sent without `await`, and if the queue is not clear by the time the command is finishing, we'll wait for the queue to flush. This won't capture exit via `SIGINT` or similar, but that's a more complicated effort.

fix: Wait for debugging information on exit

---

packages/cli/src/cli.ts
packages/cli/src/cmds/agentInstaller/install-agent.ts
packages/cli/src/openapi/command.js
packages/cli/src/openapi/util.js
packages/cli/tests/unit/openapi.spec.ts

Add type mappings for Python and Java. This ensures that all types that
can appear in AppMaps will get mapped to the corresponding OpenAPI type.
Fixes #445.

fix: Map language types to OpenAPI types

---

packages/cli/package.json

Add a prepack hook to the package.json. This will cause the updates
applied by semantic-release (e.g. the new version) to be included in the
compiled sources that are packaged and published to npm.

fix: Show the correct version with --version

---

.releaserc.js
package.json
packages/cli/package.json

In case the published package copies package.json, rebuild the package before publishing artifacts.

fix: Rebuild packages before publish

---

packages/models/src/util.js

FIxes `TypeError: Cannot read property 'forEach' of undefined` error.

Fix hash generation for events without parameters/labels

---

packages/cli/src/cmds/agentInstaller/agentProcedure.ts
packages/cli/src/cmds/agentInstaller/install-agent.ts
packages/cli/src/telemetry.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts

Make sure we send `install-agent:success`. Also, move the call to `Telemetry.flush()` into an exit handler.

Bring back install-agent:success

---

packages/cli/src/cmds/agentInstaller/javaScriptAgentInstaller.ts
packages/cli/src/encodedFile.ts
packages/cli/tests/unit/encodedFile.spec.ts

Allow the user to specify a different appmap-agent-js package by setting `APPMAP_AGENT_PACKAGE`.
Also, fix #455.

Add support for APPMAP_AGENT_PACKAGE

---

packages/components/src/pages/quickstart-docs/RecordAppMaps.vue

**NB!** For vscode link I added `.html` extension to the end of link, because all other links have it:
https://appland.com/docs/quickstart/vscode/java-step-3.html
https://appland.com/docs/quickstart/vscode/python-step-3.html
https://appland.com/docs/quickstart/vscode/ruby-step-3.html
Fixes #465

feat: add links for JavaScript docs in Quickstart

---

packages/cli/src/cmds/agentInstaller/agentInstaller.ts
packages/cli/src/cmds/agentInstaller/agentProcedure.ts
packages/cli/src/cmds/agentInstaller/gradleInstaller.ts
packages/cli/src/cmds/agentInstaller/javaBuildToolInstaller.ts
packages/cli/src/cmds/agentInstaller/javaScriptAgentInstaller.ts
packages/cli/src/cmds/agentInstaller/mavenInstaller.ts
packages/cli/src/cmds/agentInstaller/pythonAgentInstaller.ts
packages/cli/src/cmds/agentInstaller/rubyAgentInstaller.ts
packages/cli/tests/unit/agentInstall/agentInstaller.spec.ts
packages/cli/tests/unit/agentInstall/statusCommand.spec.ts

Resolve the path passed to the installer to ensure that we always know where the project is, even if the working directory is changed.
There are no functional changes the `refactor` commit b905bb3.
Fixes #467.
Fixes #469.
Fixes #471.

Use absolute path when installing

---

packages/cli/src/cmds/agentInstaller/projectConfiguration.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts
packages/cli/tests/unit/fixtures/java/multi-project-root/pom.xml
packages/cli/tests/unit/fixtures/java/multi-project-root/project-a/pom.xml
packages/cli/tests/unit/fixtures/java/multi-project-root/project-b/build.gradle

If a project has a build config file in the current directory, but also
has sub-projects, make installing in the current directory be the
default choice.
Fixes #461 .

fix: Nudge user to install in current project

---

packages/models/package.json
yarn.lock

This bumps sqlite-parser to a patched version that accepts PSQL-style casts and custom operators.

feat: Correctly parse some PostgreSQL-specific constructs

---

packages/cli/src/cmds/agentInstaller/commandRunner.ts
packages/cli/tests/unit/agentInstall/commandRunner.spec.ts

Tell child_process.spawn to use a shell. If we don't, on Windows it can
only find .exe's, and npm and npx are .cmd files.

fix: Use a shell when running a command

---

packages/components/src/pages/VsCodeExtension.vue

fix: remove bottom margin of Trace view filter input

---

packages/components/src/components/Container.vue

This change will prevent clipping Trace view on https://app.land

fix: set container max-width to 100%

---

packages/cli/tests/unit/agentInstall/commandRunner.spec.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts

The change to use a timeout to call `Yargs.exit` after flushing telemetry events broke many of the installer tests. (In one case, the way the test failed meant it called `process.exit(0)`, which hid all the failures.)
These changes ensure that `Yargs.exit` is called synchronously by `Telemetry.flush`, and use a regexp to verify that "command not found" errors are detected. They also add calls to `expect.assertions` to make sure all `expect` calls are actually getting executed.

Fix installer tests

---

packages/client/src/buildRequest.ts

Add a missing import of `URL` from `node:url`.

fix: Add missing import of URL

---

packages/components/src/components/FiltersForm.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/e2e/specs/vsCodeExtension.spec.js

To check this functionality, you can open filters panel, focus into "Root objects" input and type ArrowUp and ArrowDown on the keyboard.
https://user-images.githubusercontent.com/17301016/146234893-719eb60a-e9e9-4d3b-866b-de672d64a001.mp4
Fixes #482 
Fixes #480

feat: keyboard navigation for filter suggestions

---

packages/client/.eslintrc.js
packages/client/src/buildRequest.ts
packages/client/src/get.ts
packages/client/src/handleError.ts
packages/client/src/loadConfiguration.ts
packages/client/src/reportJson.ts

These imports restrict the node version to v16+. We could potentially remove them in a post-process build step, but I don't think it's worth the effort.

fix: Drop node protocol import

---

packages/cli/src/cli.ts
packages/cli/src/cmds/prune/prune.ts
packages/cli/src/cmds/prune/pruneAppMap.ts
packages/cli/tests/unit/prune.spec.ts
packages/models/PRUNING.md

Bring over the prune subcommand from appland/appmap-cli. That package
also exports an `appmap` command, which conflicts with ours.

feat: Port prune subcommand

---

packages/cli/package.json
packages/cli/src/cmds/open/openers.ts
yarn.lock

The supports-hyperlinks dependency was added in such a way that it wasn't bundled (very odd - non-standard).
Now it should be fine and be included with the distribution.

fix: Add supports-hyperlinks dependency

---

.travis.yml
packages/cli/src/cmds/agentInstaller/commandStruct.ts
packages/cli/tests/unit/agentInstall/commandRunner.spec.ts

When creating a CommandStruct, add quotes around any element of args that
contains a space.

fix: Handle spaces in CommandStruct.args

---

packages/cli/src/cmds/agentInstaller/agentInstaller.ts
packages/cli/src/cmds/agentInstaller/agentInstallerProcedure.ts
packages/cli/src/cmds/agentInstaller/gradleInstaller.ts
packages/cli/src/cmds/agentInstaller/javaScriptAgentInstaller.ts
packages/cli/src/cmds/agentInstaller/mavenInstaller.ts
packages/cli/src/cmds/agentInstaller/pythonAgentInstaller.ts
packages/cli/src/cmds/agentInstaller/rubyAgentInstaller.ts
packages/cli/tests/unit/agentInstall/agentInstaller.spec.ts

Get rid of the language-specific post-install message after successful install. Just direct the user to the  doc page for the agent.

fix: Update post-install messages

---

.gitattributes
packages/models/package.json
packages/models/src/event.js
packages/models/src/event/hash.js
packages/models/src/sql/parse.js
packages/models/src/sql/parseError.js
packages/models/src/util.js
packages/models/tests/unit/event/hash.spec.js
packages/models/tests/unit/sql.spec.js

Hashing a call event now only considers the fields which are truly specific to the call generalically and not specific arguments that     were used. This also includes literals and variables in SQL queries.
Note that all events will now have different hashes than previously calculated, so the transition can confuse change tracking. Also the new algorithm refuses to hash non-call events (as they don't really have any data that is generic enough to make sense).

feat: Improved event hash

---

packages/cli/src/cmds/record/createRecording.ts

This changes sets `metadata.name` in the AppMap data before writing it to a file. As a result, AppMaps will no longer be untitled in VSCode.

fix: Set the metadata name property before writing out AppMap data

---

packages/cli/package.json
packages/cli/src/fingerprint/canonicalize/sqlTables.js
packages/cli/src/fingerprint/canonicalize/trace.js
packages/cli/src/functionStats.js
packages/cli/tests/unit/fingerprint/sqlTables.spec.js
packages/cli/tests/unit/fingerprint/trace.spec.js
yarn.lock

* Require minimum necessary version of `@appland/models`.
* Handle cases where `analyzeSQL` returns null.
Does this surprise you? It did me:
```
> typeof(null)
'object'
```

fix: OpenAPI gen

---

packages/components/tests/e2e/specs/vsCodeExtension.spec.js
packages/models/src/classMap.js
packages/models/tests/unit/classMap.spec.js

fix: filter out other children of package when one child was set as root

---

packages/models/src/appMapBuilder/index.js
packages/models/src/event.js

For some reason in some AppMaps `normalized_path_info` is preset as empty array.
According to [AppMap specification ](https://github.com/applandinc/appmap#http-server-request-call-attributes) it's not expected behavior, but to make plugin work with such AppMaps I've added type cast to `string`.

fix: empty "normalized_path_info" of HTTP server request is present as empty array in AppMap

---

packages/models/src/appMapBuilder/index.js
packages/models/tests/unit/appMapBuilder.spec.js
packages/models/tests/unit/fixtures/large_scenario.json

Fixes SCAN-196
This change is needed to remove username/password from git repository URLs.

fix: remove credentials from git repository URLs

---

packages/components/src/components/DetailsPanelEvent.vue
packages/components/src/components/SqlCode.vue
packages/components/src/components/trace/TraceNodeBodySql.vue
packages/components/tests/unit/DetailsPanelEvent.spec.js

In some cases, formatting PostgreSQL queries would fail when attempting to format them as generic SQL. We'll now use `database_type` as a hint for how to format the SQL query and if all else fails, we'll render it as-is instead of throwing an exception.
In practice, this error would result in empty query strings:
They'll now render as intended:

fix: Use database hints to format SQL

---

packages/components/src/components/SourceCodeLink.vue
packages/components/src/stories/VsCodeExtension.stories.js
packages/components/src/stories/support/resolvePath.js
packages/components/tests/unit/SourceCodeLink.spec.js

- `viewSource` was not being emitted on click. The only means of emitting the event would be to have access to the element.
- Instead of an `external` boolean flag, the logic responsible for resolving external source code paths can cache an external URL by providing an `externalUrl` property in the response.
- The test case to validate the `viewSource` event was failing yet silently passing.

fix: View source event

---

packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/unit/VsCodeExtension.spec.js

This is causing issues downstream. We're accessing `traceFilter` which may not yet exist if we're not in the trace view.

fix: Delay mutation of the trace filter until the view has changed

---

packages/scanner/src/cli/scan/command.ts
packages/scanner/src/rules/nPlusOneQuery.ts
packages/scanner/test/scanner/nPlusOneQuery.spec.ts

N+1 SQL must have the same ancestor at the same depth.
This differentiates true N+1 queries from cases where there are duplicate queries in a request, but they are not true N+1.

feat: N+1 queries must have the same common ancestor

---

packages/cli/src/fingerprint/canonicalize/classes.js
packages/scanner/bin/upload.rb
packages/scanner/package.json
packages/scanner/src/cli/ci/command.ts
packages/scanner/src/cli/scan/command.ts
packages/scanner/src/cli/scan/options.ts
packages/scanner/src/cli/scanArgs.ts
packages/scanner/src/cli/upload/command.ts
packages/scanner/src/configuration/configurationProvider.ts
packages/scanner/src/rules/lib/util.ts
packages/scanner/test/cli/scan.spec.ts

Default scanner config file becomes `appmap-scanner.yml` (was: no default besides the default sampleConfig). If `appmap-scanner.yml` is not available, the default sampleConfig is used, as before.
Default findings file becomes `appmap-findings.json` (was: `appland-findings.json`).
If `appmap.yml` contains *appmap_dir*, it will be used as the default dir for the `scan` and `ci` commands.

feat: Change filename defaults

---

packages/scanner/src/cli/upload.ts
packages/scanner/src/cli/upload/pruneAppMap.ts
packages/scanner/test/cli/upload.spec.ts

Limit the size of each uploaded AppMap to 40MB.

fix: Have scanner prune AppMaps before uploading

---

packages/cli/package.json
yarn.lock

I can confirm that the build is now building the cli.js to `built/cli.js`, and that running that script seems to work:
```
➜  cli git:(main) ls built/cli.js
built/cli.js
➜  cli git:(main) node built/cli.js 
cli.js <command>
Commands:
cli.js diff                   Compute the difference between two mapsets
cli.js depends [files]        Compute a list of AppMaps that are out of date
cli.js inspect <code-object>  Search AppMaps for references to a code object
(package, function, class, query, route, etc)
and print available event info
```

fix: Correct packages/cli bin script location

---

packages/cli/package.json
packages/cli/webpack.config.js
yarn.lock

The compiled files have moved directly to `built` instead of `built/src`, but still referred to `resources` two directories up, ending up pointing at `packages/cli/resources` instead of `packages/cli/built/resources`. The solution was to include the `resources` directory when creating the package. Old code copying `resources` to `built/resources` could now be removed.

fix: Openapi template is packaged correctly and the command works again

---

packages/components/src/componentExports.js
packages/components/src/components/CodeSnippet.vue
packages/components/src/components/mixins/navigation.js
packages/components/src/components/quickstart/QuickstartLayout.vue
packages/components/src/pages/InstallGuide.vue
packages/components/src/pages/MultiPage.vue
packages/components/src/pages/install-guide/Analyze.vue
packages/components/src/pages/install-guide/Collaboration.vue
packages/components/src/pages/install-guide/InvestigateFindings.vue
packages/components/src/pages/install-guide/OpenAppMaps.vue
packages/components/src/pages/install-guide/ProjectPicker.vue
packages/components/src/pages/install-guide/RecordAppMaps.vue
packages/components/src/stories/InstallGuide.stories.js

feat: Add `Open AppMaps` to install guide

---

.releaserc.js
.travis.yml
package.json

This is to avoid build errors like the one at https://app.travis-ci.com/github/applandinc/appmap-js/jobs/571098857
Also, simplify the semantic-release config a bit.

Don't try to release @appland/telemetry

---

packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/e2e/specs/vsCodeExtension.spec.js

Fixes: https://linear.app/appland/issue/MAP-300/limit-root-events-to-http-filter-is-unselected-when-needed-to-make-an

fix: disable "Limit root events to HTTP" filter when searching for hidden root event

---

packages/cli/src/cmds/record/action/configureRemainingRequestOptions.ts
packages/cli/src/cmds/record/action/detectProcessCharacteristics.ts
packages/cli/src/cmds/record/configuration.ts
packages/cli/src/cmds/record/prompt/continueWithRequestOptionConfiguration.ts
packages/cli/src/cmds/record/state/agentNotAvailable.ts
packages/cli/src/cmds/record/state/record_remote.ts
packages/cli/tests/unit/record/record.remote.spec.ts

Even if the server process can't be found in the process table, the user can elect to continue with remote recording and specify extended options for the URL connection.

fix: User can configure extended RR URL

---

packages/scanner/src/cli/scan/command.ts
packages/scanner/src/cli/scan/watchScan.ts
packages/scanner/test/cli/scan.spec.ts

In watch mode, scan command watches the config file and reloads the checks config when the file is modified.

feat: Watch the scan config file

---

packages/cli/src/cmds/record/action/startTestCases.ts
packages/cli/src/cmds/record/record.ts
packages/cli/src/utils.js
packages/components/CHANGELOG.md
packages/components/package.json

Fix two bugs in the record command:
* listAppMapFiles blows up with a `stat` error when the indexer is writing temp files into the index directory
* maxTime may be non-numeric, in which case it's not properly enforced

fix: Record command

---

packages/cli/src/fingerprint/fingerprintQueue.js
packages/cli/src/fingerprint/fingerprinter.js
packages/cli/src/utils.js
packages/cli/tests/unit/fingerprint/fingerprintQueue.spec.ts

A race condition existed where an AppMap may be deleted during the fingerprinting process. If this were to occur the command would panic and exit, even in `--watch` mode. This commit changes the behavior to instead log a warning and continue.
This is was most often observed in automated testing where files are quickly written and removed.
Resolves MAP-368

fix: Index no longer panics on missing files

---

packages/components/src/pages/InstallGuide.vue

This change fixes a bug which causes the project state not to be reactive. A reference to an existing project would not be updated as project states change.
Fixes MAP-341

fix: Project state is reactive

---

packages/models/src/eventNavigator.js
packages/models/tests/unit/eventNavigator.spec.js

EventNavigator.descendants used recursion for going down the
structure; unfortunately node didn't seem to do TCO which led
to the structure depth being limited by the stack depth.
After changing code to iterate instead it can handle arbitrary depth.

fix: Handle deep structures in EventNavigator.descendants

---

packages/openapi/src/schemaInferrer.ts
packages/openapi/test/schemaInferrer.spec.ts

Without this code change, the new test case fails as follows:
```
FAIL  test/schemaInferrer.spec.ts (7.358 s)
● SchemaInferrer › can merge arrays that don't have items
TypeError: Cannot use 'in' operator to search for 'type' in undefined
> 36 |     if ('type' in a.items && 'type' in b.items) {
|               ^
37 |       const merged = mergeType(a.items, b.items);
38 |       if (merged) return { ...a, items: merged };
39 |     }
at mergeType (src/schemaInferrer.ts:36:15)
at mergeProperties (src/schemaInferrer.ts:14:20)
at mergeType (src/schemaInferrer.ts:45:19)
at Array.reduce (<anonymous>)
at SchemaInferrer.openapi (src/schemaInferrer.ts:63:20)
at Object.<anonymous> (test/schemaInferrer.spec.ts:43:21)
```
Reported in community Slack (advise this user when the fix is released):
Fixes …

fix: Merge succeeds when examples are missing 'items'

---

packages/components/src/pages/install-guide/RecordAppMaps.vue
packages/components/tests/unit/RecordAppMaps.spec.js

Hide all disabled languages when rendering the RecordAppMaps view.
To support fixing applandinc/board#30.

feat: Hide disabled languages in RecordAppMaps

---

packages/cli/src/cmds/open/showAppMap.ts

Always open the AppMap when recording finishes. If we're running in the
vscode terminal, on macOS, it will open in vscode. Otherwise, it will
open in a browser tab.

fix: record subcommand now always opens the AppMap

---

packages/cli/tests/unit/inspect.spec.js
packages/models/src/classMap.js
packages/models/src/codeObject.js
packages/models/src/event.js
packages/models/src/util.js
packages/models/tests/unit/classMap.spec.js
packages/models/tests/unit/event.spec.js

`CodeObject#toJSON` was omitting some fields from the source data. This PR ensures that all the expected fields are emitted. It does the same for `Event` as well, although this problem is not known to be occurring with Event (not to say it wasn't...). 
As a result, printing an AppMap object to JSON will result in a valid and complete AppMap. So, for example, raw AppMap data can be loaded, normalized, and then printed without loss of data.
Fixes https://github.com/applandinc/appmap-js/issues/637

fix: Emit missing data fields to JSON

---

packages/components/src/components/SqlCode.vue

Even though we're only using highlight.js for SQL, we used to load support for all languages, which ended up being bundled with in our webpage and VS code extension. Loading only SQL significantly (>1 MiB) improves bundle footprint.
Here's the VS code extension webview bundle before this change:
```
asset app.js 2.98 MiB [emitted] [big] (name: main) 1 related asset
```
And after:
```
asset app.js 1.7 MiB [emitted] [big] (name: main) 1 related asset
```

Only load SQL language for highlight.js

---

packages/components/src/stories/ProjectPicker.stories.js

Closes https://github.com/applandinc/board/issues/81
Fix typos, use consistent language for Install steps. 
Existing:
- `This project looks like Ruby. It's one of languages supported by AppMap!`
- `This project uses Rails. AppMap enables recording web requests and remote recording.`
New:
- `This project looks like Ruby. It's one of the languages supported by AppMap.`
- `This project uses Rails. AppMap will automatically recognize web requests, SQL queries, and key framework functions during recording.`

fix typos, and consistent wording & punctuation

---

packages/scanner/src/cli/scan/watchScan.ts
packages/scanner/test/cli/scan.spec.ts

`scan --watch` was missing fs events for mtime files if the parent directory was removed and recreated. An automated test now verifies this case, however if you'd like to see it yourself, here are the steps:
1. Run `appmap index --watch` and `scanner scan --watch` together in the same directory
2. Touch an appmap file
3. Delete the new directory containing the indexed data for that appmap
4. Touch the same appmap file
Previously, the indexer would recreate the directory but the scan would fail to receive an event. This has something to do with Chokidar watching a relative path instead of an absolute path. There are a number of reports of similar issues on their GitHub.

fix: `scan --watch` picks up mtime files which have been deleted and restored

---

packages/components/src/components/install-guide/ProjectPickerRequirements.vue

Fixes applandinc/board#94
Changed the links in the project picker to go to the Agent Installation section instead of the Reference section, because the user needs to install the AppMap Agent at this stage. 
Also, this better highlights that Python and JS are in beta, because the Open Beta message appears near the top of the page in the Agent Installation section.

Fix: update links to docs in project picker

---

packages/components/src/pages/install-guide/InvestigateFindings.vue
packages/components/src/pages/install-guide/RecordAppMaps.vue

Heading sizes should match the size used in Project-picker (2rem).
Fixes https://github.com/applandinc/board/issues/97
Project-picker (reference):
Before: 
After:

Fixes: consistent heading sizes for install-guide

---

packages/components/src/components/install-guide/ProjectPickerRequirements.vue

The links to the docs for Python and JavaScript were mistakenly switched. I fixed them so that now they go to the correct page.

Fix: switch links for python and js

---

packages/validate/src/macro.yml

The majority of the optional property of objects have been made 
nullable. So the property can either be absent or null. This change 
extend this behaviour to all optional properties for better consistency.

feat: make sure every optional field is nullable

---

packages/scanner/src/analyzer/recordSecrets.ts
packages/scanner/src/ruleChecker.ts
packages/scanner/src/rules/circularDependency.ts
packages/scanner/src/rules/illegalPackageDependency.ts
packages/scanner/src/rules/insecureCompare.ts
packages/scanner/src/rules/jobNotCancelled.ts
packages/scanner/src/rules/nPlusOneQuery.ts
packages/scanner/src/rules/queryFromInvalidPackage.ts
packages/scanner/src/rules/secretInLog.ts
packages/scanner/src/types.d.ts
packages/scanner/test/scanner/jobNotCancelled.spec.ts
packages/scanner/test/scanner/nPlusOneQuery.spec.ts
packages/scanner/test/scanner/secretInLog.spec.ts

Currently, each finding has an `event` which is the event that the finding "occurs on". But in actuality, many findings have more than one event that are instrumental to the finding. For example, for the secrets in log finding, the two participating events are the event that generated the secret, and the event that wrote to the log.
This PR adds `participatingEvents` which should include all events that are instrumental to the finding. In a subsequent PR, the finding hash will be composed from all these events.
Participating events is distinct from `relatedEvents` in that `relatedEvents` may add context to the finding, but do not directly participate in it and should not be included in the finding hash.

feat: Add participating events to each finding

---

packages/cli/src/cli.ts
packages/cli/src/lib/appmapDirFromConfig.ts
packages/cli/src/lib/handleWorkingDirectory.ts
packages/cli/src/lib/locateAppMapDir.ts

`diff` and `inventory` commands will use default `appmap_dir` from *appmap.yml*.
This is a start on adding this behavior to all the commands.

feat: Handle -d working directory arg

---

packages/cli/smoketest.sh
packages/components/src/components/install-guide/NavigationButtons.vue
packages/components/src/pages/InstallGuide.vue
packages/components/src/pages/install-guide/InvestigateFindings.vue
packages/components/src/stories/InvestigateFindings.stories.js
packages/components/tests/e2e/specs/investigateFindings.spec.js
packages/components/tests/e2e/specs/investigateFindingsEmpty.spec.js

Closes https://github.com/applandinc/board/issues/28
Updates the Investigate findings message:
OLD
NEW
Updates the project not scanned message:
OLD:
NEW:
Adds content for 'Investigate findings' view.
TODO:

Map379 investigate findings content

---

packages/models/package.json
packages/models/src/event.js
packages/models/src/event/hash.js
packages/models/tests/unit/event.spec.js
packages/models/types/index.d.ts
yarn.lock

Add `Event.stableProperties`, which is meant to be a better foundation for an improved event/finding hash.
The concept is that all the data that identifies this event and is stable across AppMaps should be present here, and can be included in the hash. Volatile information such as SQL literals, parameter and return value literals, ... should be omitted.

feat: Stable properties

---

packages/scanner/src/rules/jobNotCancelled.ts
packages/scanner/test/scanner/jobNotCancelled.spec.ts

It's not correct to return a separate finding for each creation event.

fix: Return proper result for job-not-cancelled

---

packages/components/src/components/quickstart/QuickstartLayout.vue
packages/components/src/pages/install-guide/InvestigateFindings.vue

- remove unnecessary elements from CTA block
- add max-width for text to maintain readability
- switch out all our Zendesk links to instead link to Slack and push everyone there for tech support
- Remove "For details:" from view directing user to open Problems tab
Fixes https://github.com/applandinc/appmap-js/issues/681

layout updates

---

packages/scanner/src/check.ts
packages/scanner/src/ruleChecker.ts
packages/scanner/src/rules/secretInLog.ts
packages/scanner/src/rules/slowFunctionCall.ts
packages/scanner/src/scope/commandScope.ts
packages/scanner/test/scanner/rpcWithoutCircuitBreaker.spec.ts

If no events qualify as commands (@command, @job, or http_server_request), `command` scope will enumerate root events.
`command` scope also be comes the default.

feat: Command scope falls back on root events

---

packages/cli/src/cmds/record/recordContext.ts
packages/cli/tests/unit/record/test/recordContext.spec.ts

Telemetry events for the "record" subcommands will now correctly report
an AppMap count of 0. Previously, 0 AppMaps would cause the count to be
missing from the events.

fix: Recording metrics report 0 initial AppMaps

---

packages/cli/src/cmds/record/action/nameAppMap.ts
packages/cli/src/cmds/record/action/saveAppMap.ts
packages/cli/src/cmds/record/action/saveRecording.ts
packages/cli/tests/unit/record/record.remote.spec.ts

Make sure the telemetry event sent by "appmap record remote" reflects
the number of AppMaps created: 1 if the response for the DELETE request
contains data, 0 otherwise.
Fixes applandinc/board#127 .

fix: Improve telemetry for "appmap record remote"

---

.releaserc.js
.travis.yml
package.json
packages/cli/bin/build-native
packages/cli/package.json
packages/cli/src/cmds/open/serveAndOpenAppMap.ts
packages/scanner/bin/build-native

Build and release `scanner` and `appmap` binaries to GitHub Releases during semantic release.
Resolves #702

ci: Build and release pre-built binaries to GitHub Releases

---

packages/models/src/eventNavigator.js
packages/models/tests/unit/eventNavigator.spec.js

I'm not entirely sure what the previous code tried to do, but it yielded duplicate nodes in no particular order.

fix: Make EventNavigator.preceding() actually work

---

packages/cli/package.json
packages/cli/src/cmds/agentInstaller/install-agent.ts
packages/cli/src/cmds/errors.ts
packages/cli/src/lib/ticket/openTicket.ts
packages/cli/src/lib/ticket/zendesk.ts
packages/cli/tests/helper.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts
packages/cli/tests/unit/lib/openTicket.spec.ts
packages/cli/tests/unit/record/record.remote.spec.ts
yarn.lock

Fixes applandinc/board#118 .
Early Loom of the flow: https://www.loom.com/share/377a1350fab84bf5a23afb13e9b79038 .
Transcript with these changes:
```! Installation failed. View error details? Yes
An error occurred while running the command: pip install -r requirements.txt
The command exited with code 3
>  ERROR: Could not find an activated virtualenv (required).
! 
Would you like to provide your name and email address to open a support ticket?
The details of the error will be included automatically.
Yes
? Your name ajp
? Your email address apotteri.appland@gmail.com
{
"name": "@appland/telemetry/open-ticket:success",
"measurements": {},
"properties": {
"common.source": "@appland/telemetry",
"common.os": "darwin",
"common.platformversion": "21.6.0",
"common.arch": "x64", …
```

Give the user the option of creating a Zendesk ticket when install fails

---

packages/cli/src/cmds/agentInstaller/install-agent.ts

Don't prompt the user to create a ticket if install is successful.

fix: Don't prompt to create ticket on success

---

packages/cli/jest-setup.js
packages/cli/jest.config.js
packages/cli/src/cmds/record/recordContext.ts
packages/cli/src/cmds/record/state/testCasesComplete.ts
packages/cli/src/cmds/record/state/testCasesRunning.ts
packages/cli/src/cmds/record/testCaseRecording.ts
packages/cli/src/cmds/userInteraction.ts
packages/cli/src/lib/ticket/openTicket.ts
packages/cli/src/lib/ticket/zendesk.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts
packages/cli/tests/unit/agentInstall/statusCommand.spec.ts
packages/cli/tests/unit/fingerprint/fingerprintQueue.spec.ts
packages/cli/tests/unit/lib/openTicket.spec.ts
packages/cli/tests/unit/record/record.test.spec.ts
packages/cli/tests/unit/record/recordContext.spec.ts
packages/cli/tests/unit/record/testCaseRecording.spec.ts
packages/cli/tests/unit/record/testCasesComplete.spec.ts
packages/telemetry/telemetry.spec.ts

**Please don't merge this, it needs a rebase.**
Offer the user the chance to create a ticket when `record test` has test command failures, or fails to create AppMaps.
Fixes applandinc/board#128. Fixes applandinc/board#106.

Create a ticket when "record test" fails

---

packages/cli/src/fingerprint/fingerprintWatchCommand.js
packages/cli/tests/unit/fingerprint/fingerprintWatchCommand.spec.js

When running `index --watch`, all existing AppMaps will be considered for indexing. This differs from the previous behavior in which only AppMaps modified/created while the watcher was running would be indexed.

feat: Index in watch mode guarantees all AppMap indexes are up to date

---

packages/scanner/package.json
packages/scanner/src/cli/scan.ts
packages/scanner/src/cli/scan/scanner.ts
packages/scanner/src/cli/scan/singleScan.ts
packages/scanner/test/cli/scan.spec.ts
yarn.lock

When running scanner in a directory scan mode, an error processing
an appmap (eg. due to malformation or too large size) will no
longer crash the process preventing scanning other maps.
A warning will be printed instead and the process continues.
If all appmaps fail, the process still exits with an error status.
If at least one succeeds, the process exits with success.
Note this change doesn't affect the scenario where you explicitly
list files using --appmap-file argument. Any failure there will
still cause the process to fail.

fix: Skip bad files when running scanner on a directory

---

packages/cli/src/cli.ts
packages/cli/src/cmds/agentInstaller/install-agent.ts
packages/cli/src/cmds/record/makeRequest.ts
packages/cli/src/cmds/record/record.ts
packages/cli/src/cmds/record/recordContext.ts
packages/cli/src/cmds/record/remoteRecording.ts
packages/cli/src/cmds/record/state/agentNotAvailable.ts
packages/cli/src/cmds/record/state/initial.ts
packages/cli/src/cmds/record/state/testCasesComplete.ts
packages/cli/src/cmds/record/test/isAgentAvailable.ts
packages/cli/src/cmds/runCommand.ts
packages/cli/src/lib/ticket/openTicket.ts
packages/cli/src/lib/ticket/zendesk.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts
packages/cli/tests/unit/lib/openTicket.spec.ts
packages/cli/tests/unit/record/makeRequest.spec.ts
packages/cli/tests/unit/record/record.remote.spec.ts
packages/cli/tests/unit/record/record.spec.ts
packages/cli/tests/unit/record/record.test.spec.ts
packages/cli/tests/unit/record/testCasesComplete.spec.ts

asciinema of the current flow: https://asciinema.org/a/aBppjvZmhPPz1tQitrOOC7VKU . Note that the final big blob of text (after I enter the email address `ajp@example.com`) is debugging output, showing the details of the request that would have been submitted to Zendesk. The user won't see this, they'll just see the confirmation that the support request was created.
You are, of course, welcome to review these changes however you see fit. I found that turning off whitespace, and comparing them side by side, made it to understand them:
Fixes applandinc/board#130 .
Fixes #639 .

Offer to open a ticket when a remote recording request fails

---

packages/cli/src/cmds/agentInstaller/agentInstaller.ts
packages/cli/src/cmds/agentInstaller/agentInstallerProcedure.ts
packages/cli/src/cmds/agentInstaller/gradleInstaller.ts
packages/cli/src/cmds/agentInstaller/install-agent.ts
packages/cli/src/cmds/agentInstaller/javaScriptAgentInstaller.ts
packages/cli/src/cmds/agentInstaller/mavenInstaller.ts
packages/cli/src/cmds/agentInstaller/pythonAgentInstaller.ts
packages/cli/src/cmds/agentInstaller/rubyAgentInstaller.ts
packages/cli/src/cmds/errors.ts
packages/cli/tests/unit/agentInstall/agentInstaller.spec.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts

Fixes applandinc/board#139
Check dependencies before adding AppMap. The check varies with the package manager:
* `npm install --dry-run`
* `yarn install --immutable`
* `bundle check --dry-run`
* `pip install -r requirements.txt --dry-run`
* `poetry install --dry-run`
Maven and Gradle are less straightforward, so those will be a separate batch.

Check project dependencies before adding appmap

---

packages/client/package.json
packages/components/package.json
packages/scanner/src/cli/scan/watchScan.ts
packages/scanner/test/cli/scan.spec.ts
yarn.lock

Fixes #727 
Note: the pull request contains some unrelated drive-by warning fixes, plus a refactoring. Every change is in a separate commit.
If accepted, the reviewer is welcome to go ahead and do a rebase merge.

Scan initial files in `scan --watch`

---

packages/cli/src/cmds/record/action/guessTestCommands.ts

```
> node ../appmap-js/packages/cli/built/cli.js record test
In order to record test cases, you need to provide a command that I can use to run the tests. If your project has many test cases, enter a command that will run integration, functional, system or request tests, as opposed to unit tests. Don't worry about how long the tests will take to run, you will specify a maximum runtime in an upcoming step.
Here's a suggested test command for your project:
npx appmap-agent-js --recorder=mocha -- npx mocha
? Use this suggested test command? Yes
I've written this test command to your AppMap configuration file (appmap.yml). The next time you run this program, it will be used automatically. You can change it in the appmap.yml if you want to. You can also delete it, in which case you'll be …
```

feat: add guess test command for the js agent

---

packages/cli/src/cmds/record/record.ts
packages/cli/src/cmds/stats/stats.ts

Fixes https://github.com/getappmap/appmap-js/issues/749
Ran manually:
```
$ npm start stats -- /home/test/src/sample_app_6th_ed --limit 20
> @appland/appmap@3.41.0 start
> ts-node src/cli.ts stats /home/test/src/sample_app_6th_ed --limit 20
✔ Computing AppMap stats...
Largest AppMaps (which are bigger than 1024kb)
1.2MB tmp/appmap/minitest/Microposts_interface_micropost_interface.appmap.json
✔ Computing functions with highest AppMap overhead...
No "elapsed_instrumentation" data in the AppMaps.
would have sent telemetry !!!                                        <================ debugging statement
```
Ran from Record command:
```
$ rm -rf  /home/test/src/sample_app_6th_ed/tmp/appmap > /dev/null 2>&1; npm start record test -- -d /home/test/src/sample_app_6th_ed
> @appland/appmap@3.41.0 …
```

feat: Send telemetry for the Stats command only when it's called manually

---

packages/cli/src/fingerprint/fingerprintQueue.ts
packages/cli/src/fingerprint/fingerprintWatchCommand.js
packages/cli/src/fingerprint/fingerprintWatchCommand.ts
packages/cli/src/fingerprint/fingerprinter.ts
packages/cli/src/fingerprint/index.js
packages/cli/src/lib/eventAggregator.ts
packages/cli/src/lib/flattenMetadata.ts
packages/cli/src/lib/intersectMaps.ts
packages/cli/tests/unit/fingerprint/fingerprintWatchCommand.spec.ts
packages/cli/tests/unit/lib/eventAggregator.spec.ts
packages/models/types/index.d.ts

The telemetry data sent includes number of AppMaps seen and some common metadata about them. An event is not sent more often than once per second.
Note this only applies to watch mode. The intention is to let us see when our users are succeeding with AppMap creation, and as live indexing automatically happens when using IDEs, this solution avoids having to call home from every agent. Telemetry can also be easily disabled in the editors.
Example event:
```json
{
"name": "appmap:index",
"properties": {
"app": "appland/AppLand",
"client.name": "appmap",
"client.url": "https://github.com/applandinc/appmap-ruby",
"framework.rails": "5.2.4.2",
"framework.rspec": "3.9.1",
"labels": "api key, api",
"language.name": "ruby",
"language.version": "2.6.6",
"language.engine": "ruby",
"recorder.name": …
```

Send telemetry events on indexing

---

packages/scanner/src/cli/scan/watchScan.ts
packages/scanner/src/configuration/configurationProvider.ts

Fixes a corner case with latest changes.

fix: Use default configuration timestamp in scan --watch if none provided

---

packages/components/src/components/install-guide/ProjectPickerRow.vue
packages/components/src/components/install-guide/ProjectPickerTable.vue
packages/components/src/pages/InstallGuide.vue
packages/components/src/pages/install-guide/ProjectPicker.vue
packages/components/src/pages/install-guide/RecordAppMaps.vue
packages/components/src/stories/install-guide/RecordAppMaps.stories.js

This change:
- Adds a toggle for Python where recording by default is documented or not
- Fixes hover tooltips being cut off
- Fixes an issue where a project would be unselected if VSCode was still initializing
- Removes some dead code and resolves other non-user facing errors 
Resolves #476

appland.appmap 0.44.0-rc fixes

---

packages/cli/src/cli.ts
packages/cli/src/fingerprint/fingerprintWatchCommand.ts

Found via IntelliJ:
```sh
$ /home/db/dev/applandinc/appmap-intellij-plugin/build/idea-sandbox/system/tmp/appland-downloads/appmap/3.43.1/appmap-linux-x64 index --watch --appmap-dir /home/db/dev/applandinc/appmap-ruby/spec/fixtures/rails6_users_app    
TypeError: FingerprintWatchCommand is not a constructor
at Object.handler (/snapshot/appmap-js/packages/cli/built/cli.js:316:21)
at /snapshot/appmap-js/node_modules/yargs/build/index.cjs:1:9114
at j (/snapshot/appmap-js/node_modules/yargs/build/index.cjs:1:4993)
at M.applyMiddlewareAndGetResult (/snapshot/appmap-js/node_modules/yargs/build/index.cjs:1:9083)
at M.runCommand (/snapshot/appmap-js/node_modules/yargs/build/index.cjs:1:7268)
at Jt.[runYargsParserAndExecuteCommands] (/snapshot/appmap-js/node_modules/yargs/build/index.cjs:1:56059) …
```

fix: Fix a panic condition when indexing in watch mode

---

packages/cli/src/fingerprint/fingerprintWatchCommand.ts
packages/cli/src/fingerprint/globber.ts
packages/cli/tests/unit/fingerprint/fingerprinter.spec.ts

Instead of using chokidar polling mode, periodically rescan the directory with glob to find appmaps. This is more reliable and avoids many corner cases of chokidar.

fix: More reliable polling in index --watch

---

.travis.yml
packages/scanner/src/cli/scan/command.ts
packages/scanner/src/cli/scan/watchScan.ts
packages/scanner/test/cli/commands.spec.ts

Also, fix paths handling for windows.
Fixes #753 .

`scan --watch` works correctly even when the appmap dir doesn't initially exist

---

packages/cli/src/cmds/record/state/testCasesComplete.ts
packages/cli/tests/unit/record/testCasesComplete.spec.ts

When running `appmap record` if a test run failed a message was
shown suggesting no maps were created even if some, in fact, were.
We're not showing that message anymore (unless maps were indeed
not created).
Fixes #728

fix: Don't show a misleading message when test fails with AppMaps

---

packages/cli/src/cmds/record/state/testCasesComplete.ts
packages/cli/tests/unit/record/testCasesComplete.spec.ts

Fixes https://github.com/getappmap/appmap-js/issues/754

fix: Don't fail if there were no testcases in Ruby.

---

packages/client/src/appMap.ts
packages/client/test/appMap.create.spec.ts

This will be used by the VS Code extension (and is, in the latest RC).

feat: Add `public` flag to create AppMap

---

packages/cli/src/cmds/agentInstaller/agentProcedure.ts
packages/cli/tests/unit/agentInstall/TestAgentProcedure.ts
packages/cli/tests/unit/agentInstall/agentProcedure.spec.ts

Fixes https://github.com/getappmap/appmap-js/issues/770
It's not easy to write a testcase for this.
```
$ mkdir js-project
$ cd js-project
$ yarn init
(enter enter enter...)
$ yarn
$ npx @appland/appmap install
Installing AppMap agent for ....
? AppMap is about to be installed. Confirm the details below.
!!! Telemetry disabled !!!: true
Project type: yarn
Project directory: /home/test/tmp/js-project
Git remote: [git remote failed, fatal: not a git repository (or any of the parent directories): .git]
Is this correct? Yes
? An appmap.yml configuration file already exists. How should the conflict be resolved? Use existing
✔ Installing the AppMap agent...
⠋ Validating the AppMap agent...
Validating the AppMap agent...
✔ Validating the AppMap agent... …
```

fix: Don't crash in the installation if there were no validation errors.

---

packages/cli/src/cmds/agentInstaller/javaScriptAgentInstaller.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts

Fixes https://github.com/getappmap/appmap-js/issues/784
```
https://registry.npmjs.org/appmap-agent-js               doesn't exist.
https://registry.npmjs.org/@appland/appmap-agent-js              exists.
```
Before
```
$ npx appmap-agent-js init ~/src/sample_app_6th_ed/
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/appmap-agent-js - Not found
npm ERR! 404 
npm ERR! 404  'appmap-agent-js@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/test/.npm/_logs/2022-10-14T14_56_38_907Z-debug-0.log
```
After
```
$ npx @appland/appmap-agent-js init ~/src/sample_app_6th_ed/
Need to install the following …
```

fix: Install `@appland/appmap-agent-js`, not `appmap-agent-js`

---

packages/scanner/src/types.d.ts

Set to `any` which is suboptimal but at least doesn't cause dependents to break. It would be good to enable proper type checking for the options.

fix: Fix unresolved type in Rule.Options

---

packages/cli/src/cmds/agentInstaller/agentProcedure.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts

If validateProject fails to JSON.parse(stdout), print out the stdout that failed to be parsed and display an error message.
Fixes https://github.com/getappmap/board/issues/193.
This is basically https://github.com/getappmap/appmap-js/pull/772 rebased to integrate the recent `error` [fix](https://github.com/getappmap/appmap-js/pull/787).

feat: Don't crash if validateProject fails to JSON.parse(stdout)

---

packages/cli/src/cmds/record/action/guessTestCommands.ts

Normally, the user should have installed the js agent at this point. But we still see failures about https://registry.npmjs.org/appmap-agent-js not existing in telemetry. I'm not sure what to think about this.

refactor: add org name in guess test commands

---

packages/cli/src/utils.ts

Glob would raise an error while searching for AppMap files if it encountered a directory it could not read due to permission errors. By specifying `strict: false`, the errors will be ignored and the search will continue on.
Resolves #803

fix: Listing AppMap files will now ignore non-permissioned directories

---

packages/cli/src/cmds/record/record.ts
packages/cli/tests/unit/record/record.test.spec.ts

If the directory path supplied as input doesn't exist or isn't a directory, let the user know.
Fixes https://github.com/getappmap/board/issues/202

feat: When recording tests, don't crash if directory path is invalid.

---

packages/components/src/pages/InstallGuide.vue

The `appMapsRecorded` flag indicates the user has, at any point, recorded AppMaps. This doesn't guarantee that there are any AppMaps currently available as the user could have since deleted them. By looking at the AppMap count, this indicator is more reflective of the actual current state.

Modify the condition in which AppMaps are depicted as being successfully recorded

---

packages/cli/src/lib/ticket/openTicket.ts
packages/cli/src/lib/ticket/zendesk.ts
packages/cli/tests/unit/lib/openTicket.spec.ts

Zendesk requires the user's name when opening a ticket request. These changes prompt them for it before prompting for their email address.
Old prompt:
```
? Would you like to open a support request? Yes
? The AppMap team will respond to you by email.
Please provide your email address to open the support request: ajp@example.com
```
New prompt:
```
? Would you like to open a support request? Yes
The AppMap team will respond to you by email. Please provide your name and email address to open the support request:
? Your name ajp
? Your email address ajp@example.com
```
Fixes getappmap/board#207.

fix: prompt user for name to open a ticket

---

packages/cli/doc/appmap-agent-validate.md
packages/cli/package.json
packages/cli/src/cmds/agentInstaller/ValidationResult.ts
packages/cli/src/cmds/agentInstaller/agentInstallerProcedure.ts
packages/cli/src/cmds/agentInstaller/agentProcedure.ts
packages/cli/src/cmds/agentInstaller/agentStatusProcedure.ts
packages/cli/src/service/config/validator.ts
packages/cli/tests/unit/agentInstall/TestAgentProcedure.ts
packages/cli/tests/unit/agentInstall/agentInstallerProcedure.spec.ts
packages/cli/tests/unit/agentInstall/agentProcedure.spec.ts
packages/cli/tests/unit/agentInstall/agentStatusProcedure.spec.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts
yarn.lock

Our appmap-agent-validate protocol supports the notion of warnings, ie. messages from the validator that aren't fatal. 
These changes add support for this:
- don't fail the validation if validator only returns warnings,
- print any warnings when the relevant commands (ie. *install* and *status*) are executed.
This is needed for a proper fix for https://github.com/getappmap/appmap-ruby/issues/292
(Also, add the documentation for the protocol to the repository for easy reference (it used to be in an internal google doc).)

Allow and show warnings from agents

---

packages/cli/src/cmds/record/prompt/obtainTestCommands.ts
packages/cli/tests/unit/record/prompt/obtainTestCommands.spec.ts

Fixes https://github.com/getappmap/appmap-js/issues/802

fix: Don't run test commands that contain only whitespace

---

packages/cli/src/cmds/agentInstaller/agentInstallerProcedure.ts
packages/cli/src/cmds/agentInstaller/agentProcedure.ts
packages/cli/src/cmds/agentInstaller/types/state.ts
packages/cli/tests/unit/agentInstall/agentInstallerProcedure.spec.ts
packages/cli/tests/unit/agentInstall/agentProcedure.spec.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts

Add a prompt in the command-line installer that commits in Git any configuration files changed by appmap.
Addresses https://github.com/getappmap/board/issues/220
If the directory isn't a valid git repo, or if there's no valid `git` tool, the tool doesn't display this prompt.  There isn't any code that checks for the directory being valid or for git being present.  The calls to `git status -s` fail, the installer thinks nothing changed, and so it doesn't display the prompt.
Don't attempt to `git add appmap.yml` the first time the install runs.
Screenshots:
1) Installing in a directory that is a valid git repo
2) Installing in a directory that isn't a valid git repo. (I manually `rm -rf .git` in this dir.)
3) Installing in a sub-directory.
To test this:
```
git clone …
```

feat: Encourage users to commit their AppMap config.

---

packages/cli/src/cli.ts
packages/cli/src/cmds/openapi.ts
packages/cli/src/lib/eventAggregator.ts
packages/cli/tests/unit/fingerprint/fingerprintWatchCommand.spec.ts
packages/cli/tests/unit/fixtures/malformedHTTPServerRequest/ApplicationController_before_action_store_current_location_does_not_store_location_for_user_if_it_is_devise_controller.appmap.json
packages/cli/tests/unit/openapi.spec.ts
packages/cli/tests/unit/stats/stats.spec.ts
packages/openapi/src/rpcRequest.ts

HTTP server or client requests without path info should be ignored when generating OpenAPI. Verify this with a test using a wild AppMap.
See https://github.com/getappmap/appmap-js/pull/853/files#diff-e1ccded3fd99486c3c18cca624f1f45126b85e20a6383ae734e1ed7a01a78ff5R108
Fixes #845

fix: Ignore requests without path info

---

packages/models/package.json
packages/models/rollup.config.js
yarn.lock

Fixes #855 
Note there is more work to be done for robust support, so this is just a starting point:
- support typescript eslint,
- typecheck on linting,
- support ts-jest,
- maybe overhaul the build to remove rollup and use tsc or tsup directly.

Typescript in models

---

packages/cli/src/cmds/openapi.ts
packages/cli/tests/unit/openapi.spec.ts

Fixes an issue where absolute `--appmap-dir` paths would be appended to the current working directory, leading to an invalid path.
Resolves #860

fix: OpenAPI accepts either relative or absolute `--appmap-dir` paths

---

packages/components/src/pages/VsCodeExtension.vue

- Point the user towards the appmap.io documentation. 
- Update the Discord Link to point to Slack instead

Update the links shown when the AppMap has no data to display

---

packages/cli/src/cmds/stats/stats.ts

Saw this with @kgilpin and thought it needed a more informative error message.

fix: Show better error message if there's no elapsed_instrumentation data in the appmaps.

---

packages/cli/src/cmds/agentInstaller/pythonAgentInstaller.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts
packages/cli/tests/unit/agentInstall/python.spec.ts

**This must be merged after https://github.com/getappmap/appmap-python/pull/195**
`appmap-python` requires python 3, so invoke the interpreter as `python3`. Also, use `python3 -m` to run some commands, instead of relying on the user to have their PATH set correctly.
Fixes #839 . Fixes #840 .

fix: replace python with python3, use -m

---

packages/cli/src/cmds/agentInstaller/agentProcedure.ts

Addresses https://github.com/getappmap/board/issues/220

fix: Change copy in prompt and commit message used when configuring AppMap for a project.

---

.travis.yml
packages/cli/package.json
packages/cli/webpack.config.js
packages/models/src/hashBuilder.js
yarn.lock

@appmap/models package is also used in the browser. Using node:crypto requires using crypto-browserify implementation which bloats the build unnecessarily. We're already using crypto-js in other places, it can be used instead.
This improves compilation time and size of the appmap.html bundle in cli by a third:
```sh-session
$ yarn build # before
asset main.js.map 3.88 MiB [emitted] [dev] (auxiliary name: main)
asset appmap.html 1.23 MiB [emitted] [big]
asset main.js.LICENSE.txt 607 bytes [emitted]
orphan modules 278 KiB [orphan] 197 modules
runtime modules 1.25 KiB 6 modules
modules by path ../../node_modules/ 1.85 MiB
javascript modules 1.83 MiB 497 modules
json modules 12.7 KiB 6 modules
modules by path ./ 9.43 KiB
modules by path ./node_modules/style-loader/dist/runtime/*.js 5.75 KiB 6 …
```

Don't use node:crypto in @appmap/models

---

packages/cli/src/fingerprint/fingerprintWatchCommand.ts
packages/cli/src/fingerprint/globber.ts
packages/cli/tests/unit/fingerprint/fingerprintWatchCommand.spec.ts

If the user does not have permissions to read a directory under `--appmap-dir`, an `EPERM`/`EACCES` error would panic the process (even in `--watch` mode).
Instead, these errors will be ignored and we'll continue scanning what we can.
I wasn't sure of an easy way to test an `EPERM` without involving other OS users, so I've omitted the test for now. Behavior should otherwise be the same.
Resolves #880

fix: Prevent EPERM/EACCES errors while watching AppMaps if a directory cannot be read

---

packages/cli/src/cli.ts
packages/cli/src/cmds/agentInstaller/agentInstaller.ts
packages/cli/src/cmds/agentInstaller/agentInstallerProcedure.ts
packages/cli/src/cmds/agentInstaller/gradleInstaller.ts
packages/cli/src/cmds/agentInstaller/javaScriptAgentInstaller.ts
packages/cli/src/cmds/agentInstaller/mavenInstaller.ts
packages/cli/src/cmds/agentInstaller/pythonAgentInstaller.ts
packages/cli/src/cmds/agentInstaller/rubyAgentInstaller.ts
packages/cli/src/cmds/openapi.ts
packages/cli/tests/unit/agentInstall/TestAgentProcedure.ts
packages/cli/tests/unit/agentInstall/agentInstaller.spec.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts

Include `appmap_dir` and `language` in the generated _appmap.yml_ file.
If the _appmap.yml_ does not contain these settings, the installer will add them on a subsequent run.
https://asciinema.org/a/5ZFuGNXeBxGPPQQlUO82or2Z4

feat: appmap_dir and language in appmap.yml

---

packages/cli/src/fingerprint/fingerprintWatchCommand.ts
packages/cli/tests/unit/fingerprint/fingerprintWatchCommand.spec.ts

When the indexer processes an appmap_dir that has more files than the OS limit for watching files, FSWatch raises an ENOSPC error.  Catch this specific type of ENOSPC error and disable file watching.  File changes continue to be detected through file polling.
Output of manual test. After disabling file watching, file polling continues to run.
Fixes https://github.com/getappmap/appmap-js/issues/894
If the reason for watching too many files was that the directory monitored wasn't precisely the `appmap_dir` but something more general, like `.` monitoring two parent directories up, then saving the `appmap_dir` in `appmap.yml` through [this pr](https://github.com/getappmap/appmap-js/pull/896) may be enough to make this ENOSPC error disappear without this fix.
This fix should still be applied …

fix: Disable file watching on "ENOSPC: System limit for number of file watchers reached" error

---

packages/openapi/src/method.ts
packages/openapi/src/path.ts
packages/openapi/src/rpcRequest.ts
packages/openapi/test/data/Users_signup_invalid_signup_information.appmap.json
packages/openapi/test/openapi.spec.ts
packages/openapi/test/response.spec.ts

Code example:
```
class AccountActivationsController < ApplicationController
def edit
response.headers['X-OpenAPI-Summary'] = 'Activate the account of an existing user'
```
Generated OpenAPI:
```
/account_activations/{id}/edit:
get:
responses:
'302':
content: {}
description: Found
parameters:
- name: email
in: query
schema:
type: string
- name: id
in: path
schema:
type: string
required: true
summary: Activate the account of an existing user
```

feat: Populate openapi path.summary from x-openapi-summary header

---

packages/cli/src/fingerprint/fingerprintWatchCommand.ts
packages/scanner/src/cli/scan/watchScan.ts
packages/scanner/test/cli/scan.spec.ts

Before this change, running the scanner with a directory that contains many files crashes with an `ENOSPC` error
After this change, the `ENOSPC` error is captured so the scanner doesn't crash and file watching is disabled.
Send a `scan:watcher_error:enospc` event.  To stay consistent also send a `index:watcher_error:enospc` in the scanner.
Fixes https://github.com/getappmap/appmap-js/issues/904.
This is similar to https://github.com/getappmap/appmap-js/pull/895.

fix: Don't let scanner crash on "ENOSPC: System limit for number of file watchers reached" error

---

packages/scanner/src/cli/scan/watchScan.ts
packages/scanner/test/cli/scan.spec.ts

Before this change, the scanner crashed when it encountered a directory that didn't have read permission.
After this change, the scanner doesn't crash.
This crash is probably caused by using a general path for `appmap_dir` instead of the expected `tmp/appmap`, along with the scanner not handling this exception.  The fix is to set `ignorePermissionErrors: true` in chokidar's options.
There's a testcase.  When `ignorePermissionErrors` is commented out the testcase fails, as expected.
Fixes https://github.com/getappmap/appmap-js/issues/899.

fix: Don't let scanner crash on `EACCES: permission denied` error

---

packages/cli/src/fingerprint/fingerprintWatchCommand.ts
packages/cli/tests/unit/fingerprint/fingerprintWatchCommand.spec.ts

Attempts to fix https://github.com/getappmap/appmap-js/issues/897. Created from branch `sw/disable_watching_on_ENOSPC_error`
This error is an exception thrown by chokidar while file watching.
I wasn't able to reproduce this error.  I created symlinks and deleted them programmatically when the queue processes the file but this produced an ENOENT error.
```
File /home/test/tmp/too_many_open_files/minitest/Static_pages_controller_should_get_help.appmap.json does not exist or is not a file.
Deleted File successfully.
[Error: ENOENT: no such file or directory, lstat '/home/test/tmp/too_many_open_files/minitest/Static_pages_controller_should_get_home.appmap.json'] {
errno: -2,
code: 'ENOENT',
syscall: 'lstat',
path: '/home/test/tmp/too_many_open_files/minitest/Static_pages_controller_should_get_ …
```

fix: Don't crash indexer on an "UNKNOWN: unknown error, lstat" error

---

packages/cli/src/fingerprint/fingerprintWatchCommand.ts
packages/cli/tests/unit/fingerprint/fingerprintWatchCommand.spec.ts
packages/scanner/src/cli/scan/watchScan.ts
packages/scanner/test/cli/scan.spec.ts

The original plan to address this was to increase the number of open files limit.  It didn't work on Windows.
To address this problem on Windows, and as a side effect address it in all operating systems, catch the `EMFILE` error.
It may be possible to get the [original pr](https://github.com/getappmap/appmap-js/pull/893) to compile for all operating systems, just as [it did ](https://app.travis-ci.com/github/getappmap/appmap-js/jobs/591181921) when it was first opened at https://github.com/getappmap/appmap-js/pull/893/commits/2ab7dd5ac182829cd2a4423c4e518eb376191aa4, but have it not call `setrlimit` on Windows.
This happens in the [indexer](https://github.com/getappmap/appmap-js/issues/881) as a `ProcessFailure` in the [logs](https://portal.azure.com/#view/Microsoft_OperationsManagementSui …

fix: Don't let indexer crash on `EMFILE: too many open files` error

---

packages/cli/src/lib/flattenMetadata.ts
packages/cli/src/lib/repositoryInfo.ts

```
$ git remote set-url origin git@github.com:land-of-apps/sample_app_6th_ed.git
```
```json
{
"name": "@appland/appmap/appmap:index",
"measurements": {
"appmap.cli.appmaps": 67
},
"properties": {
"common.source": "@appland/appmap",
"common.os": "darwin",
"common.platformversion": "21.5.0",
"common.arch": "arm64",
"appmap.cli.machineId": "e30b0f8f68963ac14e85088b17d1ff22b94607cc12f59105884c155625ba7321",
"appmap.cli.sessionId": "00cb37ff563bd6ce4fc07a326df1a3238f3ca941e5c4ff3dd0c2d51d4284e7c9",
"appmap.cli.version": "3.55.1",
"appmap.cli.args": "/Users/kevin/source/getappmap/appmap-js/packages/cli/built/cli.js index --watch -d /Users/kevin/source/land-of-apps/sample_app_6th_ed",
"appmap.cli.app": "sample_app_6th_ed",
"appmap.cli.client.name": "appmap",
"appmap.cli.client.url": …
```

feat: Emit git URL in appmap:index telemetry

---

packages/diagrams/src/componentDiagram/index.js

If an external service has once child, do not expand the service into its route. There's no rendering support for that type. This change also prevents future issues of this type.

fix: Don't attempt to render external service routes

---

packages/components/package.json
packages/diagrams/package.json
yarn.lock

Ensure that @appland/models version ^1.23.0 is used in @appland/components.

fix: bump @appland dependency versions

---

packages/cli/src/cmds/record/action/guessTestCommands.ts

The default js test command seems to record 0 appmaps in many cases. It  could be that there is no tests or that the project is not using node to  run tests. Also, the command is confusing because it mixes  `--recorder=process` with a test command whereas we want to push ad-hoc  recorders for tests.

feat: remove fonky default test command

---

packages/scanner/src/rules/updateInGetRequest.ts
packages/scanner/test/scanner/updateInGetRequest.spec.ts
packages/scanner/test/support/describeRule.ts
packages/scanner/test/support/testMap.ts
packages/scanner/test/support/testRule.ts

The rule was missing a correct `enumerateScope` setting.

fix: Fix a bug preventing 'Update in GET request' rule from working

---

packages/scanner/src/cli/scan/watchScan.ts
packages/scanner/src/lib/isAncestorPath.ts
packages/scanner/test/lib/isAncestorPath.spec.ts

Fix the problem where on Windows, if the appmap directory was located on a different drive, scan --watch command would erronously watch the current directory instead.

fix: Scan-watching directories on other than the current drive

---

packages/cli/src/cmds/agentInstaller/pythonAgentInstaller.ts
packages/cli/tests/unit/agentInstall/python.spec.ts

When there's only a single requirements.txt file in a Python project make sure to use its name instead of assuming it's always 'requirements.txt'.
Also, change the tests for this code to only excercise this code path instead of trying to call out to python, which was slow and unreliable.

fix: Allow non-standard requirements.txt names

---

packages/components/src/pages/AnalysisFindings.vue

Closes #947 
- Change `SUMMARY` to `OVERVIEW`
- Change `Finding Overview` to `Finding Impact Categories`

Update subheadings on Overview webview

---

packages/cli/src/cmds/openapi.ts
packages/cli/tests/unit/openapi.spec.ts
packages/scanner/src/report/scanResults.ts
packages/telemetry/telemetry.spec.ts
packages/telemetry/telemetry.ts

Add an option to send environment variable names in telemetry.
Include environment variable names in scan completion events.
Send a telemetry message when openapi CLI command is invoked.
Include environment variable names.

feat: Env var telemetry

---

packages/components/.storybook/run.js
packages/components/tests/e2e/specs/vsCodeExtension.spec.js

Fixes #953 
Prior to this change, test failures in `packages/components` were not causing the build to fail. Because of this we've had one test that's been failing for a few months and no one noticed.
For example, this build passed even though 8 tests failed:
Solution from [this SO post](https://stackoverflow.com/a/61320225).

fix: run components tests in ci

---

packages/cli/src/cmds/openapi.ts
packages/openapi/src/model.ts
packages/openapi/test/model.spec.ts

Before this change, `basePath` produced paths that were blank like
```
requestPath (/locale/{locale})/api/users/{id} produced 
requestPath (/locale/{locale})/api/readinglist produced 
```
After this change, `basePath` produces paths like
```
requestPath (/locale/{locale})/api/users/{id} produced (/locale/{locale})/api/users/{id}
requestPath (/locale/{locale})/api/readinglist produced (/locale/{locale})/api/readinglist
```
With this change the [`openapi.yml`](https://github.com/forem/forem/compare/main...symwell:forem:sw/use_appmap_to_create_openapi_doc?expand=1#diff-5016bdc926b6c0f649f363739d09159a1db664aae19a08fa6b38b03406f040dc) file for Forem was generated with many paths instead of a path named `''`. `openapi.yml` contains all 42 API calls that were found in the AppMap files.
I didn't …

fix: Fix basePath to not return '' when there's ( and )

---

packages/cli/src/fingerprint/index.js
packages/cli/src/utils.ts
packages/models/src/event.js
packages/models/tests/unit/event.spec.js
packages/scanner/src/rules/lib/util.ts
packages/sequence-diagram/package.json
packages/sequence-diagram/src/buildDiagram.ts
packages/sequence-diagram/src/types.ts

Handle missing `returnEvent` a bit better.
Accept `status` or `status_code` because there still seem to be places where the wrong one occurs.

feat: Sequence diagram model updates

---

packages/components/src/components/Pending.vue
packages/components/src/components/install-guide/ProjectPickerRow.vue
packages/components/src/components/quickstart/QuickstartLayout.vue
packages/components/src/pages/install-guide/InvestigateFindings.vue
packages/components/src/pages/install-guide/RecordAppMaps.vue

Closes #976 
Update styling of success messages so they are more prominent

success-message styling for recording appmaps

---

packages/cli/src/fingerprint/fingerprinter.ts
packages/cli/tests/unit/fingerprint/canonicalize.spec.js
packages/cli/tests/unit/fixtures/ruby/canonicalize/revoke_api_key.update.json
packages/models/src/appMapBuilder/index.js
packages/models/src/event.js
packages/models/src/util.js
packages/models/tests/unit/appMap.spec.js
packages/models/tests/unit/event.spec.js
packages/models/tests/unit/fixtures/many_requests_scenario.json

This fixes two cases. First, event properties would not always be serialized when the value was an object. Only in cases where the object contained an Array or a Set would it have been serialized. Second, `http_server_response.status_code` was being re-written to `http_server_response.status`. This likely wasn't resulting in any bugs, but would change the contents of an AppMap after serialization occurred. `status` and `status_code` can now be safely interchanged for backwards compatibility reasons in case anything downstream depends on one or the other.

fix: Prevent data from being dropped during serialization

---

packages/cli/package.json
yarn.lock

`^1` works as a JS dependency, but a binary must be built with the correct version constraints as well, so these may as well be more tightly constrained to their minimum version so we can create releases for version bumps. Otherwise there's no way for an upstream fix to propagate to a binary release.

fix: Bump @appland/models to v1.23.2

---

packages/components/src/components/DetailsSearch.vue
packages/components/src/components/Tab.vue
packages/components/src/components/TabButton.vue
packages/components/src/components/Tabs.vue
packages/components/src/pages/VsCodeExtension.vue

Fixes #988 
This is the first of two PRs to help better understand user behavior. The follow-up PR is [here](https://github.com/getappmap/vscode-appland/pull/609).
This PR causes the frontend to emit events so we can collect telemetry about how users interact with an AppMap:
- When a user clicks on the Filter button
- When a user clicks on the Reset button
- When a user focuses on the search bar
- When a user clicks on a list item in the sidebar
- When a user switches view types by using the tabs
**NOTES**
- There was already an event that was emitted when a user clicked on the Reset button [here](https://github.com/getappmap/appmap-js/blob/main/packages/components/src/pages/VsCodeExtension.vue#L1012), but it was also triggered when clearing the selection in the sidebar, so I made a new …

Telemetry to better understand sign in

---

packages/models/src/codeObject.js
packages/models/tests/unit/appMap.spec.js
packages/models/types/index.d.ts
packages/scanner/src/ruleChecker.ts

If a CodeObject's location is empty, it'll be omitted upon serialization. This means that if an AppMap was serialized, saved out and loaded again, access to `data.location` would result in an undefined value. Instead of returning `undefined`, return an empty string.
This unblocks https://github.com/getappmap/vscode-appland/pull/606. A test case uses a Python AppMap which contains an empty location, resulting in failures after it's indexed.

fix: `CodeObject#location` may be `undefined`

---

packages/cli/package.json
packages/scanner/bin/schema.ts
yarn.lock

fixes https://github.com/getappmap/appmap-js/issues/998
I don't understand how this is only noticed now:
- `packages/cli/package.json` did not have a `@appland/client` dependency since at least edea424c8ad533118e23c6e983322ce44932b0c8 (3.50.0)
- `packages/cli/src/cmds/upload.ts` did have `import { AppMap, loadConfiguration, Mapset } from '@appland/client';` since its creation 7f83aa52890c86c604acb1233ca1b8b21dd74b69
Maybe it would be a good idea to invest in some e2e testing so that it does not happen in the future.
**EDIT `upload.ts` was only recently added, please disregard the above**

fix: add missing @appland/client dependency

---

packages/models/types/index.d.ts
packages/openapi/src/appmap/index.ts
packages/openapi/src/appmap/propertiesParserV1.ts
packages/openapi/src/appmap/propertiesParserV2.ts
packages/openapi/src/method.ts
packages/openapi/src/schemaInferrer.ts
packages/openapi/src/util.ts
packages/openapi/test/data/examples/appmap-v1.10.0.yml
packages/openapi/test/data/examples/appmap-v1.9.0.yml
packages/openapi/test/data/examples/deep-merge.yml
packages/openapi/test/data/examples/expected/deep-merge.yml
packages/openapi/test/data/http_server_response_with_object_list.yaml
packages/openapi/test/model.spec.ts
packages/openapi/test/openapi.spec.ts
packages/openapi/test/propertiesParser.spec.ts
packages/openapi/test/response.spec.ts
packages/openapi/test/schemaInferrer.spec.ts
packages/openapi/tsconfig.json
packages/sequence-diagram/src/buildDiagram.ts
packages/sequence-diagram/tests/fixtures/app/tmp/appmap/show_user.sequence.uml
packages/sequence-diagram/tests/fixtures/sequenceDiagrams/userFoundVsNotFound.sequence.uml

This PR adds support for AppMaps which include the following change to the specification: https://github.com/getappmap/appmap/pull/36
I've included some notes at the bottom. I'd also like to increase the test coverage a bit more before merging.
Here's an example before/after:
```yaml
/api/appmaps:
get:
responses:
'200':
content:
application/json:
schema:
type: array
items:
type: object
properties:
code_objects:
type: array
items: {}
labels:
type: array
items: {}
mapset_id:
type: integer
metadata:
type: object
properties:
feature:
type: string
git:
type: object
labels:
type: array
items: {}
language:
type: object
name:
type: string
scenario_uuid:
type: string
description: OK
```
After:
```yaml
/api/appmaps:
get:
responses:
'200':
content:
application/json:
schema:
type: array
items:
type: …
```

OpenAPI: Describe and merge non-object array types

---

packages/components/src/components/DetailsPanelExternalService.vue
packages/components/src/components/DetailsPanelHeader.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/e2e/specs/appmap/sidebar.spec.js

Seq diagram bug fixes

---

packages/components/src/components/Tabs.vue

Prevent tabs from disappearing

---

ci/make-smoke-package-json.mjs
smoketest.sh

For some reason our smoke test didn't catch new missing dependency of cli on the client. I've realized yarn doesn't always use the correct packages installing files when resolutions include relative path. Changing the smoke test to instead use absolute paths seems to resolve the issue and allow the test to catch it.
Fixes #1002

test: Improved smoke test

---

packages/scanner/src/cli/scan/watchScan.ts

A tiny addition: I noticed when a scan fails for some file in watch scanning mode, the user is not notified. With this change, a warning is shown.

feat: Show a warning when watch scanning fails

---

packages/components/src/components/sequence/Actor.vue
packages/components/src/components/sequence/CallAction.vue

Fixes #1019 
Style the selected elements in Sequence diagrams
TODO: style selected elements in Sequence Diff

Selected element styling

---

.travis.yml

Building some packages requires dependencies to be built first. Chromatic only runs build on the packages that changes, which can lead to a build failure if the dependencies haven't been changed too.

ci: Do a full build before chromatic release

---

packages/cli/src/cmds/openapi.ts
packages/cli/src/cmds/upload.ts
packages/cli/src/fingerprint/fingerprintWatchCommand.ts
packages/cli/tests/unit/fingerprint/fingerprintWatchCommand.spec.ts
packages/scanner/jest.config.js
packages/scanner/src/cli/scan/singleScan.ts
packages/scanner/src/cli/scan/watchScan.ts
packages/scanner/src/cli/scan/watchScanTelemetry.ts
packages/scanner/src/report/scanResults.ts
packages/scanner/test/cli/commands.spec.ts
packages/scanner/test/cli/scan.spec.ts
packages/scanner/test/cli/watchScanTelemetry.spec.ts
packages/scanner/test/setup.ts
packages/scanner/test/util.ts
packages/telemetry/telemetry.spec.ts
packages/telemetry/telemetry.ts

This will count the number of unique contributors within a repository. The API is safe to call in any context, returning `0` if an error occurs (e.g. `git` is missing, not a repository, etc.).

fix: Include git contributor count in OpenAPI event

---

packages/components/src/components/sequence/CallAction.vue
packages/components/src/components/sequence/CallLabel.vue

The existing color for selected elements in the sequence diagram was subtle, but made it hard to find the element if scrolling around the map. Updated to have a brighter color for easier navigation. 
Closes #1040

Improved highlighting for selected sequence diagram elements

---

packages/telemetry/telemetry.spec.ts
packages/telemetry/telemetry.ts

Recent additions to telemetry cause processes to hang if git is not found. This fixes the problem.

Don't hang without git

---

packages/components/src/assets/sequence-action-arrow.svg

The arrowheads in the sequence diagrams look broken because the tip of the arrow is thinner than the line of the arrow. Update the arrowhead SVG to have squared-off edges (2px to match line width), so it doesn't look broken.
Fixes #1054

Improved arrowhead alignment

---

packages/components/src/components/sequence/Actor.vue
packages/components/src/components/sequence/CallAction.vue
packages/components/src/components/sequence/ReturnAction.vue

When sequence diagram arrows go from right to left, the border-radius is inconsistent and looks broken. Update so the selection looks clean from L -> R, as well as from R -> L
Fixes #1062

fix inconsistent border-radius for selected diagram elements

---

packages/components/cypress.config.ts
packages/components/cypress.json
packages/components/package.json
packages/components/tests/e2e/specs/appmap/componentDiagram.spec.js
packages/components/tests/e2e/specs/appmap/sequenceDiagram.spec.js
yarn.lock

Fix broken sequence diagram test

---

packages/components/cypress.config.ts
packages/components/tests/e2e/specs/appmap/sequenceDiagram.spec.js

Fixes #1099 
This reverts commit abc9ba1136f3e42551024bd465d23450d217148e.
This test just failed in CI again, so it seems that it wasn't fixed after all.

Revert "test: fix broken sequence diagram test"

---

packages/cli/src/cmds/prune/prune.ts
packages/cli/src/cmds/prune/pruneAppMap.ts
packages/cli/src/lib/handleWorkingDirectory.ts
packages/cli/tests/unit/prune.spec.ts
packages/components/src/pages/VsCodeExtension.vue
packages/models/src/appMapBuilder/index.js
packages/models/src/appMapFilter.js
packages/models/src/util.js
packages/models/types/index.d.ts

Fixes #1104 
Alter the `prune` CLI command:
**Example:**
command: 
```
node built/cli.js prune tests/unit/fixtures/stats/appmap/Microposts_interface_micropost_interface.appmap.json --format json -s 500kb
```
output:
```
{
"exclusions": [
"function:logger/Logger::LogDevice#write",
"function:actionpack/ActionDispatch::Request::Session#[]",
"function:activerecord/ActiveRecord::Relation#records",
"function:actionview/ActionView::Resolver#find_all",
"function:app/helpers/UsersHelper#gravatar_for"
]
}
```
**Example (with `--filter`):**
The filter for the command below is:
```
{
hideName: [
function:logger/Logger::LogDevice#write
function:activerecord/ActiveRecord::Relation#records
function:actionpack/ActionDispatch::Request::Session#[]
]
}
```
command:
```
node built/cli.js prune --filter …
```

Updates to handle large appmaps

---

packages/cli/package.json
packages/cli/src/cmds/stats/stats.ts
packages/components/package.json
yarn.lock

Robust appmap locating

---

packages/components/src/components/SignIn.vue
packages/components/src/components/Tab.vue
packages/components/src/components/TabButton.vue
packages/components/src/components/Tabs.vue
packages/components/src/pages/VsCodeExtension.vue

Fixes getappmap/board#261
**Sign-in before:**
**Sign-in after:**
**Sequence diagram tab before:**
**Sequence diagram tab after:**

Visual updates

---

packages/components/src/assets/stats-icon.svg
packages/components/src/pages/VsCodeExtension.vue

Add UI tooltips for all map controls. (Filter & Reload were missing tool tips). Closes #1124

tooltip for map controls

---

packages/models/src/appMapBuilder/index.js

Fixes #1150 
Prevent an error where call events that cannot be converted to a code object cause the prune command to fail. This change keeps any call event that cannot be found in the class map.
Before this change, pruning this file failed: https://github.com/getappmap/board/files/11126270/21-Mb-appmap.json.zip

More robust pruning

---

packages/cli/package.json
packages/cli/src/cmds/stats/directory/statsForMap.ts
packages/components/package.json
yarn.lock

Fixes #1151 
Before this change, the stats command required that the `classMap` field preceded the `events` field. For example, this would work:
```
{
"classMap": ...,
"events": ...
}
```
However, this would result in an error:
```
{
"events": ...,
"classMap": ...
}
```
This change also pulls in the latest version of `@appland/models` to fix [this issue](https://github.com/getappmap/appmap-js/pull/1149) in the next release of `@appland/appmap`.

Fix CLI bugs for handling large maps

---

packages/models/src/appMapFilter.js
packages/models/tests/unit/appMapFilter.spec.js

If the AppMap contains no HTTP server requests, limitRootEvents should be a nop.

fix: limitRootEvents filter should be a nop

---

packages/components/src/components/SignIn.vue

Explicitly define font-family. Fonts in JetBrains were rendered incorrectly. Closes #1160 
JetBrains:
Font-family defined (local Storybook):

define font-family

---

packages/sequence-diagram/src/specification.ts
packages/sequence-diagram/tests/unit/sequenceDiagram.spec.ts

Previously, the `expand` option would fail to include the child classes of the expanded package in the list of actors.

Sequence diagram `expand` option includes child classes in `actors`

---

packages/components/package.json
packages/components/src/assets/collapse-icon.svg
packages/components/src/assets/expand-icon.svg
packages/components/src/components/DiagramSequence.vue
packages/components/src/components/sequence/Actor.vue
packages/components/src/components/sequence/LoopAction.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/src/scss/_variables.scss
packages/components/src/store/vsCode.js
packages/components/tests/e2e/specs/appmap/sequenceDiagram.spec.js
yarn.lock

Fixes #1166
For some reason the Travis build isn't attached anymore, but you can find it [here](https://app.travis-ci.com/github/getappmap/appmap-js/builds/262948442).
[Here](https://www.chromatic.com/component?appId=5fe18baf66f2280021e634d0&csfId=pages-vs-code--extension-with-default-sequence-view&buildNumber=2186&k=645bdb3bb4699530485605ba-1200-interactive-true&h=10&b=-5) is the interactive chromatic build where you can try out this feature.

User can expand sequence diagram packages to classes

---

packages/components/src/components/DetailsPanelFilters.vue
packages/components/src/components/FilterMenu.vue
packages/components/src/components/sequence/Actor.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/src/store/vsCode.js
packages/components/tests/unit/VsCodeExtension.spec.js

Make the filter menu into its own Vue component

---

packages/models/src/serialize.js
packages/models/tests/unit/serialize.spec.js

Fixes #1185 
This needs to be merged and a new version of `models` needs to be released before the [`Hide external code` filter option PR](https://github.com/getappmap/appmap-js/pull/1178) can be merged and released.
This PR fixes the `serialize` and `deserialize` functions in `models` that was not working with the `hideExternalPaths` declutter field.

Serialize and deserialize work correctly for hide external

---

packages/components/package.json
packages/components/src/components/FilterMenu.vue
packages/components/tests/e2e/specs/appmap/viewFilter.spec.js
yarn.lock

Fixes #1175 
Adds the ability for users to filter external code:
This option only appears in Ruby and JavaScript maps because we're only filtering out external code in `vendor` and `node_modules` at the moment.

Users can filter external code

---

packages/cli/src/cli.ts
packages/cli/src/cmds/openapi.ts
packages/cli/src/cmds/sequenceDiagramDiff.ts
packages/cli/src/depends.js
packages/cli/src/fingerprint/fingerprintQueue.ts
packages/cli/src/sequenceDiagram/buildDiagrams.ts
packages/cli/src/utils.ts
packages/cli/tests/unit/depends.spec.ts
packages/cli/tests/unit/queue.spec.ts
packages/scanner/src/cli/upload.ts

* Optimize target file enumeration
* Cache file modified times
* Remove the most verbose logging
* Remove source locations that are blank
Before optimization:
```
node ./built/cli.js depends -d ~/source/land-of-apps/forem > forem.log  11.41s user 6.40s system 169% cpu 10.537 total
```
After optimization:
```
node ./built/cli.js depends -d ~/source/land-of-apps/forem > forem.log  3.86s user 1.59s system 127% cpu 4.296 total
```

feat: 'depends' performance

---

packages/models/src/serialize.js
packages/models/tests/unit/serialize.spec.js

Fixes #1194 
These changes are needed prior to merging [this PR](https://github.com/getappmap/appmap-js/pull/1186).

Add explicit option to serialize

---

packages/cli/package.json
packages/components/package.json
packages/components/src/components/FilterMenu.vue
packages/components/src/components/PopperMenu.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/src/store/vsCode.js
packages/components/src/stories/ViewFilterMenu.stories.js
packages/components/src/stories/VsCodeExtension.stories.js
packages/components/src/stories/data/saved_filters.js
packages/components/tests/e2e/specs/appmap/viewFilter.spec.js
packages/components/tests/unit/filterMenu.spec.js
packages/openapi/package.json
packages/scanner/package.json
packages/sequence-diagram/package.json
yarn.lock

Fixes #1187 
This feature allows users to save filter settings. Users can save the filter settings with a name and then select from previously saved filter settings from a dropdown menu in the filters menu:
Because the saved filters need to propagate across AppMaps in the workspace, the VS Code extension handles some of the logic for this feature (and the JetBrains plugin will have to do the same in the future). Therefore, much of the functionality is not present in Storybook.
Features:
There was some discussion about including an option to save a new filter as the default filter. I did a quick mock-up of that and I didn't like how it came out, so if we want to add this feature, we'll need to come up with a better design.

User can bookmark filter settings

---

packages/diagrams/package.json
packages/diagrams/src/helpers/container/index.js
packages/diagrams/src/helpers/momentum/index.js
yarn.lock

Duplicate d3-selection causes issues. Let's use the most recent d3-selection version . As a bonus we get rid of the ugly global d3Event.
Fixes: https://github.com/getappmap/appmap-js/issues/1206

fix: update d3 dependencies to dedup d3-selection

---

packages/cli/package.json
packages/components/package.json
yarn.lock

Update `@appland/diagrams` to version 1.7.0 to fix the issues with duplicate versions of `d3-selection`.

Update diagrams to 1.7.0

---

packages/components/src/components/install-guide/ProjectPickerRow.vue
packages/components/src/components/install-guide/install-instructions/JavaScript.vue
packages/components/src/components/install-guide/install-instructions/Python.vue
packages/components/src/components/install-guide/install-instructions/Ruby.vue

Adds a header, spacing, and code formatting to the installer views...
Before
After

formatting for install instructions

---

packages/components/src/components/install-guide/record-instructions/Python.vue
packages/components/src/components/quickstart/QuickstartLayout.vue
packages/components/src/pages/install-guide/InvestigateFindings.vue

- Removes a sentence from the Record AppMaps page for Python
- Removes the framework specific name from the instructions, because commands for both options are always present
- Updates text to include the work 'Then' to follow up on the 'First..' step and provide a sense of flow
Previous:
Updated:
-Centers the 'Generate OpenAPI' button to be consistent with other primary actions in the flow.
- Removes the word 'Success!' from the Runtime Analysis page because it doesn't make sense in the context of Runtime Analysis and is dissonant with the status messaging.

Minor updates to the onboarding text

---

packages/scanner/package.json
packages/scanner/src/integration/github/commitStatus.ts
yarn.lock

Octokat hasn't been updated in five years and it's using a dependency with a known security issue:
https://github.com/advisories/GHSA-r683-j2x4-v87g

Replace octokat with octokit

---

packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/unit/VsCodeExtension.spec.js

Fixes #1247 
Previously, the VS Code extension was creating the default AppMap filter, but to make the filter feature compatible with JetBrains we want to move this code into the Vue frontend.

Create default AppMap filter if none exists

---

.travis.yml
package.json
packages/cli/package.json
packages/client/package.json
packages/components/package.json
packages/diagrams/package.json
packages/models/package.json
packages/openapi/package.json
packages/scanner/package.json
packages/sequence-diagram/package.json
packages/telemetry/package.json
packages/validate/package.json

Fixes #1255 
We can stop supporting Node 14 and so we can stop testing with it in CI to save time and resources.

Do not test on node 14

---

packages/components/package.json
yarn.lock

Bump `@appland/sequence-diagram` to `1.6.1` in `@appland/components`.

Bump sequence diagram version in components

---

packages/components/src/components/install-guide/install-instructions/JavaScript.vue
packages/components/src/components/install-guide/install-instructions/Python.vue
packages/components/src/components/install-guide/install-instructions/Ruby.vue
packages/components/src/stories/install-guide/ProjectPicker.stories.js

This pull request updates manual instructions for Python, Ruby and JavaScript, informing the user to create an `appmap.yml` in a language specific manner.
Java is addressed via an upcoming change in `vscode-appland`.

feat: Manual instructions instruct the user to create appmap.yml

---

packages/components/src/components/install-guide/ProjectPickerRow.vue
packages/components/src/stories/install-guide/ProjectPicker.stories.js
packages/components/tests/e2e/specs/projectPickerBadProject.spec.js

Fixes #1266 
Unsupported projects didn't have a `language` property, and several methods in the `v-project-picker-row` component were assuming that `language` existed, which was causing an error, making the project picker row fail to render. This PR fixes that by using optional chaining.
Before:
After:

Unsupported projects show helpful information

---

packages/cli/tests/unit/search/findCodeObjects.spec.ts
packages/components/tests/e2e/specs/appmap/componentDiagram.spec.js
packages/components/tests/e2e/specs/appmap/viewFilter.spec.js
packages/models/src/codeObjectId.js
packages/models/tests/unit/codeObjectId.spec.js

Fixes #1269 
We do not need to include the parent name for queries and routes because the relationship between a query/route and its parent is always the same and can be inferred from the type.
For more information, see discussion [here](https://github.com/getappmap/appmap-js/pull/1265).

Consistent `fqid`s for queries and (external) routes

---

packages/cli/src/fingerprint/algorithms.js
packages/cli/src/fingerprint/canonicalize.js
packages/cli/src/fingerprint/canonicalize/exceptions.ts
packages/cli/src/fingerprint/fingerprinter.ts
packages/cli/tests/unit/fingerprint/exceptions.spec.js
packages/models/src/classMap.js

Add exceptions to the AppMap index. This allows exceptions to be efficiently compared across versions, and displayed in the Code Objects view.

feat: Add exceptions to the index

---

packages/cli/package.json
packages/components/package.json
packages/openapi/package.json
packages/scanner/package.json
packages/sequence-diagram/package.json
yarn.lock

Upgrades `@appland/models` to 2.6.3 to include the changes made in [this PR](https://github.com/getappmap/appmap-js/pull/1271) to make `fqid`s consistent with VS Code.

Upgrade @appland/models to 2.6.3

---

.gitignore
packages/cli/src/cmds/compare/ChangeReporter.ts
packages/cli/src/cmds/compare/Digests.ts
packages/cli/src/cmds/compare/Paths.ts
packages/cli/src/cmds/compare/SequenceDiagramDigest.ts
packages/cli/src/cmds/compare/compare.ts
packages/cli/src/cmds/compare/loadFindings.ts
packages/cli/tests/unit/compare/isChanged.spec.ts
packages/cli/tests/unit/compare/isNew.spec.ts

Only report "tests"-recorded AppMaps as new or changed.
If there are other types of AppMaps, such as requests recordings, in the AppMap archive, don't consider these when reporting new & changed AppMaps, because they don't have stable names.
Fixes #1274

fix: Only "tests" AppMaps can be new or changed

---

packages/cli/jest.config.js
packages/cli/src/cmds/archive/ArchiveMetadata.ts
packages/cli/src/cmds/archive/analyze.ts
packages/cli/src/cmds/archive/archive.ts
packages/cli/src/cmds/archive/archiveStore.ts
packages/cli/src/cmds/archive/buildFilter.ts
packages/cli/src/cmds/archive/indexAppMaps.ts
packages/cli/src/cmds/archive/parseFilterArgs.ts
packages/cli/src/cmds/archive/updateSequenceDiagrams.ts
packages/cli/src/lib/loadAppMapConfig.ts
packages/cli/src/search/findCodeObjects.ts
packages/cli/src/sequenceDiagram/analyzeAppMaps.ts
packages/cli/src/utils.ts
packages/cli/tests/unit/analyze/compareFilter.spec.ts
packages/cli/tests/unit/analyze/parseFilterArgs.spec.ts
packages/cli/tests/unit/archive/archive.spec.ts
packages/cli/tests/unit/inspect.spec.ts
packages/cli/tests/unit/search/findCodeObjects.spec.ts

Configure filters that trim noise from the canonical sequence diagrams used for CI analysis.
Filters can be configured in two ways:
1) Via a `compare.filter` option in appmap.yml
2) Via `--filter` arguments to the `appmap archive` command
The filter type is defined as:
```typescript
export type HideOption =
| 'pragma'
| 'savepoint'
| 'pg_metadata'
| 'sqlite_metadata'
| 'selenium'
| 'ruby_included';
// This type is similar to FilterState in @appland/models, but only contains the
// fields that are likely to be used for creating a canonical sequence diagram.
export type CompareFilter = {
hide_external?: boolean;
dependency_folders?: Array<string>;
hide_name?: Array<string>;
hide?: Array<HideOption>;
reveal?: Array<HideOption>;
};
```
These options are related to the AppMapFilter and …

feat: Compare filter

---

packages/components/src/components/FilterMenu.vue
packages/components/src/components/FiltersForm.vue

When selecting a New root from the filter menu, the first item is selected. This selection color was incorrect, should be just white text to be consistent.
Closes https://github.com/getappmap/appmap-js/issues/1289

fix: New root selection

---

packages/cli/package.json
packages/scanner/package.json

This should improve error messages when user tries to run `npx @appland/appmap@latest` with a deprecated node version.

fix: Specify node version requirements for user-facing packages

---

packages/components/src/components/PopperMenu.vue
packages/components/src/components/Tabs.vue
packages/components/src/components/sequence/LoopAction.vue
packages/components/src/components/trace/TraceEventBlock.vue
packages/components/src/components/trace/TraceSummary.vue

Fixes #1314 
Ty's fix from [this issue](https://github.com/getappmap/appmap-js/issues/1289) ([this PR](https://github.com/getappmap/appmap-js/pull/1304)) did not trigger a release of `@appland/components` because there was not a commit with the prefix `feat:` or `fix:`.
This PR also removes some extraneous comments.

Release new version of components

---

packages/components/src/components/install-guide/ProjectPickerRow.vue
packages/components/src/components/install-guide/record-instructions/IntelliJ.vue
packages/components/src/components/install-guide/record-instructions/Java.vue

Fixes #1322 
Make sure the JVM flag in the instructions is correct.
Change from `-Djavaagent=appmap.jar` to `-javaagent:~/.appmap/lib/java/appmap.jar`.

Update java agent jar instructions

---

packages/telemetry/telemetry.spec.ts
packages/telemetry/telemetry.ts

The [porcelain](https://git-scm.com/docs/git-status#Documentation/git-status.txt---porcelainltversiongt) flag is intended to be used by scripts. It won't require stdin.
Fixes #1311

fix: `git status` is now run with the porcelain flag

---

packages/cli/src/cmds/sequenceDiagram.ts
packages/cli/tests/unit/sequenceDiagram.spec.ts

--expand specifies a code object to expand in the output diagram. The --expand option may be repeated.
Most commonly, --expand will specify a package.
Example:
--expand package:app/controllers

feat: sequence-diagram --expand option

---

packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/unit/VsCodeExtension.spec.js
packages/components/tests/unit/fixtures/user_page_scenario.appmap.json

Fixes #1340 
Previously, when opening an AppMap from the findings webview:
It would open to the `Trace View`:
This change (along with a followup change in `vscode-appland`) makes it so that it opens the AppMap to the finding:

Select finding when map opened from findings webview

---

packages/cli/src/appMapCatalog.js
packages/cli/src/cli.ts
packages/cli/src/fingerprint/fingerprintDirectoryCommand.ts
packages/cli/src/inventoryCommand.js
packages/cli/tests/unit/fingerprint/fingerprintDirectoryCommand.spec.ts

The `findFiles` utility function doesn't accept glob patterns, so these would never resolve to anything.

fix: Resolve some cases where AppMaps failed to be located

---

packages/components/src/components/FilterMenu.vue
packages/components/tests/e2e/specs/appmap/viewFilter.spec.js
packages/components/tests/e2e/specs/filterMenu.spec.js

Fixes #1347. 
Changed FilterMenu.vue:
- apply button title renamed from "Apply" to "Load"
- moved the button to the right of the filter select
- spacing between "Load" button and select on the left made consistent with Save Filter button and the input box on its left.
Before (Filter Menu storybook)
After (Filter Menu storybook)

fix: Apply button in filter dialog is confusing

---

packages/components/src/components/DetailsPanelFilters.vue
packages/components/src/components/DiagramSequence.vue
packages/components/src/components/sequence/Actor.vue
packages/components/src/lib/isPrecomputedSequenceDiagram.js
packages/components/src/pages/VsCodeExtension.vue
packages/components/src/store/vsCode.js
packages/components/src/stories/DiagramSequence.stories.js
packages/components/src/stories/VsCodeExtension.stories.js
packages/components/src/stories/data/sequence-diff/Users_profile_profile_display.appmap.json
packages/components/src/stories/data/sequence-diff/Users_profile_profile_display.diff.sequence.json
packages/components/src/stories/data/sequence/Users_profile_profile_display.diff.sequence.json
packages/components/src/stories/data/sequence/appland_api_key_diff.sequence.json
packages/components/tests/e2e/specs/appmap/sequenceDiagramDiff.spec.js
packages/scanner/package.json
yarn.lock

Fixes #1096 
Display sequence diagram diff in AppMap view. This feature is designed to be used to display the "diff" diagrams that are generated by AppMap Analysis in CI / GitHub Actions. 
When the AppMap diagram `loadData` method is called with a `sequenceDiagram` argument, that diagram will be used in place of the auto-generated sequence diagram that would otherwise be created. This "precomputed" sequence diagram provided can be a "diff" diagram. In this mode, the AppMap behavior differs from the default behavior in the following ways:
* The Filters functionality is disabled, because there is no way to change the sequence diagram to reflect the filters. 
* Diagram actions that do not contain any "diff" content are collapsed by default.
* The diagram scrolls to show the first "diff" …

feat: Sequence diagram diff in appmap

---

packages/cli/src/cli.ts
packages/cli/src/cmds/archive/generateOpenAPI.ts
packages/cli/src/cmds/compare/ArchiveAnalyzer.ts
packages/cli/src/cmds/openapi/DataStore.ts
packages/cli/src/cmds/openapi/DefinitionGenerator.ts
packages/cli/src/cmds/openapi/openapi.ts
packages/cli/src/lib/fileSizeFilter.ts
packages/cli/src/utils.ts
packages/cli/tests/unit/openapi.spec.ts
packages/openapi/src/index.ts
packages/openapi/src/method.ts
packages/openapi/src/securitySchemes.ts
packages/openapi/test/propertiesParser.spec.ts
packages/openapi/test/securitySchemes.spec.ts

For OpenAPI generation, stage requests data into files organized by request path, then process one path at a time. This approach will greatly reduce the max memory usage.
Fixes https://github.com/getappmap/appmap-js/issues/1342
Tested in https://github.com/land-of-apps/rails_tutorial_sample_app_7th_ed/pull/19/files#diff-a28198b36e9b27792ef763b3349cc505969aaff75e15e4bd5f43c3ced91117c3R37

fix: Reduce max memory usage of OpenAPI gen

---

packages/cli/src/cmds/openapi/DefinitionGenerator.ts
packages/openapi/src/model.ts
packages/openapi/test/model.spec.ts

OpenAPI paths must start with `/`. Discard paths that don't match this constraint.

fix: Ignore invalid OpenAPI paths

---

packages/cli/doc/index-verbose.md
packages/cli/package.json
packages/cli/src/fingerprint/fingerprintWatchCommand.ts
packages/cli/src/fingerprint/fingerprinter.ts
packages/cli/src/lib/quotePath.ts
packages/cli/tests/unit/fingerprint/fingerprintWatchCommand.spec.ts
packages/cli/tests/unit/fingerprint/fingerprinter.spec.ts
packages/cli/tests/unit/lib/quotePath.spec.ts
packages/cli/tsconfig.json
yarn.lock

The events are also human-readable and are printed when `--verbose` switch is used:
```console
$ yarn start index -v --watch -d ~/projects/tmp/mocha-examples/packages/apollo-server-graphql-api/
Watching appmaps in /home/divide/projects/tmp/mocha-examples/packages/apollo-server-graphql-api/tmp/appmap
AppMap added: tmp/appmap/mocha/Create Apollo-Server.appmap.json
Indexing tmp/appmap/mocha/Create Apollo-Server.appmap.json
Read 4204 bytes from tmp/appmap/mocha/Create Apollo-Server.appmap.json
Read 4204 bytes from tmp/appmap/mocha/Create Apollo-Server.appmap.json
Indexed /home/divide/projects/tmp/mocha-examples/packages/apollo-server-graphql-api/tmp/appmap/mocha/Create Apollo-Server.appmap.json
AppMap changed: tmp/appmap/mocha/Create Apollo-Server.appmap.json
Indexing tmp/appmap/mocha/Create …
```

Print indexing events

---

packages/cli/src/cmds/archive/analyzeWorker.ts
packages/cli/src/cmds/archive/index.ts
packages/cli/src/cmds/index/IndexResult.ts
packages/cli/src/lib/emitUsage.ts
packages/cli/tests/unit/fingerprint/fingerprintWatchCommand.spec.ts
packages/cli/tests/unit/lib/emitUsage.spec.ts

Following indexing, a JSON file is output to `./appmap/run-stats` (assuming `.appmap` exists). This file contains a sample AppMap metadata blob, the number of events and AppMaps processed and indicates whether the index occurred in CI.
Currently, this is not enabled in `--watch` mode, only during one shot indexing of a specific directory or via the `analyze` command.

feat: Emit run stats after index

---

packages/cli/resources/change-report.hbs
packages/cli/src/cmds/compare-report/MarkdownReport.ts
packages/cli/src/cmds/compare-report/compareReport.ts
packages/cli/tests/unit/compareReport/compareReport.spec.ts
packages/cli/tests/unit/compareReport/expectedReport-changedAppMaps.md.txt
packages/cli/tests/unit/compareReport/expectedReport-openapiDiff.md.txt
packages/cli/tests/unit/compareReport/expectedReport.md.txt

Experimental report sections can be enabled with the `--include-section` option. Default report sections can be disabled with the `--exclude-section` option.
`changed-appmaps` is now an experimental section, and therefore off by default.
See https://github.com/getappmap/analyze-action/pull/38

feat: Enable and disable report sections

---

packages/components/src/components/sequence/CallAction.vue
packages/components/src/components/sequence/CallLabel.vue
packages/components/tests/e2e/specs/appmap/sequenceDiagram.spec.js

Fixes: #1051 
style(CallAction.vue): add position:relative to .connecting-span for better alignment
test(sequenceDiagram.spec.js): verify .call-line-segment.connecting-span has position relative

Long function call labels on top of lifelines

---

packages/components/src/components/DiagramSequence.vue
packages/components/src/components/sequence/ReturnAction.vue
packages/components/src/components/sequence/ReturnLabel.vue
packages/components/tests/e2e/specs/appmap/sequenceDiagram.spec.js

Fixes: #1353 
feat(components/DiagramSequence.vue): add appMap prop to DiagramSequence
feat(sequence/ReturnAction.vue): integrate appMap prop to VReturnLabel instances
feat(sequence/ReturnLabel.vue): add tooltip to display return values or exceptions on hover
feat(sequenceDiagram.spec.js): add e2e test to verify tooltip visibility on hover

Return value tooltip on hover

---

packages/components/src/pages/install-guide/InvestigateFindings.vue
packages/components/tests/e2e/specs/investigateFindings.spec.js

Fixes:  https://github.com/getappmap/vscode-appland/issues/819
feat(InvestigateFindings.vue): add conditionally displayed 'View anal…ysis report' button
fix(InvestigateFindings.vue): rename viewProblems to viewFindings
test(investigateFindings.spec.js): update test to reflect new button label

Analysis tab should opens findings overview

---

packages/components/src/components/DetailsPanelFilters.vue
packages/components/tests/e2e/specs/appmap/componentDiagram.spec.js

Fixes: #1370 
feat(DetailsPanelFilters.vue): enhance root object filtering logic
test(componentDiagram.spec.js): add e2e tests for "Set as Root" functionality

Consistent set as root

---

packages/components/src/components/FilterMenu.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/e2e/specs/appmap/viewFilter.spec.js

Fixes #1379 
If you want to test this just go [here](https://5fe18baf66f2280021e634d0-gjwlzrufqf.chromatic.com/iframe.html?id=pages-vs-code--extension&viewMode=story) and try it out. Saving, deleting, and setting filters as default didn't used to work in Storybook, but now you can do any of those things and the filters will get saved in the browser's local storage.

Appmap filter works in the browser

---

packages/components/src/components/SignIn.vue

fix: The OpenAPI links have been replaced in the sign in page

---

packages/components/src/components/DetailsSearch.vue
packages/components/tests/e2e/specs/appmap/findings.spec.js

Fixes: #1375 
feat(DetailsSearch.vue): enhance findings filtering to include message and rule title
test(findings.spec.js): add e2e tests for new filtering functionality

Add filtering on analysis findings search.

---

packages/cli/package.json

Binaries built for `3.97.0` did not include the necessary Handlebars resources used by `compare-report`.
**3.97.0**
```
➜  cli git:(main) ./release/appmap-macos-arm64 archive -d ~/source/land-of-apps/sample_app_6th_ed
pkg/prelude/bootstrap.js:1876
throw error;
^
AssertionError [ERR_ASSERTION]: Report template directory 'change-report' not found
at Object.<anonymous> (/snapshot/appmap-js/packages/cli/built/cmds/compare-report/ReportSection.js:19:22)
```
**This branch**
```
➜  cli git:(fix/include-all-hbs-in-native-binary) ./release/appmap-macos-arm64 archive -d ~/source/land-of-apps/sample_app_6th_ed
Note: The AppMap archive won't contain the version of @appland/appmap because process.env.npm_package_version is not available.
Building 'auto' archive from tmp/appmap
Building archive of …
```

fix: Package all resources in the native binary

---

packages/cli/package.json
packages/cli/src/cmds/compare/ChangeReporter.ts
packages/cli/src/cmds/compare/DiffLoader.ts
packages/cli/src/lib/executeCommand.ts
packages/cli/tests/unit/compare/DiffLoader.spec.ts
packages/cli/tests/unit/compare/fixtureData/addDeleteChangeRemoveDiff.txt
packages/cli/tests/unit/compare/fixtureData/exampleDiff.txt
packages/cli/tests/unit/compare/fixtureData/expectedDiff.txt
packages/cli/tests/unit/compare/fixtureData/parsedUnifiedDiff.json
yarn.lock

Don't run `git diff` for every appmap - run it only when a new set of root files is encountered in the classMap.
Parse the diff output to figure out what the diff is for each file.
**How it used to work**
For every AppMap, if that AppMap contained source paths (most do...), [`git diff` was executed](https://github.com/getappmap/appmap-js/pull/1400/files#diff-c437d6ceecd503d4d812155930024411ffbdeba29439ec53f4efc2c9f26d88ecL97) to find the source diff for that AppMap.
When a PR contained a lot of changed AppMaps, this was a lot of work to perform.
**How it works now**
* For each AppMap [find the root source paths](https://github.com/getappmap/appmap-js/pull/1400/files#diff-c437d6ceecd503d4d812155930024411ffbdeba29439ec53f4efc2c9f26d88ecR95) (filename, if the path is not in a directory, or …

feat: Diff once

---

packages/components/src/components/DetailsButton.vue
packages/components/src/components/DetailsPanelEvent.vue
packages/components/src/components/TabButton.vue
packages/components/tests/e2e/specs/appmap/sequenceDiagramDiff.spec.js

When showing a precomputed sequence diagram, disable the other tabs since they don't indicate any "diff". Also, disable the options to `Show in Trace`, `Show in Sequence`, `Show in Flame Graph`. This whole section of the LHS panel can be disabled.
In the future, it would be great to bring "diff" to the dependency map as well.
When using a precomputed AppMap:

feat: Disable diagram tabs in 'diff' mode

---

packages/cli/src/cmds/archive/analyzeTask.ts
packages/cli/src/cmds/index/IndexResult.ts

The index worker shouldn’t return undefined. 
If it does, the worker crashes and a new one is launched, making indexing very slow.
In CI, this case doesn’t happen because the AppMaps are always unindexed when the analyzer runs. But locally, it’s easy to run the archive command on a repo that’s already indexed (eg by the IDE extension) and then this problem occurs.

fix: Don't report undefined when the index is already up-to-date

---

packages/cli/src/cmds/agentInstaller/gradleInstaller.ts
packages/cli/src/cmds/agentInstaller/mavenInstaller.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts

Set `appmap_dir` to `tmp/appmap` when creating the default configs for maven and gradle projects.

fix: set appmap_dir for maven, gradle project

---

packages/cli/src/lib/serveAndOpen.ts

The code tried to send an HTTP response twice in some cases, breaking eg. the 'sequence-diagram' command with the error `Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client`.

fix: Commands involving HTTP serving work again

---

packages/sequence-diagram/src/buildDiagram.ts
packages/sequence-diagram/src/types.ts
packages/sequence-diagram/tests/unit/sequenceDiagram.spec.ts
packages/sequence-diagram/tests/util.ts

Fixes #1413 
When loading the sequence diagram, we first need to [determine the Actors](https://github.com/getappmap/appmap-js/blob/main/packages/components/src/components/DiagramSequence.vue#L128). Previously, we were building an entire diagram using `buildDiagram` for this purpose, but that is unnecessary and computationally expensive. See this flame graph:
This PR creates a new function `getActors` that creates the actors without building an entire sequence diagram.
This is a separate PR so that we release a version of `@appland/sequence-diagram` that can be subsequently used in `@appland/components`.

Get actors without building a complete diagram

---

packages/components/package.json
packages/components/src/components/DiagramSequence.vue
yarn.lock

When loading an AppMap in VS Code, the Vue components are created and mounted before any data is available. This can lead to errors where we try to access properties on `undefined`. This PR ensures that we don't try to access these properties before there is appropriate data.
Also, because not all of the data is available upon component creation in VS Code, the `maxSeqDiagramCollapseDepth` was getting set to `0` when the sequence diagram was `mounted`, and it wasn't getting updated, causing problems with the auto-collapse feature. This PR fixes that.
Finally, this PR includes a couple of performance updates:
- Simplify action/actor key computation
- Get sequence diagram actors without building an entire sequence diagram (#1416)

Ensure smooth initial load in vs code & performance updates

---

packages/cli/resources/change-report/changed-appmaps/details.hbs
packages/cli/resources/change-report/changed-appmaps/heading.hbs
packages/cli/resources/change-report/failed-tests/details.hbs
packages/cli/resources/change-report/findings/details.hbs
packages/cli/resources/change-report/findings/heading.hbs
packages/cli/resources/change-report/new-appmaps/details.hbs
packages/cli/resources/change-report/new-appmaps/heading.hbs
packages/cli/resources/change-report/openapi-diff/details.hbs
packages/cli/resources/change-report/openapi-diff/heading.hbs
packages/cli/resources/change-report/removed-appmaps/details.hbs
packages/cli/resources/change-report/removed-appmaps/heading.hbs
packages/cli/src/cmds/compare-report/ChangeReport.ts
packages/cli/src/cmds/compare-report/MarkdownReport.ts
packages/cli/src/cmds/compare-report/Preprocessor.ts
packages/cli/src/cmds/compare-report/ReportSection.ts
packages/cli/src/cmds/compare/loadFindings.ts
packages/cli/tests/unit/compareReport/changedAppMaps.spec.ts
packages/cli/tests/unit/compareReport/compareReport.spec.ts
packages/cli/tests/unit/compareReport/expectedReport.md.txt
packages/cli/tests/unit/compareReport/findings.spec.ts
packages/cli/tests/unit/compareReport/newAppMaps.spec.ts
packages/cli/tests/unit/compareReport/openapiDiff.spec.ts
packages/cli/tests/unit/compareReport/removedAppMaps.spec.ts

Organize findings by category, rather than presenting them as one list.
List the "type" of new AppMaps, e.g. `1 new test`.
*Avoid*
```
<h2 id="security-flaws">Security flaws</h2>
```
*Use*
```
<h2 id="security-flaws">Security flaws</h2>
<-- New line here
```
Security flaws, Performance problems, and Code anti-patterns now each get their own section.
| Summary | Status |
| --- | --- |
| [Failed tests](#failed-tests) | :white_check_mark: All tests passed |
| [API changes](#openapi-changes) | :wrench: 1 non-breaking |
| [Security flaws](#security-flaws) |  🔒 1 new  :tada: 2 resolved  |
| [Performance problems](#performance-problems) |  :white_check_mark: None detected  |
| [Code anti-patterns](#code-antipatterns) |  :white_check_mark: None detected  |
| [New AppMaps](#new-appmaps) | :star: 1 …

feat: Organize findings by category

---

packages/sequence-diagram/package.json
packages/sequence-diagram/src/buildDiagram.ts
packages/sequence-diagram/src/mergeWindow.ts
yarn.lock

This small PR represents a massive performance boost for large AppMaps. It adds three caches to avoid repeating expensive computations:
- A cache for SQL that is parsed into an AST. This requires that [this commit](https://github.com/getappmap/appmap-js/pull/1432/commits/f813f3771e742afe8bffb0645774bb7b98984b8f) is released in `@appland/models`.
- Two caches for `sha256` values that are used when building digests.

Improve appmap performance in sequence diagram

---

packages/cli/resources/change-report/changed-appmaps/heading.hbs
packages/cli/resources/change-report/failed-tests/heading.hbs
packages/cli/resources/change-report/findings/details.hbs
packages/cli/resources/change-report/findings/heading.hbs
packages/cli/resources/change-report/new-appmaps/heading.hbs
packages/cli/resources/change-report/openapi-diff/heading.hbs
packages/cli/resources/change-report/removed-appmaps/heading.hbs
packages/cli/src/cmds/compare-report/ChangeReport.ts
packages/cli/src/cmds/compare-report/MarkdownReport.ts
packages/cli/src/cmds/compare-report/Preprocessor.ts
packages/cli/src/cmds/compare-report/ReportSection.ts
packages/cli/src/cmds/compare-report/helpers.ts
packages/cli/tests/unit/compareReport/changedAppMaps.spec.ts
packages/cli/tests/unit/compareReport/expectedReport.md.txt
packages/cli/tests/unit/compareReport/failedTests.spec.ts
packages/cli/tests/unit/compareReport/findings.spec.ts
packages/cli/tests/unit/compareReport/newAppMaps.spec.ts
packages/cli/tests/unit/compareReport/openapiDiff.spec.ts

| Summary | Status |
| --- | --- |
| Failed tests | :white_check_mark: All tests passed |
| [API changes](#openapi-changes) | :wrench: 1 non-breaking |
| [Security flaws](#security-flaws) |  🔒 1 new  :tada: 2 resolved  |
| Performance problems |  :white_check_mark: None detected  |
| Code anti-patterns |  :white_check_mark: None detected  |
| [New AppMaps](#new-appmaps) | :star: 1 new minitest test |
| [Removed AppMaps](#removed-appmaps) | :heavy_multiplication_x: 1 removed minitest test |
| Summary | Status |
| --- | --- |
| [Failed tests](#failed-tests) | :warning: 1 failed |
| [New AppMaps](#new-appmaps) | :star: 1 new minitest test |
| [Removed AppMaps](#removed-appmaps) | :heavy_multiplication_x: 1 removed minitest test |
:warning: **Note** Because 2 tests failed, AppMap is showing …

feat: Suppress report sections

---

packages/cli/resources/change-report/findings/details.hbs
packages/cli/src/cmds/compare-report/ReportSection.ts
packages/cli/tests/unit/compareReport/findings.spec.ts
packages/cli/tests/unit/compareReport/helpers.spec.ts

Fixes #1437 
When opening an AppMap from the findings section of a PR report, the relevant finding is selected in the AppMap viewer. This is accomplished by adding a `state` query param that has a base64-url-encoded string as its value.

Finding is selected in appmaps from PR report

---

packages/components/package.json
packages/components/src/components/DetailsPanelListHeader.vue
packages/components/src/components/DiagramFlamegraph.vue
packages/components/src/components/DiagramSequence.vue
packages/components/src/components/DiagramTrace.vue
packages/components/src/components/flamegraph/FlamegraphBranch.vue
packages/components/src/components/flamegraph/FlamegraphHover.vue
packages/components/src/components/flamegraph/FlamegraphItem.vue
packages/components/src/components/flamegraph/FlamegraphMain.vue
packages/components/src/components/flamegraph/FlamegraphNode.vue
packages/components/src/components/sequence/Actor.vue
packages/components/src/components/sequence/CallAction.vue
packages/components/src/components/sequence/CallLabel.vue
packages/components/src/components/sequence/LoopAction.vue
packages/components/src/components/sequence/ReturnAction.vue
packages/components/src/components/sequence/ReturnLabel.vue
packages/components/src/components/trace/Trace.vue
packages/components/src/components/trace/TraceEventBlock.vue
packages/components/src/components/trace/TraceNode.vue
packages/components/src/components/trace/TraceNodeColumns.vue
packages/components/src/components/trace/TraceNodeElapsed.vue
packages/components/src/components/trace/TraceNodeLabels.vue
packages/components/src/components/trace/TraceSummary.vue
packages/components/src/pages/Diff.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/src/store/vsCode.js
packages/components/src/stories/DiagramSequence.stories.js
packages/components/src/stories/Trace.stories.js
packages/components/tests/e2e/specs/appmap/sequenceDiagram.spec.js
yarn.lock

This is the third and largest PR in a series of PRs that improve AppMap viewer performance.
There are several categories of changes in this PR.
- **Functional components**: They have improved performance over standard components because they have less overhead.
- **Stabilize props**: Whenever a prop changes the component and all children re-render. We were passing `selectedEvent` and `focusedEvent` as props down through many levels of components. These values change often and were causing unnecessary re-renders. They were already in the Vuex store, so I removed them as props and changed it so that components that actually use them have computed properties that pull them from the store.
- **Decrease repeated access to computed properties**: There is a small amount of overhead from Vue when …

Improve appmap performance in components

---

packages/components/src/components/install-guide/record-instructions/IntelliJ.vue
packages/components/src/components/install-guide/record-instructions/Java.vue

This PR also fixes the doc links within the instructions which are still anchored to a now-deleted section.

Change mentions of "Runnable recording" to "code block recording" in install instructions

---

packages/components/src/components/DetailsSearch.vue
packages/components/tests/e2e/specs/appmap/findings.spec.js
packages/components/tests/e2e/specs/appmap/sequenceDiagramDiff.spec.js
packages/components/tests/e2e/specs/appmap/viewFilter.spec.js

Fixes: #1056 
fix(DetailsSearch.vue): modify condition to push item based on childLeafs length
fix(findings.spec.js): add e2e test for actionview package search in AppMap

Include all packages in search

---

packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/e2e/specs/appmap/sequenceDiagram.spec.js

Fixes: #1426 
feat(VsCodeExtension.vue): prevent seqDiagramCollapseDepth from exceeding max
test(sequenceDiagram.spec.js): add checks for default collapse depth limits

Default collapse depth should be within range

---

packages/cli/src/utils.ts
packages/cli/tests/unit/utils.spec.ts

With filesystem symlink loops `depends` and other commands could get into an infinite loop or crash with ELOOP. Using lstat instead of stat prevents this infinite recursion.

fix: Gracefully handle filesystem symlink loops

---

packages/models/src/appMapFilter.js
packages/models/tests/unit/appMapFilter.spec.js

The following labels are recognized as being "roots" (aka commands):
* `cli.command`
* `job.perform`
* `message.handle`
These labels extend the existing definition of a "root", which is currently only HTTP server requests.
A follow-on to this will change "Limit root events to HTTP" to something like "Limit root events to commands":
PS "Hide unlabeled" seems kind of useless, maybe we should drop it.

feat: Recognize certain labeled functions as roots

---

packages/components/src/components/DiagramSequence.vue
packages/components/tests/e2e/specs/appmap/sequenceDiagram.spec.js

Fixes #1473 
This fixes the problem where selecting an event from the sidebar did not pan to the event in the sequence diagram.

Pan to selected event in sequence diagram

---

packages/components/src/components/DiagramSequence.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/src/stories/VsCodeExtension.stories.js
packages/components/tests/e2e/specs/appmap/slowLoad.spec.js

Fixes #1471 
In the VS Code extension, the collapse depth was initially being set to `0` whenever a map was opened. This behavior only happens in VS Code and it does not happen in Storybook.

Correctly set initial collapse depth in sequence diagram

---

packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/unit/VsCodeExtension.spec.js

Currently, it is possible to open an AppMap by including the state as the `fragment` in the URI like this:
```
{ fragment: eyJjdXJyZW50VmlldyI6InZpZXdDb21wb25lbnQiLCJzZWxlY3RlZE9iamVjdCI6ImV2ZW50OjQ0In0 }
```
The state is a base-64-encoded string. The above string `eyJj...` decodes to:
```
'{"currentView":"viewComponent","selectedObject":"event:44"}'
```
With this PR, the state can include the `selectedObjects` field:
```
'{"selectedObjects":["event:44","package:app/controllers"]}'
```
So, opening an AppMap with the above state will have both code objects selected, and they will be navigable using the menu introduced in #1480.

Open an AppMap with multiple selected objects

---

packages/components/src/pages/VsCodeExtension.vue

* The icons for the export, stats, and refresh control buttons got a bit too thick recently. This PR slims them back down.
* Adds a hover effect to the fullscreen icon.

Fix control button styling

---

packages/components/src/assets/hamburger-menu.svg
packages/components/src/components/DetailsPanel.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/e2e/specs/appmap/collapsibleSidebar.spec.js
packages/components/tests/e2e/specs/appmap/smallDevice.spec.js

[Try it out here](https://5fe18baf66f2280021e634d0-yhfbggzizq.chromatic.com/iframe.html?args=&id=pages-vs-code--extension-with-default-sequence-view&viewMode=story)
This PR makes it so that the left-hand side (LHS) panel is collapsible. When the component is rendered, the side panel is shown unless the component width is less than 900px.
This adds a chevron in the top right corner of the LHS panel:
If you click the chevron, then the panel slides to the left:
Clicking the hamburger menu icon makes the LHS panel visible again. 
Also, if you click on a code object in the diagram and the LHS panel is collapsed, then it will expand and become visible.

Collapsible sidebar

---

packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/e2e/specs/appmap/fullscreen.spec.js

- The state no longer de-syncs after pressing Esc
- Full screen now only targets the AppMap viewer element, not the entire document
- This will be useful for dropping the element into other contexts

Full screen fixes

---

packages/cli/src/cmds/index/index.ts

Otherwise the indexer will not run without an API key, and the API key is not yet reliably provided (not should it be absolutely required, since indexing does not require a key and the local RPC operations don't require one either).

fix: Make API key optional for index watch mode

---

packages/components/src/components/DiagramComponent.vue
packages/components/src/components/chat/Chat.vue
packages/components/src/pages/ChatSearch.vue
packages/components/src/stories/Accordion.stories.js
packages/components/src/stories/ChatSearch.stories.js
packages/components/src/stories/CodeSnippet.stories.js
packages/components/src/stories/DiagramComponent.stories.js
packages/components/src/stories/DiagramFlamegraph.stories.js
packages/components/src/stories/Diff.stories.js
packages/components/src/stories/FlashMessage.stories.js
packages/components/src/stories/Notification.stories.js
packages/components/src/stories/Popper.stories.js
packages/components/src/stories/SignIn.stories.js
packages/components/src/stories/Slider.stories.js
packages/components/src/stories/Tabs.stories.js
packages/components/src/stories/Trace.stories.js
packages/components/src/stories/TraceNode.stories.js
packages/components/src/stories/ViewFilterMenu.stories.js
packages/components/src/stories/VsCodeExtension.stories.js
packages/components/src/stories/VsCodeExtensionEmpty.stories.js
packages/components/src/stories/VsCodeExtensionJava.stories.js
packages/components/src/stories/install-guide/InstallGuide.stories.js
packages/components/src/stories/install-guide/RecordAppMaps.stories.js
packages/components/src/stories/install-guide/Status.stories.js

Linting in `@appland/components` is currently noisy and difficult to read, mostly because of the storybook rule `storybook/prefer-pascal-case`. This PR fixes the linting warnings:
```
/home/ahtrotta/projects/appmap/appmap-js/packages/components/src/components/DiagramComponent.vue
8:10  warning  'CLEAR_SELECTION_STACK' is defined but never used  @typescript-eslint/no-unused-vars
/home/ahtrotta/projects/appmap/appmap-js/packages/components/src/components/chat/Chat.vue
107:6  warning  'Suggestion' is defined but never used  @typescript-eslint/no-unused-vars
/home/ahtrotta/projects/appmap/appmap-js/packages/components/src/pages/ChatSearch.vue
98:8  warning  '_' is defined but never used  @typescript-eslint/no-unused-vars
/home/ahtrotta/projects/appmap/appmap-js/packages/components/src/stories/ …
```

Fix lint warnings in @appland/components

---

packages/client/src/index.ts
packages/components/src/components/mixins/authenticatedClient.js
packages/components/src/pages/Chat.vue
packages/components/src/pages/ChatSearch.vue
packages/components/tests/unit/chat/authentication.spec.js

This change allows authenticated API requests from Chat/ChatSearch. This is still used for things like providing message feedback.

fix: Authenticate Chat/ChatSearch frontend clients

---

packages/components/src/components/chat/Chat.vue
packages/components/src/stories/ChatSearch.stories.js
packages/components/tests/unit/chat/ChatComponent.spec.js

* When the user scrolls up, stop auto-scrolling.
* When the user scrolls back down to the bottom again, resume auto-scrolling.
It's important to base this on the `scrollTop` property, rather than on the `scrollHeight`, because the `scrollHeight` is frequently changing due to new content being added. It's also not a good idea to try and track state variables like `autoScroll` and activate/cancel them based on scroll events, because there's no good way to distinguish between scroll events that are triggered by the user and those that are triggered by DOM changes.
https://www.loom.com/share/a32dd639a44a4290a620fd062a61ca6c

fix: Allow user scroll

---

packages/components/build/svg.d.ts
packages/components/src/components/mixins/emitLink.ts
packages/components/src/components/notices/ConfigurationRequiredNotice.vue
packages/components/src/components/notices/NoDataNotice.vue
packages/components/src/components/notices/UnlicensedNotice.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/src/stories/Notices.stories.js
packages/components/src/stories/VsCodeExtensionUnlicensed.stories.js
packages/components/tests/e2e/specs/appmap/empty.spec.js
packages/components/tests/unit/VsCodeExtension.spec.js
packages/components/tests/unit/mixins/emitLink.spec.js
packages/components/tests/unit/notices/ConfigurationRequiredNotice.spec.js
packages/components/tests/unit/notices/UnlicensedNotice.spec.js
packages/components/tsconfig.json

This change adds the following two notices for use in Confluence. There's an additional change which emits link clicks as events so they can be passed through an API to (purposefully) circumvent CSP.

feat: Add a page to notify of invalid license

---

packages/components/src/pages/ChatSearch.vue

Drop the "Diagnostics" display from the ChatSearch, unless it's enabled by property.

feat: Drop Diagnostics info from ChatSearch

---

packages/components/src/components/install-guide/ProjectPickerRow.vue
packages/components/src/components/install-guide/record-instructions/IntelliJ.vue

We are starting to use scoped styles in our Vue components, but in the case of SVGs it doesn't work flawlessly. Consequently this line is causing the 'huge logo' problem...
As a fix I am removing the 'scoped' attribute, because it's not really needed. The run config icon should always be icon width. 
Before:
After:

Removed Scoped Style from the Run Config Icon

---

packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/unit/VsCodeExtension.spec.js

Fixes #1435 
Currently, when opening an AppMap from an AppMap PR report ([like this one](https://getappmap.com/github_artifact?owner=getappmap&repo=appmap-server&run_id=7503869671&base_revision=1d9e16b1783841d0acc60ae8d4a3d163d9283775&head_revision=9361bb62e5ba31f98e375b6b5c3f7701709dd85f&path=head%2Frspec%2FTrialLicenseRequestsController_create_submits_the_new_email_form.appmap.json)) a new `AppMap default` filter will be added each time the page loads, so you can end up with a lot of them:

Stop creating multiple default filters in the browser

---

appmap.yml
packages/cli/appmap.yml
packages/cli/src/cmds/index/index.ts
packages/cli/src/rpc/appmap/filter.ts
packages/cli/src/rpc/appmap/stats.ts
packages/cli/tests/integration/buildRPC.ts
packages/cli/tests/integration/rpc.appmap.spec.ts
packages/rpc/src/appmap.ts

Provide RPC command `appmap.stats`, which includes summary information about the AppMaps available in the workspace.
This PR is the basis for https://github.com/getappmap/appmap-js/pull/1547 , and includes the RPC and CLI changes (only).

feat: appmap.stats RPC

---

packages/components/src/components/PopperMenu.vue
packages/components/src/components/Tabs.vue
packages/components/src/pages/ChatSearch.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/tests/e2e/specs/appmap/viewFilter.spec.js
packages/components/tests/e2e/specs/chat/chatSearch.spec.js

Fixes #1522 
This PR fixes the issue where the AppMap control buttons were being clipped in the Chat Search interface. Instead of using the width of the viewport for responsive styling, this PR uses the width of the AppMap view component.

Map controls are responsive to column width

---

.github/workflows/main.yml
packages/components/build/vue.d.ts
packages/components/src/components/chat-search/Instructions.vue
packages/components/src/components/chat-search/MatchInstructions.vue
packages/components/src/components/chat-search/NoMatchInstructions.vue
packages/components/src/components/chat/Chat.vue
packages/components/src/components/chat/Loader.vue
packages/components/src/components/chat/SuggestionGrid.vue
packages/components/src/components/chat/ToolStatus.vue
packages/components/src/components/chat/UserMessage.vue
packages/components/src/lib/AppMapRPC.ts
packages/components/src/pages/Chat.vue
packages/components/src/pages/ChatSearch.vue
packages/components/src/stories/ChatSearch.stories.js
packages/components/src/stories/ChatSearchInstructions.stories.js
packages/components/src/stories/ChatSearchNoMatchInstructions.stories.js
packages/components/src/stories/ChatTools.stories.js
packages/components/tests/e2e/specs/appmap/sequenceDiagramDiff.spec.js
packages/components/tests/e2e/specs/chat/chatSearch.spec.js
packages/components/tests/unit/chat/ChatComponent.spec.js
packages/components/tests/unit/chat/ChatSearch.spec.js
packages/components/tests/unit/chat/authentication.spec.js
packages/components/tsconfig.json

Builds on https://github.com/getappmap/appmap-js/pull/1551 , adding Components changes (only).
Shows stats about the available AppMaps, plus "how it works" and some tips.
If no maps are found, the user sees something like this:
If maps are found, a bit of information is shown about that:
Fixes #1548

feat: Add AppMaps context to Navie

---

packages/components/src/components/ExportJSON.vue
packages/components/src/components/PopperMenu.vue
packages/components/src/components/sequence/DownloadSequenceDiagram.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/src/stories/VsCodeExtension.stories.js
packages/components/tests/e2e/specs/appmap/export.spec.js
packages/components/tests/e2e/specs/appmap/sequenceDiagram.spec.js
packages/components/tests/e2e/specs/appmap/viewFilter.spec.js
packages/components/tests/e2e/specs/chat/chatSearch.spec.js
packages/components/tests/unit/ExportJSON.spec.js
packages/components/tests/unit/VsCodeExtension.spec.js

Add an Export option that's downloads the AppMap data with the view configuration (selected tab and filters) embedded. It also restores the view configuration when the AppMap data is loaded.
Note: The view filters are applied to the data before download, so if the AppMap is pruned, the pruned-out data will not be included in the download. This is intended to enable users to create much smaller data uploads than they would otherwise be able to, if they always had to upload the entire AppMap JSON.
https://www.loom.com/share/64b87bad09004ca0978a5f4cee8e070a
Fixes #1526 
Related https://github.com/getappmap/vscode-appland/pull/862

feat: Export AppMap data as JSON

---

packages/components/src/components/chat-search/Instructions.vue
packages/components/src/components/chat-search/NoMatchInstructions.vue

Adds links in the Navie instructions that open the `Record AppMaps` instruction page when clicked.

Navie instructions link to record appmaps page

---

packages/cli/src/cmds/index/index.ts
packages/cli/src/fingerprint/fingerprintWatchCommand.ts
packages/cli/src/fingerprint/globber.ts
packages/cli/tests/unit/fingerprint/fingerprintWatchCommand.spec.ts

Don't apply stat delay to the initial scan - startup is blocked until the scan completes, so let it run ASAP.
Remove user configurability of the stat delay. It's not exposed anywhere to the user where it might be useful anyway.

feat: Improve file watcher stat delay

---

packages/cli/src/depends.js
packages/cli/src/fulltext/AppMapIndex.ts
packages/cli/src/lib/UpToDate.ts
packages/cli/src/utils.ts
packages/cli/tests/unit/depends.spec.ts
packages/cli/tests/unit/fulltext/AppMapIndex.spec.ts
packages/cli/tests/unit/lib/UpToDate.spec.ts

When searching client-side for AppMaps to match a set of keywords, apply a score penalty to AppMaps that are out-of-date.
The penalty is hard-coded here as `0.5 * stddev`

feat: Downscore out-of-date AppMaps in full text search

---

packages/cli/package.json
yarn.lock

The CLI is [not building correctly](https://github.com/getappmap/appmap-js/actions/runs/7878989013/job/21498405134?pr=1589#step:3:58) because `@appland/components` got released with a new major version. This updates the CLI so that it builds successfully.

Update @appland/components to 4.0.0 in @appland/cli

---

packages/cli/src/fulltext/AppMapIndex.ts
packages/cli/tests/unit/fulltext/AppMapIndex.spec.ts

This fixes the following issue
```txt
227802 [Stderr] Stack trace: TypeError: Cannot read properties of undefined (reading 'score')
227802 [Stderr]     at scoreMatches (/home/divide/.config/Code/User/globalStorage/appland.appmap/node_modules/@appland/appmap/built/fulltext/AppMapIndex.js:109:61)
227802 [Stderr]     at AppMapIndex.search (/home/divide/.config/Code/User/globalStorage/appland.appmap/node_modules/@appland/appmap/built/fulltext/AppMapIndex.js:184:28)
227802 [Stderr]     at async AppMapIndex.search (/home/divide/.config/Code/User/globalStorage/appland.appmap/node_modules/@appland/appmap/built/fulltext/AppMapIndex.js:193:16)
227802 [Stderr]     at async handler (/home/divide/.config/Code/User/globalStorage/appland.appmap/node_modules/@appland/appmap/built/rpc/search/search.js:17:3 …
```

fix: Prevent read from undefined if no matches are found

---

packages/cli/src/rpc/explain/explain.ts
packages/cli/tests/integration/rpc.explain.spec.ts
packages/components/src/components/chat/Chat.vue
packages/components/src/pages/ChatSearch.vue
packages/components/tests/unit/chat/ChatSearch.spec.js

This PR fixes two issues:
1. Responses were not being streamed in if the user had no AppMap matches
2. If the user had not agreed to the latest EULA, the socket would close without notifying the user
Resolves #1601 
Resolves #1602

fix: Empty or invalid Navie responses

---

packages/components/src/pages/ChatSearch.vue
packages/components/src/stories/ChatTools.stories.js
packages/components/tests/unit/chat/ChatSearch.spec.js

When the project does not contain AppMaps, Navie will not initiate a search. Account for this in the ChatSearch UI.
The progress box language is updated somewhat. 
**Initial message**
**Project was searched for AppMaps**
**Project was not searched for AppMaps**

feat: Navie may not always search for AppMaps

---

packages/cli/package.json

Resolves the following error in the binary distribution
```
Error: Cannot find module '/snapshot/appmap-js/node_modules/openai/_shims/auto/runtime-node.js'
```

fix: Add missing dynamic import

---

.github/workflows/main.yml
packages/cli/package.json
packages/cli/tests/binary/helpers/index.ts
packages/cli/tests/binary/helpers/setup.ts
packages/cli/tests/binary/jest.config.js
packages/cli/tests/binary/smoke.bin-spec.ts

This isn't as extensive as it used to be, but it's enough to catch and prevent any missing module issues in the future, and lays the groundwork to expand tests via Jest.

Test the native binary for @appland/appmap

---

packages/components/src/lib/debounce.ts
packages/components/src/pages/ChatSearch.vue
packages/components/tests/unit/chat/ChatSearch.spec.js
packages/components/tests/unit/lib/debounce.spec.js

Changes to 'most recent AppMaps' will trigger a reload of AppMap stats. The RPC call is debounced to one request per second.
[Peek 2024-03-01 16-22.webm](https://github.com/getappmap/appmap-js/assets/8737782/d09ebcac-f6f2-4f63-823e-67838fa8290e)
Resolves #1607

feat: AppMap stats in the Navie view are reactive

---

packages/components/src/components/chat/Chat.vue

If a user accesses Navie and they haven't activated their IDE (which is probably quite uncommon), then we want to show them messaging that is consistent with the new `Activate` terminology.

Use activation terminology in Navie

---

packages/components/src/components/Container.vue
packages/components/src/components/FilterMenu.vue
packages/components/src/components/Slider.vue
packages/components/src/pages/VsCodeExtension.vue

* Make scrollbars a lighter shade of grey so it has better contrast.
* Make the zoom sliders have better contrast.
* Always show the "X" close icon for the filter menu.
* When hiding a code object with a long name, don't extend the width of the filter menu.

Update filter menu and increase contrast

---

packages/cli/src/cmds/index/index.ts
packages/components/src/components/chat-search/ContextStatus.vue
packages/components/src/components/chat-search/MatchInstructions.vue
packages/components/src/components/chat-search/NoMatchInstructions.vue
packages/components/src/lib/AppMapRPC.ts
packages/components/src/pages/ChatSearch.vue
packages/components/src/stories/ChatSearch.stories.js
packages/components/src/stories/ChatSearchNoMatchInstructions.stories.js
packages/components/tests/unit/chat/ChatSearch.spec.js

This PR modifies the ChatSearch frontend to request stats from `v2.appmap.stats` instead of the v1 method. It aggregates the response to fit within the current frontend.

feat: Migrate ChatSearch to v2 stats API

---

packages/components/src/assets/compass-simpler.svg
packages/components/src/components/Button.vue
packages/components/src/components/DetailsPanel.vue
packages/components/src/components/chat/Chat.vue
packages/components/src/components/chat/ChatInput.vue
packages/components/src/pages/ChatSearch.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/src/stories/ChatSearch.stories.js
packages/components/tests/e2e/specs/chat/chatSearch.spec.js
packages/components/tests/unit/VsCodeExtension.spec.js
packages/components/tests/unit/chat/ChatSearch.spec.js

Fixes getappmap/board#316
This PR and it's [VS Code counterpart](https://github.com/getappmap/vscode-appland/pull/920) allow a user to open Navie from within an AppMap and then chat with Navie using that AppMap as the context.
In an AppMap, there are three clickable elements that will open Navie with the AppMap as context:
1. There is a small compass icon in the control bar.
2. When the details panel is collapsed, there is a compass icon.
3. When the details panel is open, there is an `Ask Navie` button.
When Navie is opened with a single AppMap as context:
* The AppMap is rendered from the start in the right panel.
* There is text describing that the user is asking Navie about a single AppMap.
* There is a button that allows the user to switch to using the full workspace as context.
* …

Open Navie from an appmap

---

packages/navie/src/chat-openai.ts
packages/navie/src/explain.ts
packages/navie/src/services/completion-service.ts
packages/navie/src/services/memory-service.ts
packages/navie/src/services/vector-terms-service.ts
packages/navie/test/services/vector-terms-service.spec.ts

This change allows using `APPMAP_NAVIE_MODEL` and `APPMAP_NAVIE_TOKEN_LIMIT` environment variables along with `OPENAI_{API_KEY,BASE_URL}` and `AZURE_OPENAI_API_{KEY,VERSION,INSTANCE_NAME,DEPLOYMENT_NAME` used by `@langchain/openai` to configure target LLM for Navie.

Allow configuring LLM with environment variables

---

packages/cli/package.json
yarn.lock

Pick up the new RAG-based @help agent.
Though it looks like this may have happened automatically - https://github.com/getappmap/appmap-js/releases/tag/%40appland/appmap-v3.134.0

feat: Update @appland/navie

---

packages/components/src/components/install-guide/record-instructions/IntelliJ.vue

Fixes #1660 
The instructions were not complete before. The instructions now reflect what is on our [docs page about process recording](https://appmap.io/docs/reference/appmap-java.html#process-recording).

Update intellij process recording instructions

---

packages/navie/src/agents/explain-agent.ts

This fixes the server-side issue where one context response maps to both search and help retrievals.

fix: Request context serially

---

packages/components/package.json
yarn.lock

If we force `@appland/rpc` to be version 1.6.0 or higher in `@appland/components` then it will solve the problem that Joachim has been running into when adding the new RPC to JetBrains.

Update `@appland/rpc` to 1.6.0 in `@appland/components`

---

packages/components/src/components/chat/SuggestionGrid.vue

@evlawler requested that I make this change recently because the language is confusing some users.

Tweak Navie suggestion language

---

packages/client/package.json
packages/components/src/assets/info-circle.svg
packages/components/src/components/chat-search/ContextStatus.vue
packages/components/src/components/chat-search/StatusBar.vue
packages/components/src/pages/ChatSearch.vue
packages/components/tests/e2e/specs/chat/chatSearch.spec.js
packages/models/package.json
packages/openapi/package.json
packages/telemetry/package.json
yarn.lock

* Changes the "No AppMaps" status bar from red to blue to de-emphasize it. 
* Changes the warning/error exclamation point icon to an info icon.
* Makes it so that the "No AppMaps" status bar does not stay on the page while the user is chatting.
* Changed `No AppMaps available` to `No AppMap data available`.
* Changed `33 AppMaps available` to `33 AppMap recordings available` (where 33 is an example number).

De-emphasize "No AppMaps" status in Navie

---

packages/cli/src/rpc/explain/collectContext.ts
packages/cli/tests/integration/rpc.explain.spec.ts
packages/cli/tests/unit/rpc/explain/ContextCollector.spec.ts
packages/navie/src/context.ts
packages/navie/src/index.ts
packages/navie/src/lib/apply-context.ts
packages/navie/src/services/apply-context-service.ts
packages/navie/test/services/apply-context-service.spec.ts

Apply the context items to the Navie context within the context request. 
This allows the context provider to prioritize among all the context that's available, rather than just sending it all back to Navie to be applied. By being smarter in this way, the context provider can make better decisions about which different types of context to include, when to go deeper on a particular type of context, when to drop very large context items that won't fit into the requested context window (or will take up most of the room and leave little room for other context).
Here are some examples to try and make the benefits clear.
Suppose Navie asks the context provider for 12,000 characters of context (a typical amount). The context provider finds an 8,000 character sequence diagram and many more …

feat: Apply fixes and updates to the apply-context function.

---

packages/rpc/src/configuration.ts

Define the types used by Configuration V2 so that client code (e.g. IDE plugins) can be developed against these types.

feat: Define v2.configuration.get+set

---

packages/cli/src/rpc/configuration.ts
packages/cli/src/rpc/explain/explain.ts
packages/navie/src/agent.ts
packages/navie/src/agents/explain-agent.ts
packages/navie/src/agents/generate-agent.ts
packages/navie/src/agents/help-agent.ts
packages/navie/src/context.ts
packages/navie/src/explain.ts
packages/navie/src/services/agent-selection-service.ts
packages/navie/src/services/classification-service.ts
packages/navie/src/services/lookup-context-service.ts
packages/navie/src/services/vector-terms-service.ts
packages/navie/test/agents/explain-agent.spec.ts
packages/navie/test/explain.spec.ts
packages/navie/test/services/classification-service.spec.ts
packages/navie/test/services/vector-terms-service.spec.ts
packages/rpc/src/explain.ts

When providing the explain context, consider the labels that have been applied to the question by the AI classifier.
Initially, the behavior is this:
```typescript
if (
labels.find((label) => label.name === 'architecture') ||
labels.find((label) => label.name === 'overview')
) {
keywords.push('architecture');
keywords.push('design');
keywords.push('readme');
keywords.push('about');
keywords.push('overview');
for (const dir of this.projectDirectories) {
keywords.push(basename(dir));
}
}
```
This is an effort to focus on high-level documentation and content that contains the name of the project itself.
In my ad-hoc testing, the classifier has done a good job of applying the "architecture" and "overview" labels. We should reflect these labels back to the user in the context view also (RHS of …

feat: Consider labels when providing the context

---

packages/cli/src/rpc/explain/explain.ts

Trigger architecture keywords only when the weight is 'high'

fix: Tone down architecture pressure

---

packages/cli/resources/change-report/failed-tests/details.hbs
packages/cli/src/report/urlHelpers.ts
packages/cli/tests/unit/compareReport/ChangeReporter.spec.ts

Fixes #1648.
When there is no `source_location` in an AppMap and a change report is generated with `appmap compare` command, AppMap metadata in resulting `change_report.json` will not contain the `source_location`. This was not tolerated in `appmap compare-report` command leading to the error shown in #1648.
- Helper function [source_url](https://github.com/getappmap/appmap-js/blob/2596f365ff12b89dafcc9868b4607377bcc635e2/packages/cli/src/report/urlHelpers.ts#L24) is changed to handle non-existent location.
- Related Handlebars [template](packages/cli/resources/change-report/failed-tests/details.hbs) is changed to show the test name instead of the test location in the failed test summary when there is no location.
- A unit [test](https://github.com/getappmap/appmap-js/blob/2596f365ff12b89d …

fix: Tolerate absence of source_location in compare-report

---

packages/components/src/components/chat-search/Context.vue
packages/components/src/components/chat-search/ContextItem.vue
packages/components/tests/unit/chat/ContextItem.spec.js

Raw PlantUML is no longer rendered for sequence diagrams. Instead, they're presented as list items.

fix: Don't render sequence diagram context content

---

packages/components/src/components/chat-search/Context.vue
packages/components/src/components/chat-search/ContextItem.vue
packages/components/src/stories/ChatSearch.stories.js
packages/components/tests/unit/chat/ChatSearch.spec.js

* Adds a message when there is no AppMap data to help the user create AppMap data.
* The `Open Instructions` button opens the installation instructions.
* Re-orders the context data so that AppMap data is above code snippets.
* Clips long AppMap names/paths with an ellipsis in the context view.

Warn users in Navie when they don't have AppMap data

---

packages/components/package.json
yarn.lock

Without this, the latest live version of components raises an error referencing `ConfigurationRpc.V2.Get.Method`

fix: Upgrade @appland/rpc to v1.9.0

---

packages/cli/src/cmds/index/index.ts
packages/cli/src/cmds/index/rpc.ts
packages/cli/src/cmds/navie/projectInfo.ts
packages/cli/src/lib/detectCodeEditor.ts
packages/cli/src/rpc/explain/buildContext.ts
packages/cli/src/rpc/explain/collectContext.ts
packages/cli/src/rpc/explain/explain.ts
packages/cli/src/rpc/explain/navie/navie-remote.ts
packages/cli/tests/integration/buildRPC.ts
packages/cli/tests/unit/rpc/explain/buildContext.spec.ts
packages/navie/package.json
packages/navie/src/agent.ts
packages/navie/src/context.ts
packages/navie/src/interaction-history.ts
packages/navie/src/lib/apply-context.ts
packages/navie/src/project-info.ts
packages/navie/src/prompt.ts
packages/navie/src/services/apply-context-service.ts
packages/navie/src/services/project-info-service.ts
packages/navie/test/agents/explain-agent.spec.ts
packages/navie/test/agents/help-agent.spec.ts
packages/navie/test/interaction-history.spec.ts
packages/navie/test/services/agent-selection-service.spec.ts
packages/navie/test/services/apply-context-service.spec.ts
packages/navie/test/services/project-info-service.spec.ts
yarn.lock

Fixes getappmap/board#318
The main reason for adding this is to help Navie provide IDE-specific @help.
This adds the `--code-editor` command-line option to the `rpc` command, which will propagate the code editor into the context sent to the LLM to help provide better answers. The code editor can also be detected from the environment, in some cases. Use of `--code-editor` is optional so the CLI will be backwards compatible, but we should change how we launch the rpc in VS Code and JetBrains after this change is released.
APPMAP_CODE_EDITOR can also be set in lieu of using the CLI option (which may not be available if the appmap executable is older). 
```
node ./built/cli.js rpc --port 0 --code-editor vscode
```
@help generate OpenAPI definitions
To generate OpenAPI definitions in Visual …

Include code editor in context

---

docs/navie/bring-your-own-llm.md
packages/cli/src/rpc/explain/explain.ts
packages/navie/src/explain.ts

8,000 seems inadequate for larger projects, in which the system prompts may be larger and the sequence diagrams are larger too.

feat: Update Navie token limit to 12,000

---

packages/navie/src/explain.ts

With 128k context, fresher knowledge and the broadest set of capabilities, GPT-4 Turbo is more powerful than GPT-4 and offered at a lower price.

feat: Switch to gpt-4-turbo-2024-04-09 as default

---

.github/workflows/build-native-scanner.yml
.github/workflows/build-native.yml
.releaserc.js
packages/scanner/bin/build-native
packages/scanner/package.json
yarn.lock

@apotterri @kgilpin I just replaced appmap with scanner where it makes sense.
@dustinbyrne note it need the same fix for npm tag as the other workflow.

ci: Build scanner packages natively

---

.github/workflows/build-native-scanner.yml
.github/workflows/build-native.yml

This fixes that CI failure after building native packages.

ci: Set NPM auth token for native build finalization

---

packages/components/src/pages/ChatSearch.vue

Fixes #1757 
Before, the context would briefly disappear when a user asked a followup question. The context would reappear, but it wasn't a smooth experience. This PR makes it so that the context remains until the user clicks the `New chat` button.

Context does not disappear on followup questions

---

packages/components/src/components/chat/UserMessage.vue
packages/components/src/lib/completionInterpolation.ts
packages/components/src/pages/ChatSearch.vue
packages/components/tests/unit/lib/completionInterpolation.spec.js

This gives the illusion of token streaming even though completions are streaming in multi-token chunks.
Before
[interp-before.webm](https://github.com/getappmap/appmap-js/assets/8737782/5ce788c8-094f-4cb8-8a5b-b2ea3a1e8e52)
After
[interp-after.webm](https://github.com/getappmap/appmap-js/assets/8737782/543bcf70-ad73-4d34-978c-dee02582cff7)
Resolves #1762

feat: Buffer and interpolate chunked completions

---

packages/cli/src/fulltext/FileIndex.ts
packages/cli/src/fulltext/SourceIndex.ts
packages/cli/src/fulltext/listGitProjectFIles.ts
packages/cli/src/fulltext/listProjectFiles.ts
packages/cli/tests/unit/fulltext/FileIndex.spec.ts
packages/cli/tests/unit/fulltext/SourceIndex.spec.ts
packages/cli/tests/unit/fulltext/listGitProjectFiles.spec.ts
packages/cli/tests/unit/fulltext/listProjectFiles.spec.ts

Before (some debugging added):
```
$ time node built/rpc/explain/try.js
collecting context,  ContextCollector {
appmapDirectories: [ '/home/divide/projects/applandinc.github.io' ],
sourceDirectories: [ '/home/divide/projects/applandinc.github.io' ],
vectorTerms: [
'edit',     'file',
'+appmap',  'node',
'diagnose', 'common',
'problems'
],
charLimit: 15924,
query: 'edit file +appmap node diagnose common problems'
}
Wrote file index to /tmp/user/1000/appmap-files-1714750213119aYPMUP/index.sqlite
buildFileIndex: 16.683s
Requested char limit: 15924
Collecting context with 5 events per diagram.
collectEvents: 0.253ms
Building source index with 10 files
Indexing 10 files:
6950 B	_docs/reference/appmap-node.md
694 B	_plugins/file_exists.rb
1274 B	_includes/docs/node_support_matrix.html
1608 B …
```

fix: Improve context gathering performance

---

packages/components/src/components/install-guide/install-instructions/Python.vue

Update the pip install instructions to include `--require-virtualenv`.
Fixes #1784 .

fix: update pip install command

---

packages/cli/src/cmds/index/index.ts
packages/cli/src/cmds/index/rpc.ts
packages/cli/src/fulltext/listProjectFiles.ts
packages/cli/src/lib/handleWorkingDirectory.ts
packages/cli/src/rpc/configuration.ts
packages/cli/tests/integration/RPCTest.ts
packages/cli/tests/unit/fulltext/listProjectFiles.spec.ts

`listProjectFiles` is yielding a full path if there is a match in the project directory. Fix this function so that all matches are relative to the project directory.
Related: When the `rpc` command gets multiple `-d` options, handle these directories using the configuration v2 style.

fix: Directory resolution

---

packages/cli/src/fulltext/FileIndex.ts
packages/cli/src/fulltext/listGitProjectFIles.ts
packages/cli/src/fulltext/queryKeywords.ts
packages/cli/src/fulltext/querySymbols.ts
packages/cli/tests/integration/rpc.explain.spec.ts
packages/cli/tests/unit/fixtures/source/sample.c
packages/cli/tests/unit/fixtures/source/sample.cs
packages/cli/tests/unit/fixtures/source/sample.generic
packages/cli/tests/unit/fixtures/source/sample.go
packages/cli/tests/unit/fixtures/source/sample.java
packages/cli/tests/unit/fixtures/source/sample.kt
packages/cli/tests/unit/fixtures/source/sample.php
packages/cli/tests/unit/fixtures/source/sample.py
packages/cli/tests/unit/fixtures/source/sample.rb
packages/cli/tests/unit/fixtures/source/sample.rs
packages/cli/tests/unit/fixtures/source/sample.ts
packages/cli/tests/unit/fulltext/FileIndex.spec.ts
packages/cli/tests/unit/fulltext/listGitProjectFiles.spec.ts
packages/cli/tests/unit/fulltext/querySymbols.spec.ts
packages/telemetry/telemetry.spec.ts
packages/telemetry/telemetry.ts

This approach uses RegEx to scrape function, class, interface, union, etc. names from source when building a full text index. This should improve accuracy when searching for static context.
There's some work left to do here, including:
I've been testing this locally with [Quake](https://github.com/id-Software/Quake) and [UnrealEngine](https://github.com/epicgames/unrealengine) (31.4M lines parsed)
```
Indexed 592 files in /home/db/dev/id-software/Quake in 254ms
```
```
Indexed 182567 files in /home/db/dev/EpicGames/UnrealEngine in 44628ms
```
Sample
```
Indexing file path QW/client/gl_mesh.c with terms QW client gl mesh GL alias build display fan length lists make model strip tris
Indexing file path QW/client/gl_draw.c with terms QW client gl draw EXT GL alloc alpha alt background begin …
```

feat: Include static symbol names in file terms

---

packages/navie/src/explain.ts
packages/navie/src/services/project-info-service.ts
packages/navie/test/explain.spec.ts
packages/navie/test/services/project-info-service.spec.ts

Prompt is too verbose with routes and packages for large projects.
Omit this info unless the user has asked a general architecture question.

fix: Don't prompt with appmapStats for non-arch questions

---

packages/cli/src/cli.ts
packages/cli/src/cmds/index/rpc.ts
packages/cli/src/cmds/navie.ts

This adds `appmap navie` command to run one-shot interactions with Navie that do the same context gathering as the RPC commands.
```console
$ LC_ALL=C ./built/cli.js navie --help
cli.js navie [question..]
Explain a question using Navie
Positionals:
question  Question text; appended to any other input     [array] [default: []]
Options:
--version         Show version number                            [boolean]
-v, --verbose         Run with verbose logging                       [boolean]
--help            Show help                                      [boolean]
-d, --directory       program working directory
[array] [default: ["/home/divide/projects/appmap-js/packages/cli"]]
--navie-provider  navie provider to use
[string] [choices: "local", "remote"]
--log-navie       Log Navie events to …
```

Navie oneshot command

---

packages/cli/src/cmds/agentInstaller/install-agent.ts
packages/cli/tests/unit/agentInstall/installCommand.spec.ts

Inform the user if the directory they've chosen for installation doesn't exist.
Fixes #1808.

fix: install subcommand checks that target exists

---

packages/navie/src/explain.ts
packages/navie/src/prompt.ts
packages/navie/src/services/project-info-service.ts

This PR updates the code editor prompt to inform the LLM that they're talking to a code editor user and not to provide additional instructions as to how to install the extension.
I've added an additional commit that will allow us to easily tweak the temperature via environment variable.
`how do i use appmap in this editor`
```
To use AppMap in VS Code for your Ruby project, follow these steps to ensure that AppMap is properly configured and you're able to record and visualize your code execution:
1. **Verify `appmap` gem Installation**:
Ensure the `appmap` gem is added at the beginning of your Gemfile in the `:development, :test` group:
```ruby
group :development, :test do
gem 'appmap'
end
```
Run `bundle install` to install the gem if it's not already installed.
2. **Configuration with …
```

Don't prompt extension users to install the extension

---

packages/cli/src/cmds/navie.ts
packages/cli/src/cmds/navie/help.ts
packages/cli/tests/unit/compareReport/verifyReportContents.ts
packages/navie/src/agents/explain-agent.ts
packages/navie/src/lib/apply-context.ts
packages/navie/src/navie.ts
packages/navie/src/services/classification-service.ts

Provide more specific instructions about AppMap help. Expand the classifiers to include greeting, troubleshoot, generate-code and generate-diagram. Drop generate.

feat: Update prompts and context

---

packages/navie/src/services/vector-terms-service.ts

This should improve accuracy of responses and adds an additional example for a poor prompt.
This should additionally fix cases where GPT-4 Turbo would respond with empty terms. E.g.,
```
Vector terms response:
Context:
Instructions:
---
Terms:
```
It's worth noting this behavior was rarely (if at all?) observed when using `gpt-4o`.

fix: Provide vector term examples as chat primitives

---

packages/cli/src/cmds/index/index.ts
packages/cli/src/cmds/navie.ts
packages/cli/src/rpc/explain/explain.ts
packages/cli/src/rpc/explain/navie/inavie.ts
packages/cli/src/rpc/explain/navie/navie-local.ts
packages/cli/src/rpc/explain/navie/navie-remote.ts
packages/cli/src/rpc/explain/navie/report-fetch-error.ts
packages/cli/tests/integration/rpc.explain.spec.ts
packages/cli/tests/unit/rpc/explain/Explain.spec.ts
packages/cli/tests/unit/rpc/explain/LocalNavie.spec.ts
packages/cli/tests/unit/rpc/explain/RemoteNavie.spec.ts
packages/navie/src/explain.ts
packages/navie/src/navie.ts

See https://github.com/getappmap/appmap-services/pull/70
These changes apply to navie-local only:
* Allocate thread and message ids by making API calls to api-services.
* Emit events when the agent name and classifiers are chosen.
* Update message metadata as the conversation progresses.

feat: Add conversation parameters

---

packages/models/src/appMapBuilder/eventStack.js

When creating a stack while building an AppMap, there's an unknown issue that causes an infinite loop that will eventually crash node.
This change introduces a check for the error, and throws an Error to avoid the crash. It's not really a fix, just a bandaid.

fix: don't crash on bad AppMaps

---

packages/cli/src/cmds/navie/help.ts
packages/cli/src/rpc/explain/collectContext.ts
packages/cli/tests/unit/cmds/navie/help.spec.ts
packages/cli/tests/unit/rpc/explain/ContextCollector.spec.ts

This change prevents context search from continuing if the supplied list of vector terms is empty.
Fixes https://github.com/getappmap/appmap-js/issues/1767

fix: Skip searching for context on empty input

---

packages/navie/src/lib/completion.ts
packages/navie/src/services/completion-service.ts
packages/navie/src/services/vector-terms-service.ts

Fixes #1860 
This was caused by two problems:
- system message merging (which is done to make sure to support engines which only accept a single system message) was only applied in *explain*,
- examples given in vector terms prompt mistakenly used `system` role instead of `assistant`.

Merge system messages everywhere

---

packages/components/src/components/DetailsPanel.vue
packages/components/src/components/chat-search/AskNavieButton.vue
packages/components/src/components/install-guide/record-instructions/RecordingMethod.vue
packages/components/src/pages/VsCodeExtension.vue
packages/components/src/stories/AskNavieButton.stories.js
packages/components/tests/unit/VsCodeExtension.spec.js

In some cases the cost of animating box shadows would significantly degrade IDE performance. These buttons have been reworked and standardized to reduce the cost of painting.

fix: Reduce the cost of painting Navie buttons

---

packages/components/src/assets/code-block-icon.svg
packages/components/src/components/CodeSnippet.vue
packages/components/src/components/install-guide/record-instructions/IntelliJ.vue
packages/components/src/components/install-guide/record-instructions/Java.vue
packages/components/src/components/install-guide/record-instructions/JavaScript.vue
packages/components/src/components/install-guide/record-instructions/Python.vue
packages/components/src/components/install-guide/record-instructions/RecordingMethod.vue
packages/components/src/components/install-guide/record-instructions/Ruby.vue
packages/components/src/components/mixins/typewriter.ts
packages/components/src/lib/buildPrompts.ts

This brings them in line with the (already released and live in VS Code) JavaScript instructions.
Python is also updated to include changes introduced in v2 of the agent, such as running `appmap-python`. This will need some fact checking.

feat: Update Java, Ruby and Python recording instructions

---

.gitignore
packages/navie/src/agents/explain-agent.ts
packages/navie/src/agents/help-agent.ts
packages/navie/src/commands/explain-command.ts
packages/navie/src/services/agent-selection-service.ts
packages/navie/test/services/agent-selection-service.spec.ts

* @help mode considers configured languages
* @help mode has built-in knowledge of Navie modes
* Tell the user when an agent mode is auto-selected
* `/nohelp` disables help mode
When experimenting this, I found that requiring `help-with-appmap=high` to be the only `high` selected classifier was too strict, and resulted in Navie running in `@explain` mode and trying to provide AppMap help without the benefit of the doc lookup RAG. 
So instead, Navie will inform the user that they are in `@help` mode and tell them how to get out of it. It would be nice if the Navie UI had a native way to indicate and explain the active mode.
Also, the `language` information in appmap.yml is considered sufficient for the help command to proceed; the user won't be prompted to enter their language if they have …

fix: Agent selection mode

---

packages/cli/src/lib/sqlErrorLog.ts
packages/cli/tests/unit/lib/sqlErrorLog.spec.ts
packages/scanner/src/sqlWarning.ts
packages/scanner/test/sqlWarning.spec.ts

Only create sql_warnings.txt if the env var APPMAP_SQL_WARNING is set. Also, if it is created, catch any errors and write them to the console.
Fixes #1902

fix: conditionally create sql_warnings.txt

---

packages/components/src/components/chat/Chat.vue
packages/components/src/pages/ChatSearch.vue
packages/components/src/stories/ChatSearch.stories.js
packages/components/tests/unit/chat/ChatComponent.spec.js

Instead of clearing the chat, "new chat" button now instead only shows when upstream (for example, a code editor) provides a method for that; if it does, it calls that. The intent is for the button to open a new tab instead.
Fixes #1922 (IDE patches to follow).

fix: "New chat" button doesn't destructively clear the chat anymore

---

packages/cli/src/fulltext/listGitProjectFIles.ts
packages/cli/tests/unit/fulltext/listGitProjectFiles.spec.ts

The output from `git status --porcelain` starts with 3 columns. Make sure it's parsed correctly.
Fixes #1931 .

fix: parse git status output correctly

---

packages/navie/package.json
packages/navie/src/services/openai-completion-service.ts
packages/navie/test/services/openai-completion-service.spec.ts
packages/navie/tsconfig.build.json
packages/navie/tsconfig.json

This makes sure we don't try to retry on Copilot errors.
Along with https://github.com/getappmap/vscode-appland/pull/1010 this fixes #1954

Don't retry on 422 from OpenAI

---

packages/cli/src/rpc/explain/explain.ts
packages/cli/src/rpc/explain/navie/history.ts
packages/cli/src/rpc/explain/navie/historyHelper.ts
packages/cli/src/rpc/explain/navie/historyWindows.ts
packages/cli/src/rpc/explain/navie/ihistory.ts
packages/cli/src/rpc/explain/navie/navie-remote.ts

This pull request addresses the issue of handling history on Windows by disabling the history functionality. Non-Administrator accounts cannot create symlinks by default on Windows, which is necessary for the current implementation of history.
- Introduced an `IHistory` interface to standardize history operations.
- Moved existing history-related functionality to the `History` class which implements `IHistory`.
- Created a `HistoryWindows` class that implements `IHistory` with no-op methods and throws a `ThreadAccessError` for unimplemented functionalities.
- Updated the initialization logic to conditionally use `HistoryWindows` on Windows platforms.
- Refactored references to `History` to use the new `IHistory` interface across the project.

fix: Symlinks fall back to copying files on Windows

---

packages/cli/src/rpc/explain/navie/navie-remote.ts

The async call before emitting a token would sometimes cause tokens to be emitted out of order.

fix: Prevent a case where tokens would appear out of order

---

packages/components/src/components/chat-search/Context.vue
packages/components/src/components/chat/ContextContainer.vue
packages/components/src/components/chat/File.vue
packages/components/src/components/chat/Handle.ts
packages/components/src/components/chat/PinEvent.ts
packages/components/src/index.js
packages/components/src/lib/PinFileRequest.ts
packages/components/src/pages/ChatSearch.vue
packages/components/tests/e2e/specs/chat/chatSearch.spec.js
packages/components/tests/unit/chat/ContextContainer.spec.js
packages/components/tests/unit/chat/File.spec.js

Give the user the ability to pin files to the Chat context, including through drag-and-drop.
There are a couple of tests here, but this will be further tested by the e2e tests in the vscode-appland changes that use it.

Pin files to context

---

packages/navie/src/lib/get-most-recent-messages.ts
packages/navie/test/lib/get-most-recent-messages.spec.ts

Considering the default limit is two messages, this can (will) completely overwrite any useful information.
This is more of an intermediate stop-gap to mitigate the issue. Fixing this properly will require some deeper abstraction.

fix: Ignore `@suggest` request and completions when preparing chat history

---

packages/components/src/pages/ChatSearch.vue

Emit an event when the ChatSearch component is completely loaded. This allows tests that use it to insure it's completely initialized before continuing.
Fixes #1994

test: emit an event when ChatSearch is loaded

---

packages/components/package.json
packages/components/src/components/chat/UserMessage.vue
packages/components/src/stories/ChatSearch.stories.js
packages/navie/src/command.ts
packages/navie/src/commands/observe-command.ts
packages/navie/src/navie.ts
packages/navie/src/services/anthropic-completion-service.ts
packages/navie/src/services/completion-service.ts
packages/navie/src/services/next-step-classification-service.ts
packages/navie/src/services/openai-completion-service.ts
packages/navie/test/commands/observe-command.spec.ts
packages/navie/test/services/openai-completion-service.spec.ts
yarn.lock

This pull request introduces a new `@observe` command to facilitate recording of test cases based on user inquiry. The user can specify some behavior they'd like to record and Navie will suggest a test case to run with AppMap enabled.
**Changes**:
1. **New Features**:
- Introduced an `@observe` command to identify and suggest the most relevant test cases for recording AppMap trace data.
2. **Bug Fixes**:
- Fixed a versioning issue in the `storybook` by correctly specifying the required version of `lru-cache`.
3. **Configuration Updates**:
- Updated `package.json` and `yarn.lock` to reflect the corrected version constraints for dependencies.
**Testing**:
- Added unit tests to cover the new `@observe` command functionality.
- All existing tests have been run to ensure no breakage in current …

feat: Add `@observe` command for recording suggestions

---

packages/navie/package.json
packages/navie/src/services/anthropic-completion-service.ts
packages/navie/src/services/openai-completion-service.ts
packages/navie/tsconfig.json
yarn.lock

Before:
```
Error: Failed to complete: Connection error.
at AnthropicCompletionService.complete_1 (/home/divide/projects/appmap-js/packages/navie/dist/services/anthropic-completion-service.js:170:23)
at complete_1.throw (<anonymous>)
at resume (/home/divide/projects/appmap-js/packages/navie/dist/services/anthropic-completion-service.js:24:44)
at reject (/home/divide/projects/appmap-js/packages/navie/dist/services/anthropic-completion-service.js:27:30)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
After:
```
Error: Failed to complete: FetchError: request to http://example.test/v1/messages failed, reason: getaddrinfo ENOTFOUND example.test
at AnthropicCompletionService.complete (/home/divide/projects/appmap-js/packages/navie/dist/services/anthropic-complet …
```

fix: More verbose errors from Anthropic completion service

---

packages/navie/package.json
packages/navie/src/services/anthropic-completion-service.ts
packages/navie/src/services/completion-service.ts
packages/navie/test/services/anthropic-completion-service.spec.ts
yarn.lock

This pull request addresses an issue with the AnthropicCompletionService where requests would fail due to an overload error from Claude's API. The following changes have been implemented to resolve this issue:
- **Retry Mechanism for SSE Errors:** 
- Introduced a method to parse SSE errors from error messages.
- Implemented a retry mechanism within the `complete` method to handle overload errors by retrying up to a maximum of five attempts with exponential backoff.
- **Unit Tests:**
- Enhanced the existing test suite to include a test that verifies the retry behavior when an overload error occurs.
- Updated mocks and test utilities to support the new retry logic.
- **Dependency Updates:**
- Updated the version of `@langchain/anthropic` to v0.3.1.
- **Automated Tests:** 
- Added a new test …

fix: Retry on Claude overload error

---

packages/navie/src/lib/trim-largest-user-message.ts
packages/navie/src/services/anthropic-completion-service.ts
packages/navie/src/services/openai-completion-service.ts
packages/navie/test/lib/trim-largest-user-message.spec.ts
packages/navie/test/services/anthropic-completion-service.spec.ts
packages/navie/test/services/openai-completion-service.spec.ts

Upon exceeding the max token limit, the completion will be retried, where the largest **user message** will be truncated by 15% of the **total content length**.
Resolves https://github.com/getappmap/appmap-js/issues/2007

fix: Truncate largest message if max tokens are exceeded

---

packages/cli/src/rpc/explain/collectContext.ts
packages/cli/tests/unit/rpc/explain/pattern.spec.ts

These can be used to store metadata and information used by Navie itself, such as prompts and snippets, without risk of that material being selected as context.

feat: Ignore .appmap and .navie directories when selecting context

---

packages/cli/tests/integration/rpc.explain.spec.ts
packages/cli/tests/unit/rpc/explain/Explain.spec.ts
packages/client/src/ai.ts

Proposed updates to provide user subscription info on thread creation.
We can use this information to determine:
* How long the user has been a subscriber for (and therefore, are they still in a free trial period?)
* To which products the user has an active subscription. Currently, there's only one: "AppMap Pro".
```javascript
export type SubscriptionItem = {
productName: string;
};
export type Subscription = {
enrollmentDate: Date;
subscriptions: SubscriptionItem[];
};
export type ConversationThread = {
id: string;
permissions: Permissions;
usage: Usage;
subscription: Subscription; <-- new
};
```
See Issue https://github.com/getappmap/appmap-services/issues/38
See PR https://github.com/getappmap/appmap-services/pull/83

feat: Report subscription status on thread creation

---

packages/navie/package.json
packages/navie/src/lib/string-or-default.ts
packages/navie/src/navie.ts
packages/navie/test/navie.spec.ts
yarn.lock

Some models (notably copilot) don't like empty user messages. Use the command name if there's no question.

fix: Handle empty prompts gracefully

---

packages/components/src/components/chat/ContextContainer.vue
packages/components/src/stories/UserMessage.stories.js
packages/components/tests/unit/chat/MarkdownCodeSnippet.spec.js
packages/components/tests/unit/chat/UserMessage.spec.js

This change fixes punctuation rendering on the wrong side of the title. The `UserMessage` story is updated to validate this change.
It also removes the file tooltip from the buttons:
Resolves https://github.com/getappmap/appmap-js/issues/2036

fix: Punctuation in RTL text

---

packages/components/src/pages/ChatSearch.vue

Get rid of a click handler on the info popper. It was added for debugging, and left in by mistake.

fix: remove click handler from ChatSearch info

---

packages/cli/src/fulltext/FileIndex.ts
packages/cli/tests/unit/fulltext/FileIndex.spec.ts
packages/cli/tests/unit/rpc/explain/pattern.spec.ts

- **Extended Binary File Extensions List**
Added more file extensions to the list of `BINARY_FILE_EXTENSIONS`.
- **Introduced Data File Extensions List**
Introduced a new list `DATA_FILE_EXTENSIONS`.
- **Refactored File Filtering Logic**
Created helper functions `isBinaryFile` and `isDataFile` to streamline file filtering.
- **Updated File Filtering Method**
Enhanced `filterFiles` function to exclude large data files.
- **Extended Unit Tests**
Modified and added unit tests to cover new filtering logic for binary and data files.
- **Added Test Case for Regex Patterns**
Added a new test case in the pattern matching tests.
Checked-off items have been reviewed by the developer and determined to be non-issues.
Fixes https://github.com/getappmap/appmap-js/issues/2039

feat: Ignore large data files

---

packages/cli/src/fulltext/FileIndex.ts

When indexing files, use `debug`'s argument formatting facility, rather string interpolation.
Also, add `map.js` and `yarn.lock` to the file extensions being ignored.
Fixes #2041 .

Speed up file indexing

---

packages/cli/src/rpc/explain/collectContext.ts
packages/cli/tests/unit/rpc/explain/pattern.spec.ts

Ignore directories such as:
* .yarn
* venv
* .venv
* vendor
* node_modules
Most of these should not be in Git though, so maybe this isn’t needed?

feat: Ignore more directories of vendored code

---

.appmapignore
packages/cli/src/cmds/archive/index.ts
packages/cli/src/fingerprint/fingerprintDirectoryCommand.ts
packages/cli/src/fingerprint/fingerprintWatchCommand.ts
packages/cli/src/lib/emitUsage.ts
packages/cli/tests/unit/lib/emitUsage.spec.ts
packages/client/src/usage.ts

Report run stats as the fingerprint watch command runs.
1. **Refactoring `emitUsage` to `writeUsage`, `collectUsageData`, and `sendUsageData`:**
- **writeUsage:** 
Writes usage statistics for AppMap events and files to a JSON file.
- **collectUsageData:** 
Collects usage data including metadata, number of events, and number of AppMap files.
- **sendUsageData:** 
Sends the usage data to a remote server; if it fails, it logs the data locally.
2. **Updated various files to use the new functions:**
- `packages/cli/src/cmds/archive/index.ts`
- `packages/cli/src/fingerprint/fingerprintDirectoryCommand.ts`
- `packages/cli/src/fingerprint/fingerprintWatchCommand.ts`

feat: Report AppMap usage stats

---

.vscode/settings.json
packages/cli/src/cmds/index/rpcServer.ts
packages/cli/src/lib/shadowLocalhost.ts
packages/cli/tests/unit/lib/shadowLocalhost.spec.ts

In some environments 'localhost' may resolve to either IPv4 or IPv6 depending on the runtime; if the client and the server differ, this could lead to connection problems.
To avoid this issue, attempt to start a server on both localhosts.

fix: Listen on localhost for IPv4 and IPv6

---

packages/components/src/components/SignIn.vue
packages/components/tests/unit/SignIn.spec.js

This is particularly an issue in IntelliJ, where it appears the `keydown` event is not throttled.

fix: Prevent cases where sign in could be requested multiple times

---

packages/navie/src/agents/diagram-agent.ts
packages/navie/src/agents/explain-agent.ts
packages/navie/test/agents/diagram-agent.spec.ts

Fixes #2070 
Note I told it how to quote, but it chose to use underscores anyway (this is copilot, other models might do better).

fix: Prevent LLM from generating special characters in class names

---

.vscode/settings.json
package.json
packages/cli/src/cmds/index/aiEnvVar.ts
packages/cli/src/cmds/index/index.ts
packages/cli/src/rpc/llmConfiguration.ts
packages/navie/.eslintrc.js
packages/navie/package.json
packages/navie/src/interaction-history.ts
packages/navie/src/lib/trajectory.ts
packages/navie/src/navie.ts
packages/navie/src/services/completion-service-factory.ts
packages/navie/src/services/google-vertexai-completion-service.ts
packages/navie/src/services/vector-terms-service.ts
packages/navie/test/fixture.ts
packages/navie/test/services/classification-service.spec.ts
packages/navie/test/services/compute-update-service.spec.ts
packages/navie/test/services/mock-completion-service.ts
packages/navie/test/services/vector-terms-service.spec.ts
yarn.lock

Note to access the API you have to create a service account at https://console.cloud.google.com/apis/credentials — after creation you'll get a JSON file with credentials. This JSON has to be put into `GOOGLE_WEB_CREDENTIALS` environment variable.
Example configuration:
```
GOOGLE_WEB_CREDENTIALS='{   "type": "service_account",   "project_id": "gen-lang-client-0551265112",   "private_key_id": "1fd731b64e9543d54e2921d7cfbe40c5f6f2845a",   "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",   "client_email": "divide-s-navie-experiments@gen-lang-client-0551265112.iam.gserviceaccount.com",   "client_id": "112105442388554579010",   "auth_uri": "https://accounts.google.com/o/oauth2/auth",   "token_uri": "https://oauth2.googleapis.com/token", …
```

feat: Support Gemini via Vertex AI

---

packages/navie/src/services/vector-terms-service.ts

The LLM is now instructed to split compound words into individual search terms. This will improve search performance among lower case search terms that cannot be split by word boundary without a word list.
E.g., given the input
```
@vector-terms htmlconsumer phpclient llmconfiguration
```
The following vector terms are generated
```
html consumer php client llm configuration +htmlconsumer +phpclient +llmconfiguration
```
This is preferred over the current behavior, which outputs the following:
```
htmlconsumer phpclient llmconfiguration +htmlconsumer +phpclient +llmconfiguration
```
Without proper casing, these outputs will not be split on word boundary, resulting in lower quality search results. This previously created a disparity between two inputs like `HTTPServer`, `httpserver`. …

fix: Split compound terms via VectorTermsService

---

packages/navie/src/services/openai-completion-service.ts
packages/navie/test/services/openai-completion-service.spec.ts

Copilot likes to respond with `Sorry, I can't assist with that.` instead of throwing an error when hitting a content filter, which used to lead to useless retry in JSON generation. We special case this to avoid the delay.
Fixes #2089

fix: Don't retry when hitting copilot content filter while generating JSON

---

packages/navie/src/navie.ts
packages/navie/test/lib/parse-options.spec.ts

Giving options to the LLM tends to confuse it; for example seeing `@generate /format=xml` often leads to it suggesting things like `@generate a plan in XML format`. Since the options are a side channel meant for Navie, not the LLM, it should be safe to strip them.

fix: Strip options from chat history given to the LLM

---

packages/components/src/components/SignIn.vue

Send the SSO target when emitting the sign-in event.
Fixes https://github.com/getappmap/board/issues/338 .

fix: pass desired SSO target

---

package.json
packages/navie/package.json
packages/navie/src/services/google-vertexai-completion-service.ts
packages/navie/src/services/vector-terms-service.ts
packages/navie/test/services/google-vertexai-completion-service.spec.ts
yarn.lock

Looking through our Gemini logs I noticed JSON queries sometimes fail:
```
[context-service] Searching for context
SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at GoogleVertexAICompletionService.json (/home/runner/work/navie-benchmark/navie-benchmark/submodules/appmap-js/packages/navie/dist/services/google-vertexai-completion-service.js:54:29)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async VectorTermsService.suggestTerms (/home/runner/work/navie-benchmark/navie-benchmark/submodules/appmap-js/packages/navie/dist/services/vector-terms-service.js:114:26)
```
It's not clear to me why this happened, so I added retry and also logging of the response on error.
EDIT: I actually checked the trajectory and here's what the output was …

fix: Retry JSON queries on Vertex AI

---

.github/workflows/main.yml

This change will automatically cancel any still running or pending jobs from previous commits on a new push to a branch.
As a bonus, it will also cancel pending releases if something new is pushed to main. This means if we merge a couple branches in quick succession it won't lead to multiple releases getting pushed.

chore: Control concurrency of GitHub Actions jobs

---

packages/navie/src/agent.ts
packages/navie/src/agents/diagram-agent.ts
packages/navie/src/agents/explain-agent.ts
packages/navie/src/agents/plan-agent.ts
packages/navie/src/agents/search-agent.ts
packages/navie/src/agents/test-agent.ts
packages/navie/src/services/context-service.ts
packages/navie/test/agent-options.spec.ts
packages/navie/test/agents/diagram-agent.spec.ts
packages/navie/test/services/context-service.spec.ts

Pinned items are now retrieved via a location context lookup, otherwise they are susceptible to being dropped due to [context length constraints](https://github.com/getappmap/appmap-js/blob/main/packages/navie/src/lib/apply-context.ts#L75-L84).
Those locations are additionally added to the exclude list, ensuring that context search does not yield duplicated code snippets.
The following sequence diagram illustrates the flow of a request:
```mermaid
sequenceDiagram
participant CLI as CLI (Client)
box Navie Backend
participant ExplainAgent as ExplainAgent
participant ContextService as ContextService
participant LookupContext as LookupContextService
end
CLI->>ExplainAgent: Send request with options
ExplainAgent->>ContextService: locationContextFromOptions(options) …
```

fix: Retrieve pinned items via location context lookup

---

packages/search/package.json
packages/search/src/build-file-index.ts
packages/search/src/file-type.ts
yarn.lock

Navie tried to index binary files in my project tree that didn't have extensions it knew to be binary (for example, executable binaries). This can be a problem with compiled languages such as rust, go, C(++), etc. which usually produce extensionless executables on non-Windows platforms.
To avoid this problem, use file sniffing (provided by isbinaryfile package) to skip binary files. This improves search time from 1m34.054s to 0m3.047s in my test project.
I've done a bunch of experiments (parsers, parallelization, dropping Unicode etc.) but in the end the solution turned out to be trivial. There is still room for improvement (searching my 58 MiB /usr/include takes about 15 s which is at the upper bound of acceptable) but with this simple change it's fast enough to fix #2126

Improve search performance by sniffing out and skipping binary files

---

packages/cli/src/cmds/search/search.ts
packages/cli/src/rpc/explain/collect-search-context.ts
packages/cli/src/rpc/explain/collect-snippets.ts
packages/cli/src/rpc/explain/index/appmap-file-index.ts
packages/cli/src/rpc/explain/index/appmap-index.ts
packages/cli/src/rpc/explain/index/project-file-index.ts
packages/cli/src/rpc/explain/index/project-file-snippet-index.ts
packages/cli/src/rpc/search/search.ts
packages/cli/tests/unit/rpc/explain/collect-search-context.spec.ts
packages/cli/tests/unit/rpc/explain/index/appmap-index.search.spec.ts
packages/search/README.md
packages/search/src/cli.ts
packages/search/src/file-index.ts
packages/search/src/index.ts
packages/search/src/session-id.ts
packages/search/src/snippet-index.ts
packages/search/test/file-index.spec.ts
packages/search/test/snippet-index.spec.ts

This allows multiple jobs / sessions to be using the index concurrently, applying different boost factors according to their needs.
When searching for code and files, add a session id for the boost records.
When searching, the session id is a required argument, and it is used to select only the boost
records that are relevant to the current search session.
---
/include=search/src
Plan changes only in packages/search/src
**Add session id to search boost records in packages/search**
**Problem**
The search system needs to differentiate between boost records from different search sessions to ensure boost records only affect search results within their intended context. This change should be implemented within the `packages/search/src` directory.
**Analysis**
We need to modify the file index …

feat: Associate boost factor data with a session id

---

.github/workflows/build-native-scanner.yml
.github/workflows/build-native.yml

GitHub Actions is starting the deprecation process for macOS 12. While the image is being deprecated, You may experience longer queue times during peak usage hours.

fix: Update macos runners to macos-latest

---

packages/navie/src/commands/review-command.ts
packages/navie/test/commands/review-command.spec.ts

JetBrains IDEs (IntelliJ, etc.) were sending pinned items as 'code selections' without location information, causing them to be ignored during the `@review` command. This resulted in incomplete context being considered during code reviews in JetBrains environments.
Modified the `getPinnedItems` function to include code selections that don't have location information. This maintains backward compatibility while ensuring that pinned items in JetBrains IDEs are properly included in the review context.
- Enhanced pinned item handling to include code selections without locations
- Added compatibility layer for JetBrains IDE pinned items
- Added test coverage to verify the handling of non-located code selections
- Maintained existing functionality for code selections with locations
- Added new …

fix: Review now includes code selections

---

architecture/navie-chat/welcome-message-v1.md
packages/cli/src/cmds/index/rpc.ts
packages/cli/src/cmds/index/rpcServer.ts
packages/cli/src/rpc/navie/metadata.ts
packages/cli/src/rpc/navie/welcome-suggestion.ts
packages/cli/src/rpc/navie/welcome.ts
packages/cli/tests/unit/rpc/navie/metadata.spec.ts
packages/cli/tests/unit/rpc/navie/welcome.spec.ts
packages/components/src/components/SkeletonLoader.vue
packages/components/src/components/chat/Chat.vue
packages/components/src/components/chat/ChatInput.vue
packages/components/src/components/chat/WelcomeMessageV1.vue
packages/components/src/components/chat/WelcomeMessageV2.vue
packages/components/src/lib/AppMapRPC.ts
packages/components/src/pages/ChatSearch.vue
packages/components/src/stories/chat-search/ChatSearch.stories.js
packages/components/src/stories/chat-search/WelcomeMessage.stories.js
packages/components/tests/unit/WelcomeMessageV1.spec.js
packages/components/tests/unit/WelcomeMessageV2.spec.ts
packages/components/tests/unit/chat/ChatInput.spec.js
packages/components/tests/unit/chat/ChatSearch.spec.js
packages/navie/src/commands/welcome-command.ts
packages/rpc/src/navie.ts

Introduces a new version of the welcome message UI that provides a more structured and context-aware experience. The key changes include:
- Splitting the welcome message into static and dynamic parts to improve initial load time
- Adding support for displaying the current activity name and related suggestions
- Introducing new RPC methods for metadata (v2) and welcome message content
- Preserving backward compatibility with v1 welcome message format
The new UI shows a standard greeting header followed by either:
- A custom welcome message in markdown format, or
- The current activity name with relevant suggestions presented as a bulleted list
Resolves #2155
Resolves #2148

feat: Navie welcome message UI

---

packages/navie/src/commands/explain-command.ts

In refactoring the `/gather` flag somehow got changed to `/gatherer`. This change changes it back.

fix: Fix a typo in `/gather` option

---

packages/cli/src/lib/executeCommand.ts
packages/cli/src/lib/git.ts
packages/cli/tests/integration/git.spec.ts

Updated the Git working directory diff functionality to include both tracked and untracked files. Previously, the system would only return changes to files already tracked by Git, which limited visibility into new files added to the project.
- Added functionality to detect and include untracked files in working directory diffs
- Implemented platform-specific handling for null device paths
- Added comprehensive integration tests for Git operations
- Enhanced the execute command to support custom exit codes
- Added proper error handling and logging for Git operations
New integration tests verify:
- Changes to tracked files
- New untracked files
- Command injection protection
- Error cases and edge conditions
The system now combines diffs from both tracked files (via `git diff HEAD`) and …

fix: Working changes include untracked files

---

packages/navie/src/context.ts
packages/navie/src/services/classification-service.ts

I've encountered a query that led OpenAI to insist on classifying something with 'low' score, leading to a parse error and retrying.
This change allows 'low' scores in the response schema. (An alternative approach would have been to remove 'low' score from the prompt, but it can be valuable to collect these low scores.)

fix: Allow 'low' classification score

---

packages/cli/src/rpc/navie/isCustomWelcomeMessageEnabled.ts
packages/cli/src/rpc/navie/welcome-suggestion.ts

This change will enable the custom welcome message for everyone once released.
`NAVIE_CUSTOM_WELCOME_MESSAGE` can still be set to `false` to disable this behavior. Any other value will be leave the custom welcome message enabled.

fix: Default the custom welcome message to ON

---

packages/navie/src/commands/explain-command.ts
packages/navie/src/services/classification-service.ts

This pull request includes improvements to error handling and configuration in the `navie` package. The most important changes involve adding error handling for the `classifyQuestion` method and configuring the maximum retries for the `completion.json` method.
Error handling improvements:
* [`packages/navie/src/commands/explain-command.ts`](diffhunk://#diff-8fc64b3b138b643930110c42f044e061bdc178fb607f1fbcf34bd30b7b13e95cL52-R57): Added a catch block to handle errors in the `classifyQuestion` method, logging a warning and returning an empty array if an error occurs.
Configuration updates:
* [`packages/navie/src/services/classification-service.ts`](diffhunk://#diff-b9faab5fe978dd5609f5f1675dd6a4aced72c85ef9ba20289c8225c5cc8ac540R183): Configured the `completion.json` method to have a …

fix: Only try once in classifier, ignore classifier errors

---

packages/cli/src/rpc/explain/review.ts
packages/cli/tests/unit/rpc/explain/review.spec.ts

This pull request updates the review functionality to encompass both committed and uncommitted changes in the review process. By integrating changes made to the workspace before being committed, the review command now provides a comprehensive analysis that includes any working changes alongside the commit log, enhancing the review process's robustness.
- Modified functionality in the review command to fetch the working diff alongside the commit diff.
- Enhanced the handling of user context by amalgamating both the working changes and the commits into the review output.
- This improvement ensures that reviewers have complete visibility into all code changes, offering a more thorough and effective code review process.
- Facilitates the review of branches like `main` or `master` when changes …

fix: Include working changes during @review

---

.github/workflows/main.yml
packages/cli/tests/unit/sequenceDiagram.spec.ts
packages/components/src/components/chat-search/LlmConfiguration.vue
packages/components/src/components/chat/ChatInput.vue
packages/components/src/pages/ChatSearch.vue
packages/components/tests/unit/chat/ChatInput.spec.js
packages/components/tests/unit/chat/ChatSearch.spec.js
packages/components/tests/unit/chat/LlmConfiguration.spec.js

This pull request introduces a feature flag to control the display of subscription-related indicators within the Navie chat. 
- **Feature Flag Addition**: A new boolean feature flag named `displaySubscription` has been introduced across relevant components. This flag defaults to `false` and is configurable via props.
- **Conditional Rendering**: The components `ChatSearch`, `ChatInput`, and `LlmConfiguration` have been updated to conditionally render subscription indicators based on the `displaySubscription` flag.
- **CSS Adjustments**: Minor CSS changes were made to handle visual layout when subscription indicators are hidden to maintain a clean UI appearance.
- **Unit Tests**: Additional unit tests have been introduced to ensure that components behave as expected when the …

fix: Subscription indicators are now behind a feature flag

---

packages/cli/src/rpc/explain/buildContext.ts
packages/cli/src/rpc/explain/lookupSourceCode.ts
packages/cli/tests/unit/rpc/explain/buildContext.spec.ts
packages/cli/tests/unit/rpc/explain/lookupSourceCode.spec.ts

This pull request includes several changes to improve the handling and testing of source code snippets in the `buildContext` and `lookupSourceCode` functions. The most important changes include modifying the `lookupSourceCode` function to return an object with content and location, updating the `buildContext` function to accommodate this change, and adding new unit tests for `lookupSourceCode`.
Improvements to `lookupSourceCode` function:
* [`packages/cli/src/rpc/explain/lookupSourceCode.ts`](diffhunk://#diff-626e77ca4eebdac8e17c8b86fd555197c5f97ff00a711e09f04ef090dfe8e08dL32-R32): Modified `lookupSourceCode` to return an object with `content` and `location` instead of an array of strings. This change ensures that the returned snippet includes both the content and its precise location. …

fix: Return whole lines when looking up source code

---

packages/cli/src/cmds/navie/help.ts

Keywords are coming in to the help search in a somewhat unprocessed form, including non-word/letter characters such as `+`. These characters are breaking the search, since they have special meaning to the search engine or are resulting in the search producing no results.

fix: Convert raw keywords to query terms when searching for help

---

packages/components/src/components/chat/ChatInput.vue
packages/components/src/stories/ChatInput.stories.js

Also, add a storybook story for this so we can see if the problem reoccurs.
(NB, the whole popper component is an abomination and should be nuked. A task for another day.)
Fixes #2048

fix: Don't cover the stop button with the tooltip

---

packages/components/src/components/chat/UserMessage.vue
packages/components/tests/unit/chat/UserMessage.spec.js
packages/navie/src/services/next-step-classification-service.ts

When suggesting a next step in the conversation, prepend the suggestion "pill" (button) with the command prefix, unless the command prefix is `@explain`.
For example, this button will show `@test Generate Test Cases` rather than `Generate Test Cases` (which could be construed as `@test` or `@generate` otherwise).
-- 
Fixes #2198

feat: Display @command in next step suggestions

---

packages/cli/src/rpc/explain/index/appmap-index.ts
packages/cli/tests/unit/rpc/explain/index/appmap-index.spec.ts
packages/search/src/build-file-index.ts
packages/search/src/build-snippet-index.ts
packages/search/src/splitter.ts
packages/search/src/tokenize.ts
packages/search/test/tokenize.spec.ts

This pull request addresses several issues related to the tokenization process and efficiency improvements across search. The key changes are described below:
- **Tokenization Process Improvement**: 
- The tokenization process has been updated to prevent the process from hanging. Tokenization is now performed in batches which periodically yield back to the main event loop, enhancing the system's responsiveness.
- The `indexFile` function now handles asynchronous tokenization, and adjustments were made to accommodate the change to a promise-based return from the `tokenizer` function.
- A new `batch` function was introduced to handle line batching, ensuring efficient processing by taking into account line lengths and batch sizes.
- **Accuracy Improvements**: 
- The file extension is now …

fix: Tokenization performance

---

packages/cli/esbuild.html.ts
packages/cli/src/cmds/index/rpcServer.ts
packages/cli/src/cmds/navie.ts
packages/cli/src/html/navie.js
packages/cli/src/lib/serveAndOpen.ts
packages/cli/src/rpc/explain/explain.ts

Add a --ui flag to the navie command which:
- Starts an RPC server on an open port
- Opens the Navie UI in the system browser configured to connect to that port
This is useful for using / debugging the UI while the UI and RPC/Navie are both in development at the same time.
```
./built/cli.js navie --ui -d $(pwd)/../..
Setting RPC configuration: {"projectDirectories":["/Users/kgilpin/source/appland/appmap-js/packages/cli/../.."],"appmapConfigFiles":["/Users/kgilpin/source/appland/appmap-js/appmap.yml"]}
No output specified, writing to stdout
Detected code editor: vscode
Opening navie.html
```
This branch is proposed to merge into `develop`, along with the other fix branches that I will be pushing.

feat: navie --ui

---

packages/components/src/components/chat/Chat.vue
packages/components/src/components/chat/CodeSelection.ts
packages/components/src/pages/ChatSearch.vue
packages/components/src/stories/ChatInput.stories.js
packages/components/tests/unit/chat/ChatComponent.spec.js

Fixes https://github.com/getappmap/appmap-js/issues/2188
Here's a sequence diagram that Navie generated for me, which I like.
```mermaid
sequenceDiagram
participant User
participant VChatInput
participant VChat
participant VChatSearch
participant ExplainRpc
participant Navie
User->>VChatInput: Enter message with code selection
VChatInput->>VChat: sendMessage(message, codeSelections)
rect rgb(150, 150, 150)
Note over VChat: Change: Parse code selection
VChat->>VChat: Parse codeSelection
end
VChat->>VChatSearch: sendMessage(message, codeSelections, appmaps)
rect rgb(150, 150, 150)
Note over VChatSearch: Change: Handle CodeSelection objects
VChatSearch->>VChatSearch: Process codeSelections
VChatSearch->>VChatSearch: Create userProvidedContext
end
VChatSearch->>ExplainRpc: Create …
```

fix: Propagate code selection location to Navie

---

packages/components/src/components/chat/ChatInput.vue
packages/components/src/stories/ChatInput.stories.js
packages/components/tests/e2e/specs/chat/chatSearch.spec.js

This drops the `focus` selector hackery in favor of using `HTMLElement` `focus` method and binding to the window's `onfocus` event handler property.
We can remove any existing code editor integration to handle focus.
Fixes https://github.com/getappmap/appmap-js/issues/2156

fix: Focus the chat input automatically

---

packages/cli/src/rpc/explain/ContentRestrictions.ts
packages/cli/src/rpc/explain/collect-location-context.ts
packages/cli/src/rpc/explain/index/project-file-index.ts
packages/cli/tests/unit/rpc/explain/ContentRestrictions.spec.ts
packages/cli/tests/unit/rpc/explain/collect-location-context.spec.ts
packages/cli/tests/unit/rpc/explain/index/project-file-index.spec.ts

This pull request introduces a new `ContentRestrictions` class to manage and enforce file access restrictions based on global and local patterns. The changes include adding the `ContentRestrictions` class, integrating it into existing modules, and adding tests to ensure its functionality.
Key changes:
* [`packages/cli/src/rpc/explain/ContentRestrictions.ts`](diffhunk://#diff-eaf89054e06a974f6aa074c060639ff54572496c15f713e1a6a5eecb7dec4204R1-R159): Introduced the `ContentRestrictions` class to handle global and local file access restrictions. The class includes methods to set restrictions, check if a path is restricted, and load default patterns.
* [`packages/cli/src/rpc/explain/collect-location-context.ts`](diffhunk://#diff-d7f5141d81d7f3bafdbeabf3a4340ec108839cd6579cbdff09855f7f9b17c741R9 …

feat: Support for file exclusion patterns in Navie

---

docs/using-navie-ai/bring-your-own-model.md

Sync docs from https://github.com/getappmap/applandinc.github.io

feat: Sync docs from applandinc.appmap.io

---

packages/cli/src/rpc/explain/location.ts
packages/cli/tests/unit/rpc/explain/location.spec.ts

In practice, Windows paths are represented in many different forms. Path separators are interchangable and paths are case insensitive. Additionally, paths constructed via a file scheme URI may contain a leading slash, similar to an absolute path in POSIX.
This was preventing pinned items from being picked up in Windows. A pinned file path may be something like:
```
/c:/Users/Administrator/Project/app.rb:2-24
```
This is problematic for a few reasons:
1. The leading slash corrupts the path and it is not usable. Ideally clients would not send us paths formatted in this manner, but it's already happening. This behavior is observed both from JetBrains and Visual Studio Code.
2. The path separators are valid, but don't match other cases in our code, such as when we compare the absolute file …

fix: Normalize Windows path locations

---

packages/navie/src/agents/plan-agent.ts
packages/navie/test/agents/plan-agent.spec.ts

Introduce a default problem statement for the PlanAgent when no user input is provided, ensuring a consistent response in such cases. Add a test to verify this behavior.

Provide default prompt for empty questions in PlanAgent

---

packages/navie/src/agents/generate-agent.ts
packages/navie/src/lib/split-on.ts
packages/navie/test/agents/generate-agent.spec.ts
packages/navie/test/lib/split-on.spec.ts

Models that mix languages sometimes generate non-XML fences around changesets. This update filters out these fences to ensure proper rendering.
Fixes #2248

Strip non-XML fences on changesets

---

packages/cli/src/rpc/explain/explain.ts
packages/cli/src/rpc/explain/location.ts
packages/navie/src/agents/diagram-agent.ts
packages/navie/src/agents/generate-agent.ts
packages/navie/src/agents/plan-agent.ts
packages/navie/src/commands/explain-command.ts
packages/navie/src/interaction-history.ts
packages/navie/src/lib/split-on.ts
packages/navie/src/services/code-selection-service.ts
packages/navie/src/services/file-change-extractor-service.ts
packages/navie/src/services/openai-completion-service.ts
packages/navie/src/user-context.ts
packages/navie/test/agents/generate-agent.spec.ts
packages/navie/test/agents/plan-agent.spec.ts
packages/navie/test/integration/pinned-items.spec.ts
packages/navie/test/lib/split-on.spec.ts

1. Pinned items are now presented solely in the user context. Previously they were split between user and system context, where a path to the file would be presented in user context but the actual contents were written to the system context. It'd be up to the LLM to make the association.
2. Some changes to the `@plan` prompt to nudge it more towards presenting relative file paths in the plan output. With gpt-4o, plan would often only include a basename or an identifier found in the code.
3. User selected context paths are now normalized on ingress so that they don't need to be spot fixed where ever we're comparing paths internally.
4. Some additional logging is added to help troubleshoot cases where Navie becomes unresponsive
5. `@diagram` now has a default prompt. Without user input, …

Improving generation consistency

---

packages/cli/src/cmds/index/rpc.ts
packages/cli/src/cmds/navie.ts
packages/search/src/cli.ts

PerformanceObserver wasn't globally available in node 18, leading to crashes

feat: Add PerformanceObserver import

---

packages/cli/src/cmds/index/rpc.ts
packages/cli/src/rpc/explain/navie/navie-local.ts
packages/cli/src/rpc/navie/isCustomWelcomeMessageEnabled.ts
packages/cli/src/rpc/navie/models/handlers/add.ts
packages/cli/src/rpc/navie/models/handlers/getConfig.ts
packages/cli/src/rpc/navie/models/handlers/list.ts
packages/cli/src/rpc/navie/models/handlers/select.ts
packages/cli/src/rpc/navie/models/providers/anthropic.ts
packages/cli/src/rpc/navie/models/providers/ollama.ts
packages/cli/src/rpc/navie/models/providers/openai.ts
packages/cli/src/rpc/navie/models/registry.ts
packages/cli/src/rpc/navie/models/util.ts
packages/cli/tests/unit/rpc/navie/models/registry.spec.ts
packages/components/src/components/Badge.vue
packages/components/src/components/chat-search/ModelSelector.vue
packages/components/src/components/chat/Chat.vue
packages/components/src/lib/AppMapRPC.ts
packages/components/src/pages/ChatSearch.vue
packages/components/tests/e2e/specs/chat/chatSearch.spec.js
packages/components/tests/unit/chat/ChatSearch.spec.js
packages/components/tests/unit/chat/ModelSelector.spec.js
packages/navie/src/index.ts
packages/navie/src/navie.ts
packages/navie/src/services/completion-service-factory.ts
packages/navie/src/services/completion-service.ts
packages/navie/src/services/ollama-completion-service.ts
packages/navie/src/services/openai-completion-service.ts
packages/navie/test/services/completion-service-factory.spec.ts
packages/rpc/src/navie.ts

This PR implements a new model selector UI and supporting backend services, allowing users to choose between different AI models for Navie.
- Added new RPC method definitions for model management (`v1.navie.models`)
- Includes methods for adding, listing, selecting, and getting model configurations
- Added support for per-message model overrides
- Implemented Ollama completion service
- Enhanced completion service factory to handle different model providers
- Added configuration for model-specific token limits
- Added support for custom API endpoints and keys
- Added new ModelSelector.vue component with dropdown and configuration UI
- Integrated model selector with Chat.vue
- Updated ChatSearch.vue to handle model selection
- Added styling for model badges and configuration UI
- Added …

feat: Replace LLM configuration with model selector

---

packages/cli/src/rpc/explain/navie/navie-local.ts
packages/cli/src/rpc/navie/register.ts
packages/cli/src/rpc/navie/services/threadService.ts
packages/cli/src/rpc/navie/thread/index.ts
packages/cli/tests/unit/rpc/navie/services/threadService.spec.ts
packages/cli/tests/unit/rpc/navie/thread/index.spec.ts

This PR addresses several issues related to thread handling and message processing in the Navie chat system:
1. Fixed file path handling when pinning items by converting URIs to filesystem paths
2. Improved thread initialization to ensure threads are properly persisted to disk
3. Enhanced message acknowledgment timing to prevent duplicate messages in chat history
- Thread initialization now flushes conversation state to disk immediately
- Message acknowledgment occurs after chat history is read, preventing duplicate messages
- URI paths are converted to filesystem paths for better context lookup
- Added error handling for URI parsing during context conversion
- Updated unit tests to handle async thread registration
These changes improve the reliability of chat thread persistence and …

Thread Initialization and Message Handling Improvements

---

packages/components/src/components/chat-search/StreamingMessageContent.ts
packages/components/src/components/chat/ContextContainer.vue
packages/components/src/components/chat/UserMessage.vue
packages/components/tests/unit/chat/ContextContainer.spec.js
packages/components/tests/unit/chat/UserMessage.spec.ts

Note that this isn't currently supported by the thread backend, so these blocks do not have identifiers and cannot be pinned.
Resolves #2273

fix: Restore frontend rendering of diff blocks

---

packages/cli/src/rpc/navie/services/threadIndexService.ts

This PR addresses two issues related to the Navie chat history database managed by `ThreadIndexService`:
*   **Database Rename:** The underlying SQLite database file has been renamed from `~/.appmap/navie/thread-index.db` to `~/.appmap/navie/chat-history.db`. This provides a more accurate name for its purpose. (See commit `3670f77f`)
*   **Migration Robustness:** The `migrate` function now attempts to run migrations even if the initial check for the database version (`shouldMigrate()`, which queries `user_version`) throws an error. Previously, such an error would prevent migrations from running. This change improves robustness, allowing the system to potentially recover or initialize the database correctly in cases where it might be corrupted or inaccessible for the version check. An …

fix: Update database name

---

packages/cli/package.json
packages/cli/src/cmds/search/search.ts
packages/cli/src/rpc/explain/index-snippets.ts
packages/cli/src/rpc/explain/index/appmap-file-index.ts
packages/cli/src/rpc/explain/index/project-file-index.ts
packages/cli/src/rpc/explain/index/project-file-snippet-index.ts
packages/cli/src/rpc/navie/services/threadIndexService.ts
packages/cli/src/rpc/search/search.ts
packages/cli/tests/setup.js
packages/cli/tests/unit/rpc/navie/services/threadIndexService.spec.ts
packages/navie/package.json
packages/search/package.json
packages/search/src/cli.ts
packages/search/src/file-index.ts
packages/search/src/snippet-index.ts
packages/search/test/file-index.spec.ts
packages/search/test/snippet-index.spec.ts
yarn.lock

While node-sqlite3-wasm was a good idea, it turned out to cause problems due to its simplistic locking strategy. File-based lock in conjunction with limited cleanup caused users to encounter "database is locked" errors with no recourse. It's possible to work on node-sqlite3-wasm to improve locking (and statement cleanup), but it's probably safer to move back to better-sqlite3 at least for now. Unfortunately this means shipping the compiled blob, with possible issues with some windows antivirus software and making it harder to use a different distribution strategy in the future :/
This reverts commit 86e0fe5386286816473c0b16a91f7fa80f8706af.

fix: Migrate from node-sqlite3-wasm to better-sqlite3

---

packages/cli/src/lib/processPatchset.ts
packages/cli/tests/unit/lib/processPatchset.spec.ts

This pull request enhances the `processPatchset` function in the `packages/cli` module by introducing an ignore list feature to filter out irrelevant file changes, such as dependencies or generated files. It also includes unit tests to ensure the functionality works as expected. The most important changes are detailed below.
* **Added support for an ignore list:** The `processPatchset` function now accepts an `ignoreList` parameter, which specifies paths to exclude when processing patchsets. A default ignore list (`DEFAULT_IGNORE_LIST`) is provided, covering common directories and files like `node_modules`, `dist`, and lock files.
* **Implemented `buildIgnoreRegex` helper function:** This function generates a regular expression from the ignore list to efficiently filter out unwanted paths …

feat: Ignore some files in the diff and remove diff size limit

---

packages/cli/src/rpc/explain/parseLocation.ts
packages/cli/tests/unit/rpc/explain/parseLocation.spec.ts

It seems that sometimes appmaps contain -1 as a placeholder for unknown line number. Handle this case gracefully.
Fixes #2304

fix: Update parseLocation to handle negative line numbers correctly

---

packages/cli/src/rpc/explain/collect-location-context.ts
packages/cli/src/rpc/explain/fileFilter.ts
packages/cli/src/rpc/explain/index/project-file-index.ts
packages/cli/tests/unit/rpc/explain/collect-location-context.spec.ts
packages/search/src/cli.ts
packages/search/src/file-index.ts
packages/search/src/file-type.ts
packages/search/test/file-index.spec.ts
packages/search/test/file-type.spec.ts

This pull request introduces several optimizations and a critical bug fix to the file indexing process, significantly reducing the time required to index a project and ensuring the index is correctly maintained between sessions.
This PR addresses performance bottlenecks and a correctness issue within the file search indexer:
*   **Optimized Binary File Detection with Caching:** To minimize disk I/O during indexing, the binary file detection logic now uses a cache. This cache is pre-populated with a list of common binary and source-code file extensions to avoid hitting the disk for most files. For unknown file types, the result of the check is cached for subsequent lookups.
*   **Improved I/O Concurrency for Faster Indexing:** The file-type checking process has been made asynchronous. This …

fix: Improve worst case performance of file indexing

---

packages/navie/src/services/completion-service.ts
packages/navie/src/services/openai-completion-service.ts
packages/navie/test/services/completion-service.spec.ts
packages/navie/test/services/openai-completion-service.spec.ts

**Problem:**
Currently, when a user exceeds their monthly request limit for a service like Copilot, the application does not provide any specific feedback. This leads to a confusing user experience where the service silently stops working, leaving the request hanging and the user unsure of the cause.
**Solution:**
This change introduces proper handling for billing-related errors to ensure users receive clear and actionable feedback.
1.  A new, specific `PaymentRequiredError` has been created to represent this state. This error contains a static, user-friendly message explaining that the service requires payment or a subscription check.
2.  The OpenAI completion service has been updated to detect HTTP `402` status codes in API responses.
3.  When a `402` error is detected, it is wrapped in …

fix: Surface billing-related errors to the user
